// mdfn/solid/src/index.tsx
import { createEffect, createSignal, onCleanup, splitProps, type Accessor, type Component, type JSX } from "solid-js";
import { createAdapterBridge, type AdapterSnapshot } from "@mdfn/adapter-kit";
import { smallestSourceChange, Transaction, type EditorController } from "@mdfn/core";
import type { DomCommand, DomEditor } from "@mdfn/dom";
import type { EditorMode, SourceEditor } from "@mdfn/source";

export function createMdfnSignal(controller: EditorController): Accessor<AdapterSnapshot> {
  const bridge = createAdapterBridge(controller);
  const [snapshot, setSnapshot] = createSignal(bridge.getSnapshot());
  const unsubscribe = bridge.subscribe(() => setSnapshot(bridge.getSnapshot()));
  onCleanup(() => { unsubscribe(); bridge.destroy(); });
  return snapshot;
}

export interface MdfnEditorProps extends JSX.HTMLAttributes<HTMLDivElement> {
  readonly controller: EditorController;
  readonly mode?: EditorMode;
  readonly readOnly?: boolean;
  readonly ariaLabel?: string;
  readonly onLoadError?: (error: Error) => void;
  readonly editorRef?: (value: MdfnEditorHandle | null) => void;
  readonly onFiles?: (files: readonly File[]) => void | Promise<void>;
}

export interface MdfnEditorHandle { focus(): void; run(command: DomCommand): boolean; can(command: DomCommand): boolean; setLink(href: string, title?: string): boolean; removeLink(): boolean; insertTable(rows?: number, columns?: number): boolean; insertMarkdown(markdown: string): boolean; }

export const MdfnEditor: Component<MdfnEditorProps> = (props) => {
  type ShellForwardedProps = MdfnEditorProps & {
    readonly toolbarGroups?: unknown;
    readonly hideToolbar?: boolean;
    readonly hideAuthoringChrome?: boolean;
    readonly actor?: unknown;
    readonly onSelectFiles?: unknown;
    readonly onModeChange?: unknown;
  };
  const [local, , rest] = splitProps(
    props as ShellForwardedProps,
    ["controller", "mode", "readOnly", "ariaLabel", "onLoadError", "editorRef", "onFiles"],
    ["toolbarGroups", "hideToolbar", "hideAuthoringChrome", "actor", "onSelectFiles", "onModeChange"],
  );
  let visualTarget: HTMLDivElement | undefined;
  let sourceTarget: HTMLDivElement | undefined;
  let previewTarget: HTMLDivElement | undefined;
  let visual: DomEditor | undefined;
  let source: SourceEditor | undefined;
  const [loadError, setLoadError] = createSignal<Error | null>(null);
  const [fallbackValue, setFallbackValue] = createSignal(local.controller.getState().markdown);
  const [version, setVersion] = createSignal(local.controller.getState().version);

  createEffect(() => {
    const controller = local.controller;
    setFallbackValue(controller.getState().markdown);
    setVersion(controller.getState().version);
    const unsubscribe = controller.subscribe((change) => {
      setFallbackValue(change.current.markdown);
      setVersion(change.current.version);
    });
    onCleanup(unsubscribe);
  });

  const handle: MdfnEditorHandle = { focus() { visual?.focus(); source?.focus(); }, run(command) { return visual?.run(command) ?? false; }, can(command) { return visual?.can(command) ?? false; }, setLink(href, title) { return visual?.setLink(href, title) ?? false; }, removeLink() { return visual?.removeLink() ?? false; }, insertTable(rows, columns) { return visual?.insertTable(rows, columns) ?? false; }, insertMarkdown(markdown) { return visual?.insertMarkdown(markdown) ?? false; } };
  createEffect(() => {
    const mode = local.mode ?? "visual";
    const controller = local.controller;
    const readOnly = local.readOnly === true || mode === "read-only";
    const ariaLabel = local.ariaLabel ?? "Markdown editor";
    const onFiles = local.onFiles;
    const editorRef = local.editorRef;
    const onLoadError = local.onLoadError;
    let cancelled = false;
    let mountedVisual: DomEditor | undefined;
    let mountedSource: SourceEditor | undefined;
    const destroyMounted = (): void => {
      mountedVisual?.destroy();
      mountedSource?.destroy();
      if (visual === mountedVisual) visual = undefined;
      if (source === mountedSource) source = undefined;
      mountedVisual = undefined;
      mountedSource = undefined;
    };
    visual?.destroy();
    source?.destroy();
    visual = undefined;
    source = undefined;
    setLoadError(null);
    const mount = async (): Promise<void> => {
      try {
        await Promise.resolve();
        if (cancelled) return;
        if ((mode === "visual" || mode === "split") && visualTarget) {
          const module = await import("@mdfn/dom");
          if (cancelled) return;
          mountedVisual = module.createDomEditor({ target: visualTarget, controller, readOnly, attributes: { "aria-label": ariaLabel }, onFiles });
          visual = mountedVisual;
        }
        if ((mode === "source" || mode === "split") && sourceTarget) {
          const module = await import("@mdfn/source");
          if (cancelled) return;
          mountedSource = module.createSourceEditor({ target: sourceTarget, controller, readOnly, ariaLabel: `${ariaLabel} source` });
          source = mountedSource;
        }
        if ((mode === "preview" || mode === "read-only") && previewTarget) {
          const module = await import("@mdfn/source");
          if (cancelled) return;
          previewTarget.innerHTML = module.createPreview(controller).html;
        }
        editorRef?.(handle);
      } catch (error) {
        destroyMounted();
        if (cancelled) return;
        const resolved = error instanceof Error ? error : new Error(String(error));
        setLoadError(resolved);
        onLoadError?.(resolved);
      }
    };
    void mount();
    onCleanup(() => { cancelled = true; editorRef?.(null); destroyMounted(); });
  });

  createEffect(() => {
    version();
    const mode = local.mode ?? "visual";
    const controller = local.controller;
    const onLoadError = local.onLoadError;
    if ((mode !== "preview" && mode !== "read-only") || !previewTarget) return;
    let cancelled = false;
    void import("@mdfn/source").then((module) => {
      if (!cancelled && previewTarget) previewTarget.innerHTML = module.createPreview(controller).html;
    }).catch((error: unknown) => {
      if (cancelled) return;
      const resolved = error instanceof Error ? error : new Error(String(error));
      setLoadError(resolved);
      onLoadError?.(resolved);
    });
    onCleanup(() => { cancelled = true; });
  });

  const updateFallback: JSX.EventHandler<HTMLTextAreaElement, InputEvent> = (event) => {
    const markdown = event.currentTarget.value;
    const current = local.controller.getState().markdown;
    const change = smallestSourceChange(current, markdown);
    if (change) local.controller.dispatch(new Transaction().replaceSource(change.from, change.to, change.insert).withSource("solid:fallback"));
  };

  return (
    <div {...rest} data-mdfn-solid="editor" data-mode={local.mode ?? "visual"}>
      {loadError() ? (
        <div data-mdfn-source-fallback="true">
          <div role="status">Visual editor unavailable: {loadError()!.message}</div>
          <textarea aria-label={`${local.ariaLabel ?? "Markdown editor"} source fallback`} value={fallbackValue()} readOnly={local.readOnly === true || local.mode === "read-only"} onInput={updateFallback} />
        </div>
      ) : (
        <>
          {((local.mode ?? "visual") === "visual" || local.mode === "split") && <div ref={visualTarget} data-mdfn-surface="visual" />}
          {(local.mode === "source" || local.mode === "split") && <div ref={sourceTarget} data-mdfn-surface="source" />}
          {(local.mode === "preview" || local.mode === "read-only") && <div ref={previewTarget} data-mdfn-surface="preview" aria-label={local.ariaLabel ?? "Markdown editor"} />}
        </>
      )}
    </div>
  );
};

export const MDFN_SOLID_VERSION = "0.1.0" as const;

// mdfn/react/src/index.tsx
"use client";

import * as React from "react";
import type { AdapterSnapshot } from "@mdfn/adapter-kit";
import { smallestSourceChange, Transaction, type EditorController } from "@mdfn/core";
import type { DomCommand, DomEditor } from "@mdfn/dom";
import type { EditorMode, SourceEditor } from "@mdfn/source";

export function useMdfn(controller: EditorController): AdapterSnapshot {
  const subscribe = React.useCallback((listener: () => void) => controller.subscribe(listener), [controller]);
  const getSnapshot = React.useCallback(() => controller.getState(), [controller]);
  const state = React.useSyncExternalStore(subscribe, getSnapshot, getSnapshot);
  return React.useMemo(() => ({
    state,
    version: state.version,
    markdown: state.markdown,
    dirty: state.dirty,
    canUndo: controller.canUndo(),
    canRedo: controller.canRedo(),
  }), [controller, state]);
}

export interface MdfnEditorHandle {
  focus(): void;
  run(command: DomCommand): boolean;
  can(command: DomCommand): boolean;
  setLink(href: string, title?: string): boolean;
  removeLink(): boolean;
  insertTable(rows?: number, columns?: number): boolean;
  insertMarkdown(markdown: string): boolean;
}

export interface MdfnEditorProps extends Omit<React.HTMLAttributes<HTMLDivElement>, "children"> {
  readonly controller: EditorController;
  readonly mode?: EditorMode;
  readonly readOnly?: boolean;
  readonly ariaLabel?: string;
  readonly onLoadError?: (error: Error) => void;
  readonly onReady?: (handle: MdfnEditorHandle) => void;
  readonly onFiles?: (files: readonly File[]) => void | Promise<void>;
}

export const MdfnEditor = React.forwardRef<MdfnEditorHandle, MdfnEditorProps>(function MdfnEditor(
  { controller, mode = "visual", readOnly = false, ariaLabel = "Markdown editor", onLoadError, onReady, onFiles, className, ...props },
  forwardedRef,
) {
  const effectiveReadOnly = readOnly || mode === "read-only";
  const snapshot = useMdfn(controller);
  const visualRef = React.useRef<HTMLDivElement>(null);
  const sourceRef = React.useRef<HTMLDivElement>(null);
  const previewRef = React.useRef<HTMLDivElement>(null);
  const visual = React.useRef<DomEditor | null>(null);
  const source = React.useRef<SourceEditor | null>(null);
  const [loadError, setLoadError] = React.useState<Error | null>(null);

  const createHandle = React.useCallback((): MdfnEditorHandle => ({
    focus() { visual.current?.focus(); source.current?.focus(); },
    run(command) { return visual.current?.run(command) ?? false; },
    can(command) { return visual.current?.can(command) ?? false; },
    setLink(href, title) { return visual.current?.setLink(href, title) ?? false; },
    removeLink() { return visual.current?.removeLink() ?? false; },
    insertTable(rows, columns) { return visual.current?.insertTable(rows, columns) ?? false; },
    insertMarkdown(markdown) { return visual.current?.insertMarkdown(markdown) ?? false; },
  }), []);
  React.useImperativeHandle(forwardedRef, createHandle, [createHandle]);

  React.useEffect(() => {
    let cancelled = false;
    const destroyers: Array<() => void> = [];
    const cleanup = (): void => {
      for (const destroy of destroyers.splice(0).reverse()) destroy();
    };
    setLoadError(null);
    const mount = async (): Promise<void> => {
      try {
        if ((mode === "visual" || mode === "split") && visualRef.current) {
          const { createDomEditor } = await import("@mdfn/dom");
          if (cancelled || !visualRef.current) return;
          const mountedVisual = createDomEditor({ target: visualRef.current, controller, readOnly: effectiveReadOnly, attributes: { "aria-label": ariaLabel }, onFiles });
          visual.current = mountedVisual;
          destroyers.push(() => {
            mountedVisual.destroy();
            if (visual.current === mountedVisual) visual.current = null;
          });
        }
        if ((mode === "source" || mode === "split") && sourceRef.current) {
          const { createSourceEditor } = await import("@mdfn/source");
          if (cancelled || !sourceRef.current) return;
          const mountedSource = createSourceEditor({ target: sourceRef.current, controller, readOnly: effectiveReadOnly, ariaLabel: `${ariaLabel} source` });
          source.current = mountedSource;
          destroyers.push(() => {
            mountedSource.destroy();
            if (source.current === mountedSource) source.current = null;
          });
        }
        if ((mode === "preview" || mode === "read-only") && previewRef.current) {
          const { createPreview } = await import("@mdfn/source");
          if (cancelled || !previewRef.current) return;
          previewRef.current.innerHTML = createPreview(controller).html;
        }
        onReady?.(createHandle());
      } catch (error) {
        cleanup();
        if (cancelled) return;
        const resolved = error instanceof Error ? error : new Error(String(error));
        setLoadError(resolved);
        onLoadError?.(resolved);
      }
    };
    void mount();
    return () => { cancelled = true; cleanup(); visual.current = null; source.current = null; };
  }, [ariaLabel, controller, createHandle, effectiveReadOnly, mode, onFiles, onLoadError, onReady]);

  React.useEffect(() => {
    if ((mode !== "preview" && mode !== "read-only") || !previewRef.current) return;
    let cancelled = false;
    void import("@mdfn/source").then(({ createPreview }) => {
      if (!cancelled && previewRef.current) previewRef.current.innerHTML = createPreview(controller).html;
    }).catch((error: unknown) => {
      if (cancelled) return;
      const resolved = error instanceof Error ? error : new Error(String(error));
      setLoadError(resolved);
      onLoadError?.(resolved);
    });
    return () => { cancelled = true; };
  }, [controller, mode, onLoadError, snapshot.version]);

  if (loadError) {
    return <SourceFallback controller={controller} ariaLabel={`${ariaLabel} source fallback`} readOnly={effectiveReadOnly} error={loadError} />;
  }

  return (
    <div {...props} className={className} data-mdfn-react="editor" data-mode={mode}>
      {(mode === "visual" || mode === "split") && <div ref={visualRef} data-mdfn-surface="visual" />}
      {(mode === "source" || mode === "split") && <div ref={sourceRef} data-mdfn-surface="source" />}
      {(mode === "preview" || mode === "read-only") && <div ref={previewRef} data-mdfn-surface="preview" aria-label={ariaLabel} />}
    </div>
  );
});

function SourceFallback({ controller, ariaLabel, readOnly, error }: { controller: EditorController; ariaLabel: string; readOnly: boolean; error: Error }) {
  const snapshot = useMdfn(controller);
  return (
    <div data-mdfn-source-fallback="true">
      <div role="status">Visual editor unavailable: {error.message}</div>
      <textarea
        aria-label={ariaLabel}
        value={snapshot.markdown}
        readOnly={readOnly}
        onChange={(event) => {
          const current = controller.getState().markdown;
          const change = smallestSourceChange(current, event.currentTarget.value);
          if (change) controller.dispatch(new Transaction().replaceSource(change.from, change.to, change.insert).withSource("react:fallback"));
        }}
      />
    </div>
  );
}

export const MDFN_REACT_VERSION = "0.1.0" as const;
