// uifn/solid/src/generated/color-picker.tsx
import { createContext, type JSX } from 'solid-js';
import { createColorPickerController, type ColorPickerProps, type ColorPickerController } from '@uifn/core/primitives/color-picker';
import {
  createSolidPrimitiveInstanceId,
  SolidPrimitivePart,
  SolidPrimitiveRoot,
  type SolidPrimitiveContextValue,
  type SolidPrimitiveDefinition,
  type SolidPrimitivePartProps,
  type SolidPrimitiveRootProps,
} from '../internal/compound.jsx';

const ColorPickerContext = createContext<SolidPrimitiveContextValue<ColorPickerProps>>();
export const ColorPickerDefinition: SolidPrimitiveDefinition<ColorPickerProps> = {
  name: 'ColorPicker',
  family: 'date-color',
  kind: 'interactive-controller',
  rootPart: 'root',
  inputNames: ["value","defaultValue","open","defaultOpen","colorSpace","alpha","name","disabled","readOnly"],
  context: ColorPickerContext,
  createController: createColorPickerController as never,
};

function ColorPickerRootElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type ColorPickerRootProps = SolidPrimitiveRootProps<ColorPickerProps, 'div'>;
export function ColorPickerRoot(props: ColorPickerRootProps): JSX.Element {
  const hydrationId = createSolidPrimitiveInstanceId();
  return <SolidPrimitiveRoot definition={ColorPickerDefinition} element="div" renderElement={ColorPickerRootElement as never} hydrationId={hydrationId} props={props as never} />;
}

function ColorPickerLabelElement(props: JSX.IntrinsicElements['label']): JSX.Element {
  return <label {...props} />;
}

export type ColorPickerLabelProps = SolidPrimitivePartProps<ColorPickerController['parts']['label'], 'label', false>;
export function ColorPickerLabel(props: ColorPickerLabelProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={ColorPickerDefinition as never}
      part="label"
      element="label"
      renderElement={ColorPickerLabelElement as never}
      many={false}
      props={props as never}
    />
  );
}

function ColorPickerControlElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type ColorPickerControlProps = SolidPrimitivePartProps<ColorPickerController['parts']['control'], 'div', false>;
export function ColorPickerControl(props: ColorPickerControlProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={ColorPickerDefinition as never}
      part="control"
      element="div"
      renderElement={ColorPickerControlElement as never}
      many={false}
      props={props as never}
    />
  );
}

function ColorPickerTriggerElement(props: JSX.IntrinsicElements['button']): JSX.Element {
  return <button {...props} />;
}

export type ColorPickerTriggerProps = SolidPrimitivePartProps<ColorPickerController['parts']['trigger'], 'button', false>;
export function ColorPickerTrigger(props: ColorPickerTriggerProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={ColorPickerDefinition as never}
      part="trigger"
      element="button"
      renderElement={ColorPickerTriggerElement as never}
      many={false}
      props={props as never}
    />
  );
}

function ColorPickerPositionerElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type ColorPickerPositionerProps = SolidPrimitivePartProps<ColorPickerController['parts']['positioner'], 'div', false>;
export function ColorPickerPositioner(props: ColorPickerPositionerProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={ColorPickerDefinition as never}
      part="positioner"
      element="div"
      renderElement={ColorPickerPositionerElement as never}
      many={false}
      props={props as never}
    />
  );
}

function ColorPickerContentElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type ColorPickerContentProps = SolidPrimitivePartProps<ColorPickerController['parts']['content'], 'div', false>;
export function ColorPickerContent(props: ColorPickerContentProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={ColorPickerDefinition as never}
      part="content"
      element="div"
      renderElement={ColorPickerContentElement as never}
      many={false}
      props={props as never}
    />
  );
}

function ColorPickerAreaElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type ColorPickerAreaProps = SolidPrimitivePartProps<ColorPickerController['parts']['area'], 'div', false>;
export function ColorPickerArea(props: ColorPickerAreaProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={ColorPickerDefinition as never}
      part="area"
      element="div"
      renderElement={ColorPickerAreaElement as never}
      many={false}
      props={props as never}
    />
  );
}

function ColorPickerAreaThumbElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type ColorPickerAreaThumbProps = SolidPrimitivePartProps<ColorPickerController['parts']['areaThumb'], 'div', false>;
export function ColorPickerAreaThumb(props: ColorPickerAreaThumbProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={ColorPickerDefinition as never}
      part="areaThumb"
      element="div"
      renderElement={ColorPickerAreaThumbElement as never}
      many={false}
      props={props as never}
    />
  );
}

function ColorPickerChannelSliderElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type ColorPickerChannelSliderProps = SolidPrimitivePartProps<ColorPickerController['parts']['channelSlider'], 'div', true>;
export function ColorPickerChannelSlider(props: ColorPickerChannelSliderProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={ColorPickerDefinition as never}
      part="channelSlider"
      element="div"
      renderElement={ColorPickerChannelSliderElement as never}
      many={true}
      props={props as never}
    />
  );
}

function ColorPickerChannelInputElement(props: JSX.IntrinsicElements['input']): JSX.Element {
  return <input {...props} />;
}

export type ColorPickerChannelInputProps = SolidPrimitivePartProps<ColorPickerController['parts']['channelInput'], 'input', true>;
export function ColorPickerChannelInput(props: ColorPickerChannelInputProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={ColorPickerDefinition as never}
      part="channelInput"
      element="input"
      renderElement={ColorPickerChannelInputElement as never}
      many={true}
      props={props as never}
    />
  );
}

function ColorPickerSwatchElement(props: JSX.IntrinsicElements['span']): JSX.Element {
  return <span {...props} />;
}

export type ColorPickerSwatchProps = SolidPrimitivePartProps<ColorPickerController['parts']['swatch'], 'span', false>;
export function ColorPickerSwatch(props: ColorPickerSwatchProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={ColorPickerDefinition as never}
      part="swatch"
      element="span"
      renderElement={ColorPickerSwatchElement as never}
      many={false}
      props={props as never}
    />
  );
}

function ColorPickerHiddenInputElement(props: JSX.IntrinsicElements['input']): JSX.Element {
  return <input {...props} />;
}

export type ColorPickerHiddenInputProps = SolidPrimitivePartProps<ColorPickerController['parts']['hiddenInput'], 'input', false>;
export function ColorPickerHiddenInput(props: ColorPickerHiddenInputProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={ColorPickerDefinition as never}
      part="hiddenInput"
      element="input"
      renderElement={ColorPickerHiddenInputElement as never}
      many={false}
      props={props as never}
    />
  );
}

export const ColorPickerProvider = ColorPickerRoot;
export const ColorPicker = /* @__PURE__ */ Object.assign(ColorPickerRoot, { Provider: ColorPickerProvider, Root: ColorPickerRoot, Label: ColorPickerLabel, Control: ColorPickerControl, Trigger: ColorPickerTrigger, Positioner: ColorPickerPositioner, Content: ColorPickerContent, Area: ColorPickerArea, AreaThumb: ColorPickerAreaThumb, ChannelSlider: ColorPickerChannelSlider, ChannelInput: ColorPickerChannelInput, Swatch: ColorPickerSwatch, HiddenInput: ColorPickerHiddenInput });

// uifn/react/src/generated/color-picker.tsx
'use client';

import * as React from 'react';
import { createColorPickerController, type ColorPickerProps, type ColorPickerController } from '@uifn/core/primitives/color-picker';
import {
  ReactPrimitivePart,
  ReactPrimitiveRoot,
  useReactPrimitive,
  type ReactPrimitiveBridge,
  type ReactPrimitiveDefinition,
  type ReactPrimitiveHookResult,
  type ReactPrimitivePartProps,
  type ReactPrimitiveRootProps,
} from '../internal/compound';

const ColorPickerContext = React.createContext<ReactPrimitiveBridge<ColorPickerProps> | null>(null);
const ColorPickerDefinition: ReactPrimitiveDefinition<ColorPickerProps> = {
  name: 'ColorPicker',
  family: 'date-color',
  kind: 'interactive-controller',
  rootPart: 'root',
  inputNames: ["value","defaultValue","open","defaultOpen","colorSpace","alpha","name","disabled","readOnly"],
  context: ColorPickerContext,
  createController: createColorPickerController as never,
};

export type ColorPickerRootProps = ReactPrimitiveRootProps<ColorPickerProps, 'div'>;
export const ColorPickerRoot = React.forwardRef<React.ElementRef<'div'>, ColorPickerRootProps>((props, ref) => (
  <ReactPrimitiveRoot definition={ColorPickerDefinition} element="div" forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
ColorPickerRoot.displayName = 'ColorPickerRoot';

export type ColorPickerLabelProps = ReactPrimitivePartProps<ColorPickerController['parts']['label'], 'label', false>;
export const ColorPickerLabel = React.forwardRef<React.ElementRef<'label'>, ColorPickerLabelProps>((props, ref) => (
  <ReactPrimitivePart definition={ColorPickerDefinition as never} part="label" element="label" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
ColorPickerLabel.displayName = 'ColorPickerLabel';

export type ColorPickerControlProps = ReactPrimitivePartProps<ColorPickerController['parts']['control'], 'div', false>;
export const ColorPickerControl = React.forwardRef<React.ElementRef<'div'>, ColorPickerControlProps>((props, ref) => (
  <ReactPrimitivePart definition={ColorPickerDefinition as never} part="control" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
ColorPickerControl.displayName = 'ColorPickerControl';

export type ColorPickerTriggerProps = ReactPrimitivePartProps<ColorPickerController['parts']['trigger'], 'button', false>;
export const ColorPickerTrigger = React.forwardRef<React.ElementRef<'button'>, ColorPickerTriggerProps>((props, ref) => (
  <ReactPrimitivePart definition={ColorPickerDefinition as never} part="trigger" element="button" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
ColorPickerTrigger.displayName = 'ColorPickerTrigger';

export type ColorPickerPositionerProps = ReactPrimitivePartProps<ColorPickerController['parts']['positioner'], 'div', false>;
export const ColorPickerPositioner = React.forwardRef<React.ElementRef<'div'>, ColorPickerPositionerProps>((props, ref) => (
  <ReactPrimitivePart definition={ColorPickerDefinition as never} part="positioner" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
ColorPickerPositioner.displayName = 'ColorPickerPositioner';

export type ColorPickerContentProps = ReactPrimitivePartProps<ColorPickerController['parts']['content'], 'div', false>;
export const ColorPickerContent = React.forwardRef<React.ElementRef<'div'>, ColorPickerContentProps>((props, ref) => (
  <ReactPrimitivePart definition={ColorPickerDefinition as never} part="content" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
ColorPickerContent.displayName = 'ColorPickerContent';

export type ColorPickerAreaProps = ReactPrimitivePartProps<ColorPickerController['parts']['area'], 'div', false>;
export const ColorPickerArea = React.forwardRef<React.ElementRef<'div'>, ColorPickerAreaProps>((props, ref) => (
  <ReactPrimitivePart definition={ColorPickerDefinition as never} part="area" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
ColorPickerArea.displayName = 'ColorPickerArea';

export type ColorPickerAreaThumbProps = ReactPrimitivePartProps<ColorPickerController['parts']['areaThumb'], 'div', false>;
export const ColorPickerAreaThumb = React.forwardRef<React.ElementRef<'div'>, ColorPickerAreaThumbProps>((props, ref) => (
  <ReactPrimitivePart definition={ColorPickerDefinition as never} part="areaThumb" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
ColorPickerAreaThumb.displayName = 'ColorPickerAreaThumb';

export type ColorPickerChannelSliderProps = ReactPrimitivePartProps<ColorPickerController['parts']['channelSlider'], 'div', true>;
export const ColorPickerChannelSlider = React.forwardRef<React.ElementRef<'div'>, ColorPickerChannelSliderProps>((props, ref) => (
  <ReactPrimitivePart definition={ColorPickerDefinition as never} part="channelSlider" element="div" many={true} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
ColorPickerChannelSlider.displayName = 'ColorPickerChannelSlider';

export type ColorPickerChannelInputProps = ReactPrimitivePartProps<ColorPickerController['parts']['channelInput'], 'input', true>;
export const ColorPickerChannelInput = React.forwardRef<React.ElementRef<'input'>, ColorPickerChannelInputProps>((props, ref) => (
  <ReactPrimitivePart definition={ColorPickerDefinition as never} part="channelInput" element="input" many={true} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
ColorPickerChannelInput.displayName = 'ColorPickerChannelInput';

export type ColorPickerSwatchProps = ReactPrimitivePartProps<ColorPickerController['parts']['swatch'], 'span', false>;
export const ColorPickerSwatch = React.forwardRef<React.ElementRef<'span'>, ColorPickerSwatchProps>((props, ref) => (
  <ReactPrimitivePart definition={ColorPickerDefinition as never} part="swatch" element="span" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
ColorPickerSwatch.displayName = 'ColorPickerSwatch';

export type ColorPickerHiddenInputProps = ReactPrimitivePartProps<ColorPickerController['parts']['hiddenInput'], 'input', false>;
export const ColorPickerHiddenInput = React.forwardRef<React.ElementRef<'input'>, ColorPickerHiddenInputProps>((props, ref) => (
  <ReactPrimitivePart definition={ColorPickerDefinition as never} part="hiddenInput" element="input" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
ColorPickerHiddenInput.displayName = 'ColorPickerHiddenInput';

export const ColorPickerProvider = ColorPickerRoot;
export function useColorPicker(inputs: ColorPickerProps = {} as ColorPickerProps): ReactPrimitiveHookResult<ColorPickerController['state'], ColorPickerController['actions']> {
  return useReactPrimitive(ColorPickerDefinition, inputs) as ReactPrimitiveHookResult<ColorPickerController['state'], ColorPickerController['actions']>;
}
export const ColorPicker = Object.assign(ColorPickerRoot, { Provider: ColorPickerProvider, Root: ColorPickerRoot, Label: ColorPickerLabel, Control: ColorPickerControl, Trigger: ColorPickerTrigger, Positioner: ColorPickerPositioner, Content: ColorPickerContent, Area: ColorPickerArea, AreaThumb: ColorPickerAreaThumb, ChannelSlider: ColorPickerChannelSlider, ChannelInput: ColorPickerChannelInput, Swatch: ColorPickerSwatch, HiddenInput: ColorPickerHiddenInput });
