// uifn/solid/src/generated/date-picker.tsx
import { createContext, type JSX } from 'solid-js';
import { createDatePickerController, type DatePickerProps, type DatePickerController } from '@uifn/core/primitives/date-picker';
import {
  createSolidPrimitiveInstanceId,
  SolidPrimitivePart,
  SolidPrimitiveRoot,
  type SolidPrimitiveContextValue,
  type SolidPrimitiveDefinition,
  type SolidPrimitivePartProps,
  type SolidPrimitiveRootProps,
} from '../internal/compound.jsx';

const DatePickerContext = createContext<SolidPrimitiveContextValue<DatePickerProps>>();
export const DatePickerDefinition: SolidPrimitiveDefinition<DatePickerProps> = {
  name: 'DatePicker',
  family: 'date-color',
  kind: 'interactive-controller',
  rootPart: 'root',
  inputNames: ["value","defaultValue","open","defaultOpen","locale","timeZone","min","max","unavailable","name","disabled","readOnly"],
  context: DatePickerContext,
  createController: createDatePickerController as never,
};

function DatePickerRootElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type DatePickerRootProps = SolidPrimitiveRootProps<DatePickerProps, 'div'>;
export function DatePickerRoot(props: DatePickerRootProps): JSX.Element {
  const hydrationId = createSolidPrimitiveInstanceId();
  return <SolidPrimitiveRoot definition={DatePickerDefinition} element="div" renderElement={DatePickerRootElement as never} hydrationId={hydrationId} props={props as never} />;
}

function DatePickerLabelElement(props: JSX.IntrinsicElements['label']): JSX.Element {
  return <label {...props} />;
}

export type DatePickerLabelProps = SolidPrimitivePartProps<DatePickerController['parts']['label'], 'label', false>;
export function DatePickerLabel(props: DatePickerLabelProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={DatePickerDefinition as never}
      part="label"
      element="label"
      renderElement={DatePickerLabelElement as never}
      many={false}
      props={props as never}
    />
  );
}

function DatePickerInputElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type DatePickerInputProps = SolidPrimitivePartProps<DatePickerController['parts']['input'], 'div', false>;
export function DatePickerInput(props: DatePickerInputProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={DatePickerDefinition as never}
      part="input"
      element="div"
      renderElement={DatePickerInputElement as never}
      many={false}
      props={props as never}
    />
  );
}

function DatePickerSegmentElement(props: JSX.IntrinsicElements['span']): JSX.Element {
  return <span {...props} />;
}

export type DatePickerSegmentProps = SolidPrimitivePartProps<DatePickerController['parts']['segment'], 'span', true>;
export function DatePickerSegment(props: DatePickerSegmentProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={DatePickerDefinition as never}
      part="segment"
      element="span"
      renderElement={DatePickerSegmentElement as never}
      many={true}
      props={props as never}
    />
  );
}

function DatePickerTriggerElement(props: JSX.IntrinsicElements['button']): JSX.Element {
  return <button {...props} />;
}

export type DatePickerTriggerProps = SolidPrimitivePartProps<DatePickerController['parts']['trigger'], 'button', false>;
export function DatePickerTrigger(props: DatePickerTriggerProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={DatePickerDefinition as never}
      part="trigger"
      element="button"
      renderElement={DatePickerTriggerElement as never}
      many={false}
      props={props as never}
    />
  );
}

function DatePickerPositionerElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type DatePickerPositionerProps = SolidPrimitivePartProps<DatePickerController['parts']['positioner'], 'div', false>;
export function DatePickerPositioner(props: DatePickerPositionerProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={DatePickerDefinition as never}
      part="positioner"
      element="div"
      renderElement={DatePickerPositionerElement as never}
      many={false}
      props={props as never}
    />
  );
}

function DatePickerContentElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type DatePickerContentProps = SolidPrimitivePartProps<DatePickerController['parts']['content'], 'div', false>;
export function DatePickerContent(props: DatePickerContentProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={DatePickerDefinition as never}
      part="content"
      element="div"
      renderElement={DatePickerContentElement as never}
      many={false}
      props={props as never}
    />
  );
}

function DatePickerHeaderElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type DatePickerHeaderProps = SolidPrimitivePartProps<DatePickerController['parts']['header'], 'div', false>;
export function DatePickerHeader(props: DatePickerHeaderProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={DatePickerDefinition as never}
      part="header"
      element="div"
      renderElement={DatePickerHeaderElement as never}
      many={false}
      props={props as never}
    />
  );
}

function DatePickerPreviousElement(props: JSX.IntrinsicElements['button']): JSX.Element {
  return <button {...props} />;
}

export type DatePickerPreviousProps = SolidPrimitivePartProps<DatePickerController['parts']['previous'], 'button', false>;
export function DatePickerPrevious(props: DatePickerPreviousProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={DatePickerDefinition as never}
      part="previous"
      element="button"
      renderElement={DatePickerPreviousElement as never}
      many={false}
      props={props as never}
    />
  );
}

function DatePickerNextElement(props: JSX.IntrinsicElements['button']): JSX.Element {
  return <button {...props} />;
}

export type DatePickerNextProps = SolidPrimitivePartProps<DatePickerController['parts']['next'], 'button', false>;
export function DatePickerNext(props: DatePickerNextProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={DatePickerDefinition as never}
      part="next"
      element="button"
      renderElement={DatePickerNextElement as never}
      many={false}
      props={props as never}
    />
  );
}

function DatePickerGridElement(props: JSX.IntrinsicElements['table']): JSX.Element {
  return <table {...props} />;
}

export type DatePickerGridProps = SolidPrimitivePartProps<DatePickerController['parts']['grid'], 'table', false>;
export function DatePickerGrid(props: DatePickerGridProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={DatePickerDefinition as never}
      part="grid"
      element="table"
      renderElement={DatePickerGridElement as never}
      many={false}
      props={props as never}
    />
  );
}

function DatePickerGridLabelElement(props: JSX.IntrinsicElements['caption']): JSX.Element {
  return <caption {...props} />;
}

export type DatePickerGridLabelProps = SolidPrimitivePartProps<DatePickerController['parts']['gridLabel'], 'caption', false>;
export function DatePickerGridLabel(props: DatePickerGridLabelProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={DatePickerDefinition as never}
      part="gridLabel"
      element="caption"
      renderElement={DatePickerGridLabelElement as never}
      many={false}
      props={props as never}
    />
  );
}

function DatePickerCellElement(props: JSX.IntrinsicElements['td']): JSX.Element {
  return <td {...props} />;
}

export type DatePickerCellProps = SolidPrimitivePartProps<DatePickerController['parts']['cell'], 'td', true>;
export function DatePickerCell(props: DatePickerCellProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={DatePickerDefinition as never}
      part="cell"
      element="td"
      renderElement={DatePickerCellElement as never}
      many={true}
      props={props as never}
    />
  );
}

function DatePickerCellTriggerElement(props: JSX.IntrinsicElements['button']): JSX.Element {
  return <button {...props} />;
}

export type DatePickerCellTriggerProps = SolidPrimitivePartProps<DatePickerController['parts']['cellTrigger'], 'button', true>;
export function DatePickerCellTrigger(props: DatePickerCellTriggerProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={DatePickerDefinition as never}
      part="cellTrigger"
      element="button"
      renderElement={DatePickerCellTriggerElement as never}
      many={true}
      props={props as never}
    />
  );
}

function DatePickerHiddenInputElement(props: JSX.IntrinsicElements['input']): JSX.Element {
  return <input {...props} />;
}

export type DatePickerHiddenInputProps = SolidPrimitivePartProps<DatePickerController['parts']['hiddenInput'], 'input', false>;
export function DatePickerHiddenInput(props: DatePickerHiddenInputProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={DatePickerDefinition as never}
      part="hiddenInput"
      element="input"
      renderElement={DatePickerHiddenInputElement as never}
      many={false}
      props={props as never}
    />
  );
}

export const DatePickerProvider = DatePickerRoot;
export const DatePicker = /* @__PURE__ */ Object.assign(DatePickerRoot, { Provider: DatePickerProvider, Root: DatePickerRoot, Label: DatePickerLabel, Input: DatePickerInput, Segment: DatePickerSegment, Trigger: DatePickerTrigger, Positioner: DatePickerPositioner, Content: DatePickerContent, Header: DatePickerHeader, Previous: DatePickerPrevious, Next: DatePickerNext, Grid: DatePickerGrid, GridLabel: DatePickerGridLabel, Cell: DatePickerCell, CellTrigger: DatePickerCellTrigger, HiddenInput: DatePickerHiddenInput });

// uifn/react/src/generated/date-picker.tsx
'use client';

import * as React from 'react';
import { createDatePickerController, type DatePickerProps, type DatePickerController } from '@uifn/core/primitives/date-picker';
import {
  ReactPrimitivePart,
  ReactPrimitiveRoot,
  useReactPrimitive,
  type ReactPrimitiveBridge,
  type ReactPrimitiveDefinition,
  type ReactPrimitiveHookResult,
  type ReactPrimitivePartProps,
  type ReactPrimitiveRootProps,
} from '../internal/compound';

const DatePickerContext = React.createContext<ReactPrimitiveBridge<DatePickerProps> | null>(null);
const DatePickerDefinition: ReactPrimitiveDefinition<DatePickerProps> = {
  name: 'DatePicker',
  family: 'date-color',
  kind: 'interactive-controller',
  rootPart: 'root',
  inputNames: ["value","defaultValue","open","defaultOpen","locale","timeZone","min","max","unavailable","name","disabled","readOnly"],
  context: DatePickerContext,
  createController: createDatePickerController as never,
};

export type DatePickerRootProps = ReactPrimitiveRootProps<DatePickerProps, 'div'>;
export const DatePickerRoot = React.forwardRef<React.ElementRef<'div'>, DatePickerRootProps>((props, ref) => (
  <ReactPrimitiveRoot definition={DatePickerDefinition} element="div" forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
DatePickerRoot.displayName = 'DatePickerRoot';

export type DatePickerLabelProps = ReactPrimitivePartProps<DatePickerController['parts']['label'], 'label', false>;
export const DatePickerLabel = React.forwardRef<React.ElementRef<'label'>, DatePickerLabelProps>((props, ref) => (
  <ReactPrimitivePart definition={DatePickerDefinition as never} part="label" element="label" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
DatePickerLabel.displayName = 'DatePickerLabel';

export type DatePickerInputProps = ReactPrimitivePartProps<DatePickerController['parts']['input'], 'div', false>;
export const DatePickerInput = React.forwardRef<React.ElementRef<'div'>, DatePickerInputProps>((props, ref) => (
  <ReactPrimitivePart definition={DatePickerDefinition as never} part="input" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
DatePickerInput.displayName = 'DatePickerInput';

export type DatePickerSegmentProps = ReactPrimitivePartProps<DatePickerController['parts']['segment'], 'span', true>;
export const DatePickerSegment = React.forwardRef<React.ElementRef<'span'>, DatePickerSegmentProps>((props, ref) => (
  <ReactPrimitivePart definition={DatePickerDefinition as never} part="segment" element="span" many={true} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
DatePickerSegment.displayName = 'DatePickerSegment';

export type DatePickerTriggerProps = ReactPrimitivePartProps<DatePickerController['parts']['trigger'], 'button', false>;
export const DatePickerTrigger = React.forwardRef<React.ElementRef<'button'>, DatePickerTriggerProps>((props, ref) => (
  <ReactPrimitivePart definition={DatePickerDefinition as never} part="trigger" element="button" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
DatePickerTrigger.displayName = 'DatePickerTrigger';

export type DatePickerPositionerProps = ReactPrimitivePartProps<DatePickerController['parts']['positioner'], 'div', false>;
export const DatePickerPositioner = React.forwardRef<React.ElementRef<'div'>, DatePickerPositionerProps>((props, ref) => (
  <ReactPrimitivePart definition={DatePickerDefinition as never} part="positioner" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
DatePickerPositioner.displayName = 'DatePickerPositioner';

export type DatePickerContentProps = ReactPrimitivePartProps<DatePickerController['parts']['content'], 'div', false>;
export const DatePickerContent = React.forwardRef<React.ElementRef<'div'>, DatePickerContentProps>((props, ref) => (
  <ReactPrimitivePart definition={DatePickerDefinition as never} part="content" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
DatePickerContent.displayName = 'DatePickerContent';

export type DatePickerHeaderProps = ReactPrimitivePartProps<DatePickerController['parts']['header'], 'div', false>;
export const DatePickerHeader = React.forwardRef<React.ElementRef<'div'>, DatePickerHeaderProps>((props, ref) => (
  <ReactPrimitivePart definition={DatePickerDefinition as never} part="header" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
DatePickerHeader.displayName = 'DatePickerHeader';

export type DatePickerPreviousProps = ReactPrimitivePartProps<DatePickerController['parts']['previous'], 'button', false>;
export const DatePickerPrevious = React.forwardRef<React.ElementRef<'button'>, DatePickerPreviousProps>((props, ref) => (
  <ReactPrimitivePart definition={DatePickerDefinition as never} part="previous" element="button" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
DatePickerPrevious.displayName = 'DatePickerPrevious';

export type DatePickerNextProps = ReactPrimitivePartProps<DatePickerController['parts']['next'], 'button', false>;
export const DatePickerNext = React.forwardRef<React.ElementRef<'button'>, DatePickerNextProps>((props, ref) => (
  <ReactPrimitivePart definition={DatePickerDefinition as never} part="next" element="button" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
DatePickerNext.displayName = 'DatePickerNext';

export type DatePickerGridProps = ReactPrimitivePartProps<DatePickerController['parts']['grid'], 'table', false>;
export const DatePickerGrid = React.forwardRef<React.ElementRef<'table'>, DatePickerGridProps>((props, ref) => (
  <ReactPrimitivePart definition={DatePickerDefinition as never} part="grid" element="table" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
DatePickerGrid.displayName = 'DatePickerGrid';

export type DatePickerGridLabelProps = ReactPrimitivePartProps<DatePickerController['parts']['gridLabel'], 'caption', false>;
export const DatePickerGridLabel = React.forwardRef<React.ElementRef<'caption'>, DatePickerGridLabelProps>((props, ref) => (
  <ReactPrimitivePart definition={DatePickerDefinition as never} part="gridLabel" element="caption" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
DatePickerGridLabel.displayName = 'DatePickerGridLabel';

export type DatePickerCellProps = ReactPrimitivePartProps<DatePickerController['parts']['cell'], 'td', true>;
export const DatePickerCell = React.forwardRef<React.ElementRef<'td'>, DatePickerCellProps>((props, ref) => (
  <ReactPrimitivePart definition={DatePickerDefinition as never} part="cell" element="td" many={true} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
DatePickerCell.displayName = 'DatePickerCell';

export type DatePickerCellTriggerProps = ReactPrimitivePartProps<DatePickerController['parts']['cellTrigger'], 'button', true>;
export const DatePickerCellTrigger = React.forwardRef<React.ElementRef<'button'>, DatePickerCellTriggerProps>((props, ref) => (
  <ReactPrimitivePart definition={DatePickerDefinition as never} part="cellTrigger" element="button" many={true} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
DatePickerCellTrigger.displayName = 'DatePickerCellTrigger';

export type DatePickerHiddenInputProps = ReactPrimitivePartProps<DatePickerController['parts']['hiddenInput'], 'input', false>;
export const DatePickerHiddenInput = React.forwardRef<React.ElementRef<'input'>, DatePickerHiddenInputProps>((props, ref) => (
  <ReactPrimitivePart definition={DatePickerDefinition as never} part="hiddenInput" element="input" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
DatePickerHiddenInput.displayName = 'DatePickerHiddenInput';

export const DatePickerProvider = DatePickerRoot;
export function useDatePicker(inputs: DatePickerProps = {} as DatePickerProps): ReactPrimitiveHookResult<DatePickerController['state'], DatePickerController['actions']> {
  return useReactPrimitive(DatePickerDefinition, inputs) as ReactPrimitiveHookResult<DatePickerController['state'], DatePickerController['actions']>;
}
export const DatePicker = Object.assign(DatePickerRoot, { Provider: DatePickerProvider, Root: DatePickerRoot, Label: DatePickerLabel, Input: DatePickerInput, Segment: DatePickerSegment, Trigger: DatePickerTrigger, Positioner: DatePickerPositioner, Content: DatePickerContent, Header: DatePickerHeader, Previous: DatePickerPrevious, Next: DatePickerNext, Grid: DatePickerGrid, GridLabel: DatePickerGridLabel, Cell: DatePickerCell, CellTrigger: DatePickerCellTrigger, HiddenInput: DatePickerHiddenInput });
