// uifn/solid/src/generated/dialog.tsx
import { createContext, type JSX } from 'solid-js';
import { createDialogController, type DialogProps, type DialogController } from '@uifn/core/primitives/dialog';
import {
  createSolidPrimitiveInstanceId,
  SolidPrimitivePart,
  SolidPrimitiveRoot,
  type SolidPrimitiveContextValue,
  type SolidPrimitiveDefinition,
  type SolidPrimitivePartProps,
  type SolidPrimitiveRootProps,
} from '../internal/compound.jsx';

const DialogContext = createContext<SolidPrimitiveContextValue<DialogProps>>();
export const DialogDefinition: SolidPrimitiveDefinition<DialogProps> = {
  name: 'Dialog',
  family: 'modal-overlay',
  kind: 'interactive-controller',
  rootPart: 'root',
  inputNames: ["open","defaultOpen","modal","initialFocus","restoreFocus"],
  context: DialogContext,
  createController: createDialogController as never,
};

function DialogRootElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type DialogRootProps = SolidPrimitiveRootProps<DialogProps, 'div'>;
export function DialogRoot(props: DialogRootProps): JSX.Element {
  const hydrationId = createSolidPrimitiveInstanceId();
  return <SolidPrimitiveRoot definition={DialogDefinition} element="div" renderElement={DialogRootElement as never} hydrationId={hydrationId} props={props as never} />;
}

function DialogTriggerElement(props: JSX.IntrinsicElements['button']): JSX.Element {
  return <button {...props} />;
}

export type DialogTriggerProps = SolidPrimitivePartProps<DialogController['parts']['trigger'], 'button', false>;
export function DialogTrigger(props: DialogTriggerProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={DialogDefinition as never}
      part="trigger"
      element="button"
      renderElement={DialogTriggerElement as never}
      many={false}
      props={props as never}
    />
  );
}

function DialogPortalElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type DialogPortalProps = SolidPrimitivePartProps<DialogController['parts']['portal'], 'div', false>;
export function DialogPortal(props: DialogPortalProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={DialogDefinition as never}
      part="portal"
      element="div"
      renderElement={DialogPortalElement as never}
      many={false}
      props={props as never}
    />
  );
}

function DialogBackdropElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type DialogBackdropProps = SolidPrimitivePartProps<DialogController['parts']['backdrop'], 'div', false>;
export function DialogBackdrop(props: DialogBackdropProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={DialogDefinition as never}
      part="backdrop"
      element="div"
      renderElement={DialogBackdropElement as never}
      many={false}
      props={props as never}
    />
  );
}

function DialogPositionerElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type DialogPositionerProps = SolidPrimitivePartProps<DialogController['parts']['positioner'], 'div', false>;
export function DialogPositioner(props: DialogPositionerProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={DialogDefinition as never}
      part="positioner"
      element="div"
      renderElement={DialogPositionerElement as never}
      many={false}
      props={props as never}
    />
  );
}

function DialogContentElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type DialogContentProps = SolidPrimitivePartProps<DialogController['parts']['content'], 'div', false>;
export function DialogContent(props: DialogContentProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={DialogDefinition as never}
      part="content"
      element="div"
      renderElement={DialogContentElement as never}
      many={false}
      props={props as never}
    />
  );
}

function DialogTitleElement(props: JSX.IntrinsicElements['h2']): JSX.Element {
  return <h2 {...props} />;
}

export type DialogTitleProps = SolidPrimitivePartProps<DialogController['parts']['title'], 'h2', false>;
export function DialogTitle(props: DialogTitleProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={DialogDefinition as never}
      part="title"
      element="h2"
      renderElement={DialogTitleElement as never}
      many={false}
      props={props as never}
    />
  );
}

function DialogDescriptionElement(props: JSX.IntrinsicElements['p']): JSX.Element {
  return <p {...props} />;
}

export type DialogDescriptionProps = SolidPrimitivePartProps<DialogController['parts']['description'], 'p', false>;
export function DialogDescription(props: DialogDescriptionProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={DialogDefinition as never}
      part="description"
      element="p"
      renderElement={DialogDescriptionElement as never}
      many={false}
      props={props as never}
    />
  );
}

function DialogCloseElement(props: JSX.IntrinsicElements['button']): JSX.Element {
  return <button {...props} />;
}

export type DialogCloseProps = SolidPrimitivePartProps<DialogController['parts']['close'], 'button', false>;
export function DialogClose(props: DialogCloseProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={DialogDefinition as never}
      part="close"
      element="button"
      renderElement={DialogCloseElement as never}
      many={false}
      props={props as never}
    />
  );
}

export const DialogProvider = DialogRoot;
export const Dialog = /* @__PURE__ */ Object.assign(DialogRoot, { Provider: DialogProvider, Root: DialogRoot, Trigger: DialogTrigger, Portal: DialogPortal, Backdrop: DialogBackdrop, Positioner: DialogPositioner, Content: DialogContent, Title: DialogTitle, Description: DialogDescription, Close: DialogClose });

// uifn/react/src/generated/dialog.tsx
'use client';

import * as React from 'react';
import { createDialogController, type DialogProps, type DialogController } from '@uifn/core/primitives/dialog';
import {
  ReactPrimitivePart,
  ReactPrimitiveRoot,
  useReactPrimitive,
  type ReactPrimitiveBridge,
  type ReactPrimitiveDefinition,
  type ReactPrimitiveHookResult,
  type ReactPrimitivePartProps,
  type ReactPrimitiveRootProps,
} from '../internal/compound';

const DialogContext = React.createContext<ReactPrimitiveBridge<DialogProps> | null>(null);
const DialogDefinition: ReactPrimitiveDefinition<DialogProps> = {
  name: 'Dialog',
  family: 'modal-overlay',
  kind: 'interactive-controller',
  rootPart: 'root',
  inputNames: ["open","defaultOpen","modal","initialFocus","restoreFocus"],
  context: DialogContext,
  createController: createDialogController as never,
};

export type DialogRootProps = ReactPrimitiveRootProps<DialogProps, 'div'>;
export const DialogRoot = React.forwardRef<React.ElementRef<'div'>, DialogRootProps>((props, ref) => (
  <ReactPrimitiveRoot definition={DialogDefinition} element="div" forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
DialogRoot.displayName = 'DialogRoot';

export type DialogTriggerProps = ReactPrimitivePartProps<DialogController['parts']['trigger'], 'button', false>;
export const DialogTrigger = React.forwardRef<React.ElementRef<'button'>, DialogTriggerProps>((props, ref) => (
  <ReactPrimitivePart definition={DialogDefinition as never} part="trigger" element="button" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
DialogTrigger.displayName = 'DialogTrigger';

export type DialogPortalProps = ReactPrimitivePartProps<DialogController['parts']['portal'], 'div', false>;
export const DialogPortal = React.forwardRef<React.ElementRef<'div'>, DialogPortalProps>((props, ref) => (
  <ReactPrimitivePart definition={DialogDefinition as never} part="portal" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
DialogPortal.displayName = 'DialogPortal';

export type DialogBackdropProps = ReactPrimitivePartProps<DialogController['parts']['backdrop'], 'div', false>;
export const DialogBackdrop = React.forwardRef<React.ElementRef<'div'>, DialogBackdropProps>((props, ref) => (
  <ReactPrimitivePart definition={DialogDefinition as never} part="backdrop" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
DialogBackdrop.displayName = 'DialogBackdrop';

export type DialogPositionerProps = ReactPrimitivePartProps<DialogController['parts']['positioner'], 'div', false>;
export const DialogPositioner = React.forwardRef<React.ElementRef<'div'>, DialogPositionerProps>((props, ref) => (
  <ReactPrimitivePart definition={DialogDefinition as never} part="positioner" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
DialogPositioner.displayName = 'DialogPositioner';

export type DialogContentProps = ReactPrimitivePartProps<DialogController['parts']['content'], 'div', false>;
export const DialogContent = React.forwardRef<React.ElementRef<'div'>, DialogContentProps>((props, ref) => (
  <ReactPrimitivePart definition={DialogDefinition as never} part="content" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
DialogContent.displayName = 'DialogContent';

export type DialogTitleProps = ReactPrimitivePartProps<DialogController['parts']['title'], 'h2', false>;
export const DialogTitle = React.forwardRef<React.ElementRef<'h2'>, DialogTitleProps>((props, ref) => (
  <ReactPrimitivePart definition={DialogDefinition as never} part="title" element="h2" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
DialogTitle.displayName = 'DialogTitle';

export type DialogDescriptionProps = ReactPrimitivePartProps<DialogController['parts']['description'], 'p', false>;
export const DialogDescription = React.forwardRef<React.ElementRef<'p'>, DialogDescriptionProps>((props, ref) => (
  <ReactPrimitivePart definition={DialogDefinition as never} part="description" element="p" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
DialogDescription.displayName = 'DialogDescription';

export type DialogCloseProps = ReactPrimitivePartProps<DialogController['parts']['close'], 'button', false>;
export const DialogClose = React.forwardRef<React.ElementRef<'button'>, DialogCloseProps>((props, ref) => (
  <ReactPrimitivePart definition={DialogDefinition as never} part="close" element="button" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
DialogClose.displayName = 'DialogClose';

export const DialogProvider = DialogRoot;
export function useDialog(inputs: DialogProps = {} as DialogProps): ReactPrimitiveHookResult<DialogController['state'], DialogController['actions']> {
  return useReactPrimitive(DialogDefinition, inputs) as ReactPrimitiveHookResult<DialogController['state'], DialogController['actions']>;
}
export const Dialog = Object.assign(DialogRoot, { Provider: DialogProvider, Root: DialogRoot, Trigger: DialogTrigger, Portal: DialogPortal, Backdrop: DialogBackdrop, Positioner: DialogPositioner, Content: DialogContent, Title: DialogTitle, Description: DialogDescription, Close: DialogClose });
