// uifn/solid/src/generated/pagination.tsx
import { createContext, type JSX } from 'solid-js';
import { createPaginationController, type PaginationProps, type PaginationController } from '@uifn/core/primitives/pagination';
import {
  createSolidPrimitiveInstanceId,
  SolidPrimitivePart,
  SolidPrimitiveRoot,
  type SolidPrimitiveContextValue,
  type SolidPrimitiveDefinition,
  type SolidPrimitivePartProps,
  type SolidPrimitiveRootProps,
} from '../internal/compound.jsx';

const PaginationContext = createContext<SolidPrimitiveContextValue<PaginationProps>>();
export const PaginationDefinition: SolidPrimitiveDefinition<PaginationProps> = {
  name: 'Pagination',
  family: 'menu-navigation',
  kind: 'interactive-controller',
  rootPart: 'root',
  inputNames: ["page","defaultPage","count","pageSize","siblingCount","disabled"],
  context: PaginationContext,
  createController: createPaginationController as never,
};

function PaginationRootElement(props: JSX.IntrinsicElements['nav']): JSX.Element {
  return <nav {...props} />;
}

export type PaginationRootProps = SolidPrimitiveRootProps<PaginationProps, 'nav'>;
export function PaginationRoot(props: PaginationRootProps): JSX.Element {
  const hydrationId = createSolidPrimitiveInstanceId();
  return <SolidPrimitiveRoot definition={PaginationDefinition} element="nav" renderElement={PaginationRootElement as never} hydrationId={hydrationId} props={props as never} />;
}

function PaginationListElement(props: JSX.IntrinsicElements['ul']): JSX.Element {
  return <ul {...props} />;
}

export type PaginationListProps = SolidPrimitivePartProps<PaginationController['parts']['list'], 'ul', false>;
export function PaginationList(props: PaginationListProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={PaginationDefinition as never}
      part="list"
      element="ul"
      renderElement={PaginationListElement as never}
      many={false}
      props={props as never}
    />
  );
}

function PaginationItemElement(props: JSX.IntrinsicElements['li']): JSX.Element {
  return <li {...props} />;
}

export type PaginationItemProps = SolidPrimitivePartProps<PaginationController['parts']['item'], 'li', true>;
export function PaginationItem(props: PaginationItemProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={PaginationDefinition as never}
      part="item"
      element="li"
      renderElement={PaginationItemElement as never}
      many={true}
      props={props as never}
    />
  );
}

function PaginationPageTriggerElement(props: JSX.IntrinsicElements['button']): JSX.Element {
  return <button {...props} />;
}

export type PaginationPageTriggerProps = SolidPrimitivePartProps<PaginationController['parts']['pageTrigger'], 'button', true>;
export function PaginationPageTrigger(props: PaginationPageTriggerProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={PaginationDefinition as never}
      part="pageTrigger"
      element="button"
      renderElement={PaginationPageTriggerElement as never}
      many={true}
      props={props as never}
    />
  );
}

function PaginationPreviousElement(props: JSX.IntrinsicElements['button']): JSX.Element {
  return <button {...props} />;
}

export type PaginationPreviousProps = SolidPrimitivePartProps<PaginationController['parts']['previous'], 'button', false>;
export function PaginationPrevious(props: PaginationPreviousProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={PaginationDefinition as never}
      part="previous"
      element="button"
      renderElement={PaginationPreviousElement as never}
      many={false}
      props={props as never}
    />
  );
}

function PaginationNextElement(props: JSX.IntrinsicElements['button']): JSX.Element {
  return <button {...props} />;
}

export type PaginationNextProps = SolidPrimitivePartProps<PaginationController['parts']['next'], 'button', false>;
export function PaginationNext(props: PaginationNextProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={PaginationDefinition as never}
      part="next"
      element="button"
      renderElement={PaginationNextElement as never}
      many={false}
      props={props as never}
    />
  );
}

function PaginationEllipsisElement(props: JSX.IntrinsicElements['span']): JSX.Element {
  return <span {...props} />;
}

export type PaginationEllipsisProps = SolidPrimitivePartProps<PaginationController['parts']['ellipsis'], 'span', true>;
export function PaginationEllipsis(props: PaginationEllipsisProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={PaginationDefinition as never}
      part="ellipsis"
      element="span"
      renderElement={PaginationEllipsisElement as never}
      many={true}
      props={props as never}
    />
  );
}

export const PaginationProvider = PaginationRoot;
export const Pagination = /* @__PURE__ */ Object.assign(PaginationRoot, { Provider: PaginationProvider, Root: PaginationRoot, List: PaginationList, Item: PaginationItem, PageTrigger: PaginationPageTrigger, Previous: PaginationPrevious, Next: PaginationNext, Ellipsis: PaginationEllipsis });

// uifn/react/src/generated/pagination.tsx
'use client';

import * as React from 'react';
import { createPaginationController, type PaginationProps, type PaginationController } from '@uifn/core/primitives/pagination';
import {
  ReactPrimitivePart,
  ReactPrimitiveRoot,
  useReactPrimitive,
  type ReactPrimitiveBridge,
  type ReactPrimitiveDefinition,
  type ReactPrimitiveHookResult,
  type ReactPrimitivePartProps,
  type ReactPrimitiveRootProps,
} from '../internal/compound';

const PaginationContext = React.createContext<ReactPrimitiveBridge<PaginationProps> | null>(null);
const PaginationDefinition: ReactPrimitiveDefinition<PaginationProps> = {
  name: 'Pagination',
  family: 'menu-navigation',
  kind: 'interactive-controller',
  rootPart: 'root',
  inputNames: ["page","defaultPage","count","pageSize","siblingCount","disabled"],
  context: PaginationContext,
  createController: createPaginationController as never,
};

export type PaginationRootProps = ReactPrimitiveRootProps<PaginationProps, 'nav'>;
export const PaginationRoot = React.forwardRef<React.ElementRef<'nav'>, PaginationRootProps>((props, ref) => (
  <ReactPrimitiveRoot definition={PaginationDefinition} element="nav" forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
PaginationRoot.displayName = 'PaginationRoot';

export type PaginationListProps = ReactPrimitivePartProps<PaginationController['parts']['list'], 'ul', false>;
export const PaginationList = React.forwardRef<React.ElementRef<'ul'>, PaginationListProps>((props, ref) => (
  <ReactPrimitivePart definition={PaginationDefinition as never} part="list" element="ul" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
PaginationList.displayName = 'PaginationList';

export type PaginationItemProps = ReactPrimitivePartProps<PaginationController['parts']['item'], 'li', true>;
export const PaginationItem = React.forwardRef<React.ElementRef<'li'>, PaginationItemProps>((props, ref) => (
  <ReactPrimitivePart definition={PaginationDefinition as never} part="item" element="li" many={true} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
PaginationItem.displayName = 'PaginationItem';

export type PaginationPageTriggerProps = ReactPrimitivePartProps<PaginationController['parts']['pageTrigger'], 'button', true>;
export const PaginationPageTrigger = React.forwardRef<React.ElementRef<'button'>, PaginationPageTriggerProps>((props, ref) => (
  <ReactPrimitivePart definition={PaginationDefinition as never} part="pageTrigger" element="button" many={true} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
PaginationPageTrigger.displayName = 'PaginationPageTrigger';

export type PaginationPreviousProps = ReactPrimitivePartProps<PaginationController['parts']['previous'], 'button', false>;
export const PaginationPrevious = React.forwardRef<React.ElementRef<'button'>, PaginationPreviousProps>((props, ref) => (
  <ReactPrimitivePart definition={PaginationDefinition as never} part="previous" element="button" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
PaginationPrevious.displayName = 'PaginationPrevious';

export type PaginationNextProps = ReactPrimitivePartProps<PaginationController['parts']['next'], 'button', false>;
export const PaginationNext = React.forwardRef<React.ElementRef<'button'>, PaginationNextProps>((props, ref) => (
  <ReactPrimitivePart definition={PaginationDefinition as never} part="next" element="button" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
PaginationNext.displayName = 'PaginationNext';

export type PaginationEllipsisProps = ReactPrimitivePartProps<PaginationController['parts']['ellipsis'], 'span', true>;
export const PaginationEllipsis = React.forwardRef<React.ElementRef<'span'>, PaginationEllipsisProps>((props, ref) => (
  <ReactPrimitivePart definition={PaginationDefinition as never} part="ellipsis" element="span" many={true} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
PaginationEllipsis.displayName = 'PaginationEllipsis';

export const PaginationProvider = PaginationRoot;
export function usePagination(inputs: PaginationProps): ReactPrimitiveHookResult<PaginationController['state'], PaginationController['actions']> {
  return useReactPrimitive(PaginationDefinition, inputs) as ReactPrimitiveHookResult<PaginationController['state'], PaginationController['actions']>;
}
export const Pagination = Object.assign(PaginationRoot, { Provider: PaginationProvider, Root: PaginationRoot, List: PaginationList, Item: PaginationItem, PageTrigger: PaginationPageTrigger, Previous: PaginationPrevious, Next: PaginationNext, Ellipsis: PaginationEllipsis });
