// uifn/solid/src/generated/pin-input.tsx
import { createContext, type JSX } from 'solid-js';
import { createPinInputController, type PinInputProps, type PinInputController } from '@uifn/core/primitives/pin-input';
import {
  createSolidPrimitiveInstanceId,
  SolidPrimitivePart,
  SolidPrimitiveRoot,
  type SolidPrimitiveContextValue,
  type SolidPrimitiveDefinition,
  type SolidPrimitivePartProps,
  type SolidPrimitiveRootProps,
} from '../internal/compound.jsx';

const PinInputContext = createContext<SolidPrimitiveContextValue<PinInputProps>>();
export const PinInputDefinition: SolidPrimitiveDefinition<PinInputProps> = {
  name: 'PinInput',
  family: 'forms-input',
  kind: 'interactive-controller',
  rootPart: 'root',
  inputNames: ["value","defaultValue","length","mask","otp","name","disabled","readOnly","required"],
  context: PinInputContext,
  createController: createPinInputController as never,
};

function PinInputRootElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type PinInputRootProps = SolidPrimitiveRootProps<PinInputProps, 'div'>;
export function PinInputRoot(props: PinInputRootProps): JSX.Element {
  const hydrationId = createSolidPrimitiveInstanceId();
  return <SolidPrimitiveRoot definition={PinInputDefinition} element="div" renderElement={PinInputRootElement as never} hydrationId={hydrationId} props={props as never} />;
}

function PinInputLabelElement(props: JSX.IntrinsicElements['label']): JSX.Element {
  return <label {...props} />;
}

export type PinInputLabelProps = SolidPrimitivePartProps<PinInputController['parts']['label'], 'label', false>;
export function PinInputLabel(props: PinInputLabelProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={PinInputDefinition as never}
      part="label"
      element="label"
      renderElement={PinInputLabelElement as never}
      many={false}
      props={props as never}
    />
  );
}

function PinInputControlElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type PinInputControlProps = SolidPrimitivePartProps<PinInputController['parts']['control'], 'div', false>;
export function PinInputControl(props: PinInputControlProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={PinInputDefinition as never}
      part="control"
      element="div"
      renderElement={PinInputControlElement as never}
      many={false}
      props={props as never}
    />
  );
}

function PinInputInputElement(props: JSX.IntrinsicElements['input']): JSX.Element {
  return <input {...props} />;
}

export type PinInputInputProps = SolidPrimitivePartProps<PinInputController['parts']['input'], 'input', true>;
export function PinInputInput(props: PinInputInputProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={PinInputDefinition as never}
      part="input"
      element="input"
      renderElement={PinInputInputElement as never}
      many={true}
      props={props as never}
    />
  );
}

function PinInputHiddenInputElement(props: JSX.IntrinsicElements['input']): JSX.Element {
  return <input {...props} />;
}

export type PinInputHiddenInputProps = SolidPrimitivePartProps<PinInputController['parts']['hiddenInput'], 'input', false>;
export function PinInputHiddenInput(props: PinInputHiddenInputProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={PinInputDefinition as never}
      part="hiddenInput"
      element="input"
      renderElement={PinInputHiddenInputElement as never}
      many={false}
      props={props as never}
    />
  );
}

function PinInputErrorElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type PinInputErrorProps = SolidPrimitivePartProps<PinInputController['parts']['error'], 'div', false>;
export function PinInputError(props: PinInputErrorProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={PinInputDefinition as never}
      part="error"
      element="div"
      renderElement={PinInputErrorElement as never}
      many={false}
      props={props as never}
    />
  );
}

export const PinInputProvider = PinInputRoot;
export const PinInput = /* @__PURE__ */ Object.assign(PinInputRoot, { Provider: PinInputProvider, Root: PinInputRoot, Label: PinInputLabel, Control: PinInputControl, Input: PinInputInput, HiddenInput: PinInputHiddenInput, Error: PinInputError });

// uifn/react/src/generated/pin-input.tsx
'use client';

import * as React from 'react';
import { createPinInputController, type PinInputProps, type PinInputController } from '@uifn/core/primitives/pin-input';
import {
  ReactPrimitivePart,
  ReactPrimitiveRoot,
  useReactPrimitive,
  type ReactPrimitiveBridge,
  type ReactPrimitiveDefinition,
  type ReactPrimitiveHookResult,
  type ReactPrimitivePartProps,
  type ReactPrimitiveRootProps,
} from '../internal/compound';

const PinInputContext = React.createContext<ReactPrimitiveBridge<PinInputProps> | null>(null);
const PinInputDefinition: ReactPrimitiveDefinition<PinInputProps> = {
  name: 'PinInput',
  family: 'forms-input',
  kind: 'interactive-controller',
  rootPart: 'root',
  inputNames: ["value","defaultValue","length","mask","otp","name","disabled","readOnly","required"],
  context: PinInputContext,
  createController: createPinInputController as never,
};

export type PinInputRootProps = ReactPrimitiveRootProps<PinInputProps, 'div'>;
export const PinInputRoot = React.forwardRef<React.ElementRef<'div'>, PinInputRootProps>((props, ref) => (
  <ReactPrimitiveRoot definition={PinInputDefinition} element="div" forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
PinInputRoot.displayName = 'PinInputRoot';

export type PinInputLabelProps = ReactPrimitivePartProps<PinInputController['parts']['label'], 'label', false>;
export const PinInputLabel = React.forwardRef<React.ElementRef<'label'>, PinInputLabelProps>((props, ref) => (
  <ReactPrimitivePart definition={PinInputDefinition as never} part="label" element="label" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
PinInputLabel.displayName = 'PinInputLabel';

export type PinInputControlProps = ReactPrimitivePartProps<PinInputController['parts']['control'], 'div', false>;
export const PinInputControl = React.forwardRef<React.ElementRef<'div'>, PinInputControlProps>((props, ref) => (
  <ReactPrimitivePart definition={PinInputDefinition as never} part="control" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
PinInputControl.displayName = 'PinInputControl';

export type PinInputInputProps = ReactPrimitivePartProps<PinInputController['parts']['input'], 'input', true>;
export const PinInputInput = React.forwardRef<React.ElementRef<'input'>, PinInputInputProps>((props, ref) => (
  <ReactPrimitivePart definition={PinInputDefinition as never} part="input" element="input" many={true} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
PinInputInput.displayName = 'PinInputInput';

export type PinInputHiddenInputProps = ReactPrimitivePartProps<PinInputController['parts']['hiddenInput'], 'input', false>;
export const PinInputHiddenInput = React.forwardRef<React.ElementRef<'input'>, PinInputHiddenInputProps>((props, ref) => (
  <ReactPrimitivePart definition={PinInputDefinition as never} part="hiddenInput" element="input" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
PinInputHiddenInput.displayName = 'PinInputHiddenInput';

export type PinInputErrorProps = ReactPrimitivePartProps<PinInputController['parts']['error'], 'div', false>;
export const PinInputError = React.forwardRef<React.ElementRef<'div'>, PinInputErrorProps>((props, ref) => (
  <ReactPrimitivePart definition={PinInputDefinition as never} part="error" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
PinInputError.displayName = 'PinInputError';

export const PinInputProvider = PinInputRoot;
export function usePinInput(inputs: PinInputProps = {} as PinInputProps): ReactPrimitiveHookResult<PinInputController['state'], PinInputController['actions']> {
  return useReactPrimitive(PinInputDefinition, inputs) as ReactPrimitiveHookResult<PinInputController['state'], PinInputController['actions']>;
}
export const PinInput = Object.assign(PinInputRoot, { Provider: PinInputProvider, Root: PinInputRoot, Label: PinInputLabel, Control: PinInputControl, Input: PinInputInput, HiddenInput: PinInputHiddenInput, Error: PinInputError });
