// uifn/solid/src/generated/rating-group.tsx
import { createContext, type JSX } from 'solid-js';
import { createRatingGroupController, type RatingGroupProps, type RatingGroupController } from '@uifn/core/primitives/rating-group';
import {
  createSolidPrimitiveInstanceId,
  SolidPrimitivePart,
  SolidPrimitiveRoot,
  type SolidPrimitiveContextValue,
  type SolidPrimitiveDefinition,
  type SolidPrimitivePartProps,
  type SolidPrimitiveRootProps,
} from '../internal/compound.jsx';

const RatingGroupContext = createContext<SolidPrimitiveContextValue<RatingGroupProps>>();
export const RatingGroupDefinition: SolidPrimitiveDefinition<RatingGroupProps> = {
  name: 'RatingGroup',
  family: 'range-gesture',
  kind: 'interactive-controller',
  rootPart: 'root',
  inputNames: ["value","defaultValue","count","allowHalf","name","disabled","readOnly","required"],
  context: RatingGroupContext,
  createController: createRatingGroupController as never,
};

function RatingGroupRootElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type RatingGroupRootProps = SolidPrimitiveRootProps<RatingGroupProps, 'div'>;
export function RatingGroupRoot(props: RatingGroupRootProps): JSX.Element {
  const hydrationId = createSolidPrimitiveInstanceId();
  return <SolidPrimitiveRoot definition={RatingGroupDefinition} element="div" renderElement={RatingGroupRootElement as never} hydrationId={hydrationId} props={props as never} />;
}

function RatingGroupLabelElement(props: JSX.IntrinsicElements['label']): JSX.Element {
  return <label {...props} />;
}

export type RatingGroupLabelProps = SolidPrimitivePartProps<RatingGroupController['parts']['label'], 'label', false>;
export function RatingGroupLabel(props: RatingGroupLabelProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={RatingGroupDefinition as never}
      part="label"
      element="label"
      renderElement={RatingGroupLabelElement as never}
      many={false}
      props={props as never}
    />
  );
}

function RatingGroupControlElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type RatingGroupControlProps = SolidPrimitivePartProps<RatingGroupController['parts']['control'], 'div', false>;
export function RatingGroupControl(props: RatingGroupControlProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={RatingGroupDefinition as never}
      part="control"
      element="div"
      renderElement={RatingGroupControlElement as never}
      many={false}
      props={props as never}
    />
  );
}

function RatingGroupItemElement(props: JSX.IntrinsicElements['button']): JSX.Element {
  return <button {...props} />;
}

export type RatingGroupItemProps = SolidPrimitivePartProps<RatingGroupController['parts']['item'], 'button', true>;
export function RatingGroupItem(props: RatingGroupItemProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={RatingGroupDefinition as never}
      part="item"
      element="button"
      renderElement={RatingGroupItemElement as never}
      many={true}
      props={props as never}
    />
  );
}

function RatingGroupItemIndicatorElement(props: JSX.IntrinsicElements['span']): JSX.Element {
  return <span {...props} />;
}

export type RatingGroupItemIndicatorProps = SolidPrimitivePartProps<RatingGroupController['parts']['itemIndicator'], 'span', true>;
export function RatingGroupItemIndicator(props: RatingGroupItemIndicatorProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={RatingGroupDefinition as never}
      part="itemIndicator"
      element="span"
      renderElement={RatingGroupItemIndicatorElement as never}
      many={true}
      props={props as never}
    />
  );
}

function RatingGroupHiddenInputElement(props: JSX.IntrinsicElements['input']): JSX.Element {
  return <input {...props} />;
}

export type RatingGroupHiddenInputProps = SolidPrimitivePartProps<RatingGroupController['parts']['hiddenInput'], 'input', false>;
export function RatingGroupHiddenInput(props: RatingGroupHiddenInputProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={RatingGroupDefinition as never}
      part="hiddenInput"
      element="input"
      renderElement={RatingGroupHiddenInputElement as never}
      many={false}
      props={props as never}
    />
  );
}

function RatingGroupValueTextElement(props: JSX.IntrinsicElements['span']): JSX.Element {
  return <span {...props} />;
}

export type RatingGroupValueTextProps = SolidPrimitivePartProps<RatingGroupController['parts']['valueText'], 'span', false>;
export function RatingGroupValueText(props: RatingGroupValueTextProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={RatingGroupDefinition as never}
      part="valueText"
      element="span"
      renderElement={RatingGroupValueTextElement as never}
      many={false}
      props={props as never}
    />
  );
}

export const RatingGroupProvider = RatingGroupRoot;
export const RatingGroup = /* @__PURE__ */ Object.assign(RatingGroupRoot, { Provider: RatingGroupProvider, Root: RatingGroupRoot, Label: RatingGroupLabel, Control: RatingGroupControl, Item: RatingGroupItem, ItemIndicator: RatingGroupItemIndicator, HiddenInput: RatingGroupHiddenInput, ValueText: RatingGroupValueText });

// uifn/react/src/generated/rating-group.tsx
'use client';

import * as React from 'react';
import { createRatingGroupController, type RatingGroupProps, type RatingGroupController } from '@uifn/core/primitives/rating-group';
import {
  ReactPrimitivePart,
  ReactPrimitiveRoot,
  useReactPrimitive,
  type ReactPrimitiveBridge,
  type ReactPrimitiveDefinition,
  type ReactPrimitiveHookResult,
  type ReactPrimitivePartProps,
  type ReactPrimitiveRootProps,
} from '../internal/compound';

const RatingGroupContext = React.createContext<ReactPrimitiveBridge<RatingGroupProps> | null>(null);
const RatingGroupDefinition: ReactPrimitiveDefinition<RatingGroupProps> = {
  name: 'RatingGroup',
  family: 'range-gesture',
  kind: 'interactive-controller',
  rootPart: 'root',
  inputNames: ["value","defaultValue","count","allowHalf","name","disabled","readOnly","required"],
  context: RatingGroupContext,
  createController: createRatingGroupController as never,
};

export type RatingGroupRootProps = ReactPrimitiveRootProps<RatingGroupProps, 'div'>;
export const RatingGroupRoot = React.forwardRef<React.ElementRef<'div'>, RatingGroupRootProps>((props, ref) => (
  <ReactPrimitiveRoot definition={RatingGroupDefinition} element="div" forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
RatingGroupRoot.displayName = 'RatingGroupRoot';

export type RatingGroupLabelProps = ReactPrimitivePartProps<RatingGroupController['parts']['label'], 'label', false>;
export const RatingGroupLabel = React.forwardRef<React.ElementRef<'label'>, RatingGroupLabelProps>((props, ref) => (
  <ReactPrimitivePart definition={RatingGroupDefinition as never} part="label" element="label" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
RatingGroupLabel.displayName = 'RatingGroupLabel';

export type RatingGroupControlProps = ReactPrimitivePartProps<RatingGroupController['parts']['control'], 'div', false>;
export const RatingGroupControl = React.forwardRef<React.ElementRef<'div'>, RatingGroupControlProps>((props, ref) => (
  <ReactPrimitivePart definition={RatingGroupDefinition as never} part="control" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
RatingGroupControl.displayName = 'RatingGroupControl';

export type RatingGroupItemProps = ReactPrimitivePartProps<RatingGroupController['parts']['item'], 'button', true>;
export const RatingGroupItem = React.forwardRef<React.ElementRef<'button'>, RatingGroupItemProps>((props, ref) => (
  <ReactPrimitivePart definition={RatingGroupDefinition as never} part="item" element="button" many={true} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
RatingGroupItem.displayName = 'RatingGroupItem';

export type RatingGroupItemIndicatorProps = ReactPrimitivePartProps<RatingGroupController['parts']['itemIndicator'], 'span', true>;
export const RatingGroupItemIndicator = React.forwardRef<React.ElementRef<'span'>, RatingGroupItemIndicatorProps>((props, ref) => (
  <ReactPrimitivePart definition={RatingGroupDefinition as never} part="itemIndicator" element="span" many={true} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
RatingGroupItemIndicator.displayName = 'RatingGroupItemIndicator';

export type RatingGroupHiddenInputProps = ReactPrimitivePartProps<RatingGroupController['parts']['hiddenInput'], 'input', false>;
export const RatingGroupHiddenInput = React.forwardRef<React.ElementRef<'input'>, RatingGroupHiddenInputProps>((props, ref) => (
  <ReactPrimitivePart definition={RatingGroupDefinition as never} part="hiddenInput" element="input" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
RatingGroupHiddenInput.displayName = 'RatingGroupHiddenInput';

export type RatingGroupValueTextProps = ReactPrimitivePartProps<RatingGroupController['parts']['valueText'], 'span', false>;
export const RatingGroupValueText = React.forwardRef<React.ElementRef<'span'>, RatingGroupValueTextProps>((props, ref) => (
  <ReactPrimitivePart definition={RatingGroupDefinition as never} part="valueText" element="span" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
RatingGroupValueText.displayName = 'RatingGroupValueText';

export const RatingGroupProvider = RatingGroupRoot;
export function useRatingGroup(inputs: RatingGroupProps = {} as RatingGroupProps): ReactPrimitiveHookResult<RatingGroupController['state'], RatingGroupController['actions']> {
  return useReactPrimitive(RatingGroupDefinition, inputs) as ReactPrimitiveHookResult<RatingGroupController['state'], RatingGroupController['actions']>;
}
export const RatingGroup = Object.assign(RatingGroupRoot, { Provider: RatingGroupProvider, Root: RatingGroupRoot, Label: RatingGroupLabel, Control: RatingGroupControl, Item: RatingGroupItem, ItemIndicator: RatingGroupItemIndicator, HiddenInput: RatingGroupHiddenInput, ValueText: RatingGroupValueText });
