// uifn/solid/src/generated/tags-input.tsx
import { createContext, type JSX } from 'solid-js';
import { createTagsInputController, type TagsInputProps, type TagsInputController } from '@uifn/core/primitives/tags-input';
import {
  createSolidPrimitiveInstanceId,
  SolidPrimitivePart,
  SolidPrimitiveRoot,
  type SolidPrimitiveContextValue,
  type SolidPrimitiveDefinition,
  type SolidPrimitivePartProps,
  type SolidPrimitiveRootProps,
} from '../internal/compound.jsx';

const TagsInputContext = createContext<SolidPrimitiveContextValue<TagsInputProps>>();
export const TagsInputDefinition: SolidPrimitiveDefinition<TagsInputProps> = {
  name: 'TagsInput',
  family: 'selection-collection',
  kind: 'interactive-controller',
  rootPart: 'root',
  inputNames: ["value","defaultValue","allowDuplicates","max","delimiter","name","disabled","readOnly","required"],
  context: TagsInputContext,
  createController: createTagsInputController as never,
};

function TagsInputRootElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type TagsInputRootProps = SolidPrimitiveRootProps<TagsInputProps, 'div'>;
export function TagsInputRoot(props: TagsInputRootProps): JSX.Element {
  const hydrationId = createSolidPrimitiveInstanceId();
  return <SolidPrimitiveRoot definition={TagsInputDefinition} element="div" renderElement={TagsInputRootElement as never} hydrationId={hydrationId} props={props as never} />;
}

function TagsInputLabelElement(props: JSX.IntrinsicElements['label']): JSX.Element {
  return <label {...props} />;
}

export type TagsInputLabelProps = SolidPrimitivePartProps<TagsInputController['parts']['label'], 'label', false>;
export function TagsInputLabel(props: TagsInputLabelProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={TagsInputDefinition as never}
      part="label"
      element="label"
      renderElement={TagsInputLabelElement as never}
      many={false}
      props={props as never}
    />
  );
}

function TagsInputControlElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type TagsInputControlProps = SolidPrimitivePartProps<TagsInputController['parts']['control'], 'div', false>;
export function TagsInputControl(props: TagsInputControlProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={TagsInputDefinition as never}
      part="control"
      element="div"
      renderElement={TagsInputControlElement as never}
      many={false}
      props={props as never}
    />
  );
}

function TagsInputItemElement(props: JSX.IntrinsicElements['span']): JSX.Element {
  return <span {...props} />;
}

export type TagsInputItemProps = SolidPrimitivePartProps<TagsInputController['parts']['item'], 'span', true>;
export function TagsInputItem(props: TagsInputItemProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={TagsInputDefinition as never}
      part="item"
      element="span"
      renderElement={TagsInputItemElement as never}
      many={true}
      props={props as never}
    />
  );
}

function TagsInputItemTextElement(props: JSX.IntrinsicElements['span']): JSX.Element {
  return <span {...props} />;
}

export type TagsInputItemTextProps = SolidPrimitivePartProps<TagsInputController['parts']['itemText'], 'span', true>;
export function TagsInputItemText(props: TagsInputItemTextProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={TagsInputDefinition as never}
      part="itemText"
      element="span"
      renderElement={TagsInputItemTextElement as never}
      many={true}
      props={props as never}
    />
  );
}

function TagsInputItemDeleteElement(props: JSX.IntrinsicElements['button']): JSX.Element {
  return <button {...props} />;
}

export type TagsInputItemDeleteProps = SolidPrimitivePartProps<TagsInputController['parts']['itemDelete'], 'button', true>;
export function TagsInputItemDelete(props: TagsInputItemDeleteProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={TagsInputDefinition as never}
      part="itemDelete"
      element="button"
      renderElement={TagsInputItemDeleteElement as never}
      many={true}
      props={props as never}
    />
  );
}

function TagsInputInputElement(props: JSX.IntrinsicElements['input']): JSX.Element {
  return <input {...props} />;
}

export type TagsInputInputProps = SolidPrimitivePartProps<TagsInputController['parts']['input'], 'input', false>;
export function TagsInputInput(props: TagsInputInputProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={TagsInputDefinition as never}
      part="input"
      element="input"
      renderElement={TagsInputInputElement as never}
      many={false}
      props={props as never}
    />
  );
}

function TagsInputClearElement(props: JSX.IntrinsicElements['button']): JSX.Element {
  return <button {...props} />;
}

export type TagsInputClearProps = SolidPrimitivePartProps<TagsInputController['parts']['clear'], 'button', false>;
export function TagsInputClear(props: TagsInputClearProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={TagsInputDefinition as never}
      part="clear"
      element="button"
      renderElement={TagsInputClearElement as never}
      many={false}
      props={props as never}
    />
  );
}

function TagsInputHiddenInputElement(props: JSX.IntrinsicElements['input']): JSX.Element {
  return <input {...props} />;
}

export type TagsInputHiddenInputProps = SolidPrimitivePartProps<TagsInputController['parts']['hiddenInput'], 'input', true>;
export function TagsInputHiddenInput(props: TagsInputHiddenInputProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={TagsInputDefinition as never}
      part="hiddenInput"
      element="input"
      renderElement={TagsInputHiddenInputElement as never}
      many={true}
      props={props as never}
    />
  );
}

function TagsInputErrorElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type TagsInputErrorProps = SolidPrimitivePartProps<TagsInputController['parts']['error'], 'div', false>;
export function TagsInputError(props: TagsInputErrorProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={TagsInputDefinition as never}
      part="error"
      element="div"
      renderElement={TagsInputErrorElement as never}
      many={false}
      props={props as never}
    />
  );
}

export const TagsInputProvider = TagsInputRoot;
export const TagsInput = /* @__PURE__ */ Object.assign(TagsInputRoot, { Provider: TagsInputProvider, Root: TagsInputRoot, Label: TagsInputLabel, Control: TagsInputControl, Item: TagsInputItem, ItemText: TagsInputItemText, ItemDelete: TagsInputItemDelete, Input: TagsInputInput, Clear: TagsInputClear, HiddenInput: TagsInputHiddenInput, Error: TagsInputError });

// uifn/react/src/generated/tags-input.tsx
'use client';

import * as React from 'react';
import { createTagsInputController, type TagsInputProps, type TagsInputController } from '@uifn/core/primitives/tags-input';
import {
  ReactPrimitivePart,
  ReactPrimitiveRoot,
  useReactPrimitive,
  type ReactPrimitiveBridge,
  type ReactPrimitiveDefinition,
  type ReactPrimitiveHookResult,
  type ReactPrimitivePartProps,
  type ReactPrimitiveRootProps,
} from '../internal/compound';

const TagsInputContext = React.createContext<ReactPrimitiveBridge<TagsInputProps> | null>(null);
const TagsInputDefinition: ReactPrimitiveDefinition<TagsInputProps> = {
  name: 'TagsInput',
  family: 'selection-collection',
  kind: 'interactive-controller',
  rootPart: 'root',
  inputNames: ["value","defaultValue","allowDuplicates","max","delimiter","name","disabled","readOnly","required"],
  context: TagsInputContext,
  createController: createTagsInputController as never,
};

export type TagsInputRootProps = ReactPrimitiveRootProps<TagsInputProps, 'div'>;
export const TagsInputRoot = React.forwardRef<React.ElementRef<'div'>, TagsInputRootProps>((props, ref) => (
  <ReactPrimitiveRoot definition={TagsInputDefinition} element="div" forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
TagsInputRoot.displayName = 'TagsInputRoot';

export type TagsInputLabelProps = ReactPrimitivePartProps<TagsInputController['parts']['label'], 'label', false>;
export const TagsInputLabel = React.forwardRef<React.ElementRef<'label'>, TagsInputLabelProps>((props, ref) => (
  <ReactPrimitivePart definition={TagsInputDefinition as never} part="label" element="label" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
TagsInputLabel.displayName = 'TagsInputLabel';

export type TagsInputControlProps = ReactPrimitivePartProps<TagsInputController['parts']['control'], 'div', false>;
export const TagsInputControl = React.forwardRef<React.ElementRef<'div'>, TagsInputControlProps>((props, ref) => (
  <ReactPrimitivePart definition={TagsInputDefinition as never} part="control" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
TagsInputControl.displayName = 'TagsInputControl';

export type TagsInputItemProps = ReactPrimitivePartProps<TagsInputController['parts']['item'], 'span', true>;
export const TagsInputItem = React.forwardRef<React.ElementRef<'span'>, TagsInputItemProps>((props, ref) => (
  <ReactPrimitivePart definition={TagsInputDefinition as never} part="item" element="span" many={true} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
TagsInputItem.displayName = 'TagsInputItem';

export type TagsInputItemTextProps = ReactPrimitivePartProps<TagsInputController['parts']['itemText'], 'span', true>;
export const TagsInputItemText = React.forwardRef<React.ElementRef<'span'>, TagsInputItemTextProps>((props, ref) => (
  <ReactPrimitivePart definition={TagsInputDefinition as never} part="itemText" element="span" many={true} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
TagsInputItemText.displayName = 'TagsInputItemText';

export type TagsInputItemDeleteProps = ReactPrimitivePartProps<TagsInputController['parts']['itemDelete'], 'button', true>;
export const TagsInputItemDelete = React.forwardRef<React.ElementRef<'button'>, TagsInputItemDeleteProps>((props, ref) => (
  <ReactPrimitivePart definition={TagsInputDefinition as never} part="itemDelete" element="button" many={true} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
TagsInputItemDelete.displayName = 'TagsInputItemDelete';

export type TagsInputInputProps = ReactPrimitivePartProps<TagsInputController['parts']['input'], 'input', false>;
export const TagsInputInput = React.forwardRef<React.ElementRef<'input'>, TagsInputInputProps>((props, ref) => (
  <ReactPrimitivePart definition={TagsInputDefinition as never} part="input" element="input" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
TagsInputInput.displayName = 'TagsInputInput';

export type TagsInputClearProps = ReactPrimitivePartProps<TagsInputController['parts']['clear'], 'button', false>;
export const TagsInputClear = React.forwardRef<React.ElementRef<'button'>, TagsInputClearProps>((props, ref) => (
  <ReactPrimitivePart definition={TagsInputDefinition as never} part="clear" element="button" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
TagsInputClear.displayName = 'TagsInputClear';

export type TagsInputHiddenInputProps = ReactPrimitivePartProps<TagsInputController['parts']['hiddenInput'], 'input', true>;
export const TagsInputHiddenInput = React.forwardRef<React.ElementRef<'input'>, TagsInputHiddenInputProps>((props, ref) => (
  <ReactPrimitivePart definition={TagsInputDefinition as never} part="hiddenInput" element="input" many={true} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
TagsInputHiddenInput.displayName = 'TagsInputHiddenInput';

export type TagsInputErrorProps = ReactPrimitivePartProps<TagsInputController['parts']['error'], 'div', false>;
export const TagsInputError = React.forwardRef<React.ElementRef<'div'>, TagsInputErrorProps>((props, ref) => (
  <ReactPrimitivePart definition={TagsInputDefinition as never} part="error" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
TagsInputError.displayName = 'TagsInputError';

export const TagsInputProvider = TagsInputRoot;
export function useTagsInput(inputs: TagsInputProps = {} as TagsInputProps): ReactPrimitiveHookResult<TagsInputController['state'], TagsInputController['actions']> {
  return useReactPrimitive(TagsInputDefinition, inputs) as ReactPrimitiveHookResult<TagsInputController['state'], TagsInputController['actions']>;
}
export const TagsInput = Object.assign(TagsInputRoot, { Provider: TagsInputProvider, Root: TagsInputRoot, Label: TagsInputLabel, Control: TagsInputControl, Item: TagsInputItem, ItemText: TagsInputItemText, ItemDelete: TagsInputItemDelete, Input: TagsInputInput, Clear: TagsInputClear, HiddenInput: TagsInputHiddenInput, Error: TagsInputError });
