// uifn/react/src/generated/avatar.tsx
'use client';

import * as React from 'react';
import { AvatarContract, type AvatarProps, type AvatarContractParts } from '@uifn/core/primitives/avatar';
import {
  ReactPrimitivePart,
  ReactPrimitiveRoot,
  useReactPrimitive,
  type ReactPrimitiveBridge,
  type ReactPrimitiveDefinition,
  type ReactPrimitiveHookResult,
  type ReactPrimitivePartProps,
  type ReactPrimitiveRootProps,
} from '../internal/compound';

const AvatarContext = React.createContext<ReactPrimitiveBridge<AvatarProps> | null>(null);
const AvatarDefinition: ReactPrimitiveDefinition<AvatarProps> = {
  name: 'Avatar',
  family: 'static-foundation',
  kind: 'typed-static-contract',
  rootPart: 'root',
  inputNames: ["src","alt","fallbackDelay"],
  context: AvatarContext,
  contract: AvatarContract as never,
};

export type AvatarRootProps = ReactPrimitiveRootProps<AvatarProps, 'span'>;
export const AvatarRoot = React.forwardRef<React.ElementRef<'span'>, AvatarRootProps>((props, ref) => (
  <ReactPrimitiveRoot definition={AvatarDefinition} element="span" forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
AvatarRoot.displayName = 'AvatarRoot';

export type AvatarImageProps = ReactPrimitivePartProps<AvatarContractParts['image'], 'img', false>;
export const AvatarImage = React.forwardRef<React.ElementRef<'img'>, AvatarImageProps>((props, ref) => (
  <ReactPrimitivePart definition={AvatarDefinition as never} part="image" element="img" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
AvatarImage.displayName = 'AvatarImage';

export type AvatarFallbackProps = ReactPrimitivePartProps<AvatarContractParts['fallback'], 'span', false>;
export const AvatarFallback = React.forwardRef<React.ElementRef<'span'>, AvatarFallbackProps>((props, ref) => (
  <ReactPrimitivePart definition={AvatarDefinition as never} part="fallback" element="span" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
AvatarFallback.displayName = 'AvatarFallback';

export const AvatarProvider = AvatarRoot;
export function useAvatar(inputs: AvatarProps): ReactPrimitiveHookResult<ReturnType<typeof AvatarContract.getState>, Record<string, never>> {
  return useReactPrimitive(AvatarDefinition, inputs) as ReactPrimitiveHookResult<ReturnType<typeof AvatarContract.getState>, Record<string, never>>;
}
export const Avatar = Object.assign(AvatarRoot, { Provider: AvatarProvider, Root: AvatarRoot, Image: AvatarImage, Fallback: AvatarFallback });

// uifn/solid/src/generated/avatar.tsx
import { createContext, type JSX } from 'solid-js';
import { AvatarContract, type AvatarProps, type AvatarContractParts } from '@uifn/core/primitives/avatar';
import {
  createSolidPrimitiveInstanceId,
  SolidPrimitivePart,
  SolidPrimitiveRoot,
  type SolidPrimitiveContextValue,
  type SolidPrimitiveDefinition,
  type SolidPrimitivePartProps,
  type SolidPrimitiveRootProps,
} from '../internal/compound.jsx';

const AvatarContext = createContext<SolidPrimitiveContextValue<AvatarProps>>();
export const AvatarDefinition: SolidPrimitiveDefinition<AvatarProps> = {
  name: 'Avatar',
  family: 'static-foundation',
  kind: 'typed-static-contract',
  rootPart: 'root',
  inputNames: ["src","alt","fallbackDelay"],
  context: AvatarContext,
  contract: AvatarContract as never,
};

function AvatarRootElement(props: JSX.IntrinsicElements['span']): JSX.Element {
  return <span {...props} />;
}

export type AvatarRootProps = SolidPrimitiveRootProps<AvatarProps, 'span'>;
export function AvatarRoot(props: AvatarRootProps): JSX.Element {
  const hydrationId = createSolidPrimitiveInstanceId();
  return <SolidPrimitiveRoot definition={AvatarDefinition} element="span" renderElement={AvatarRootElement as never} hydrationId={hydrationId} props={props as never} />;
}

function AvatarImageElement(props: JSX.IntrinsicElements['img']): JSX.Element {
  return <img {...props} />;
}

export type AvatarImageProps = SolidPrimitivePartProps<AvatarContractParts['image'], 'img', false>;
export function AvatarImage(props: AvatarImageProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={AvatarDefinition as never}
      part="image"
      element="img"
      renderElement={AvatarImageElement as never}
      many={false}
      props={props as never}
    />
  );
}

function AvatarFallbackElement(props: JSX.IntrinsicElements['span']): JSX.Element {
  return <span {...props} />;
}

export type AvatarFallbackProps = SolidPrimitivePartProps<AvatarContractParts['fallback'], 'span', false>;
export function AvatarFallback(props: AvatarFallbackProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={AvatarDefinition as never}
      part="fallback"
      element="span"
      renderElement={AvatarFallbackElement as never}
      many={false}
      props={props as never}
    />
  );
}

export const AvatarProvider = AvatarRoot;
export const Avatar = /* @__PURE__ */ Object.assign(AvatarRoot, { Provider: AvatarProvider, Root: AvatarRoot, Image: AvatarImage, Fallback: AvatarFallback });
