// uifn/react/src/generated/badge.tsx
'use client';

import * as React from 'react';
import { BadgeContract, type BadgeProps, type BadgeContractParts } from '@uifn/core/primitives/badge';
import {
  ReactPrimitivePart,
  ReactPrimitiveRoot,
  useReactPrimitive,
  type ReactPrimitiveBridge,
  type ReactPrimitiveDefinition,
  type ReactPrimitiveHookResult,
  type ReactPrimitivePartProps,
  type ReactPrimitiveRootProps,
} from '../internal/compound';

const BadgeContext = React.createContext<ReactPrimitiveBridge<BadgeProps> | null>(null);
const BadgeDefinition: ReactPrimitiveDefinition<BadgeProps> = {
  name: 'Badge',
  family: 'static-foundation',
  kind: 'typed-static-contract',
  rootPart: 'root',
  inputNames: ["variant"],
  context: BadgeContext,
  contract: BadgeContract as never,
};

export type BadgeRootProps = ReactPrimitiveRootProps<BadgeProps, 'span'>;
export const BadgeRoot = React.forwardRef<React.ElementRef<'span'>, BadgeRootProps>((props, ref) => (
  <ReactPrimitiveRoot definition={BadgeDefinition} element="span" forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
BadgeRoot.displayName = 'BadgeRoot';



export const BadgeProvider = BadgeRoot;
export function useBadge(inputs: BadgeProps = {} as BadgeProps): ReactPrimitiveHookResult<ReturnType<typeof BadgeContract.getState>, Record<string, never>> {
  return useReactPrimitive(BadgeDefinition, inputs) as ReactPrimitiveHookResult<ReturnType<typeof BadgeContract.getState>, Record<string, never>>;
}
export const Badge = Object.assign(BadgeRoot, { Provider: BadgeProvider, Root: BadgeRoot });

// uifn/solid/src/generated/badge.tsx
import { createContext, type JSX } from 'solid-js';
import { BadgeContract, type BadgeProps, type BadgeContractParts } from '@uifn/core/primitives/badge';
import {
  createSolidPrimitiveInstanceId,
  SolidPrimitivePart,
  SolidPrimitiveRoot,
  type SolidPrimitiveContextValue,
  type SolidPrimitiveDefinition,
  type SolidPrimitivePartProps,
  type SolidPrimitiveRootProps,
} from '../internal/compound.jsx';

const BadgeContext = createContext<SolidPrimitiveContextValue<BadgeProps>>();
export const BadgeDefinition: SolidPrimitiveDefinition<BadgeProps> = {
  name: 'Badge',
  family: 'static-foundation',
  kind: 'typed-static-contract',
  rootPart: 'root',
  inputNames: ["variant"],
  context: BadgeContext,
  contract: BadgeContract as never,
};

function BadgeRootElement(props: JSX.IntrinsicElements['span']): JSX.Element {
  return <span {...props} />;
}

export type BadgeRootProps = SolidPrimitiveRootProps<BadgeProps, 'span'>;
export function BadgeRoot(props: BadgeRootProps): JSX.Element {
  const hydrationId = createSolidPrimitiveInstanceId();
  return <SolidPrimitiveRoot definition={BadgeDefinition} element="span" renderElement={BadgeRootElement as never} hydrationId={hydrationId} props={props as never} />;
}



export const BadgeProvider = BadgeRoot;
export const Badge = /* @__PURE__ */ Object.assign(BadgeRoot, { Provider: BadgeProvider, Root: BadgeRoot });
