// uifn/react/src/generated/carousel.tsx
'use client';

import * as React from 'react';
import { createCarouselController, type CarouselProps, type CarouselController } from '@uifn/core/primitives/carousel';
import {
  ReactPrimitivePart,
  ReactPrimitiveRoot,
  useReactPrimitive,
  type ReactPrimitiveBridge,
  type ReactPrimitiveDefinition,
  type ReactPrimitiveHookResult,
  type ReactPrimitivePartProps,
  type ReactPrimitiveRootProps,
} from '../internal/compound';

const CarouselContext = React.createContext<ReactPrimitiveBridge<CarouselProps> | null>(null);
const CarouselDefinition: ReactPrimitiveDefinition<CarouselProps> = {
  name: 'Carousel',
  family: 'range-gesture',
  kind: 'interactive-controller',
  rootPart: 'root',
  inputNames: ["index","defaultIndex","itemCount","loop","orientation","autoplayDelay","dir"],
  context: CarouselContext,
  createController: createCarouselController as never,
};

export type CarouselRootProps = ReactPrimitiveRootProps<CarouselProps, 'section'>;
export const CarouselRoot = React.forwardRef<React.ElementRef<'section'>, CarouselRootProps>((props, ref) => (
  <ReactPrimitiveRoot definition={CarouselDefinition} element="section" forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
CarouselRoot.displayName = 'CarouselRoot';

export type CarouselViewportProps = ReactPrimitivePartProps<CarouselController['parts']['viewport'], 'div', false>;
export const CarouselViewport = React.forwardRef<React.ElementRef<'div'>, CarouselViewportProps>((props, ref) => (
  <ReactPrimitivePart definition={CarouselDefinition as never} part="viewport" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
CarouselViewport.displayName = 'CarouselViewport';

export type CarouselItemProps = ReactPrimitivePartProps<CarouselController['parts']['item'], 'div', true>;
export const CarouselItem = React.forwardRef<React.ElementRef<'div'>, CarouselItemProps>((props, ref) => (
  <ReactPrimitivePart definition={CarouselDefinition as never} part="item" element="div" many={true} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
CarouselItem.displayName = 'CarouselItem';

export type CarouselPreviousProps = ReactPrimitivePartProps<CarouselController['parts']['previous'], 'button', false>;
export const CarouselPrevious = React.forwardRef<React.ElementRef<'button'>, CarouselPreviousProps>((props, ref) => (
  <ReactPrimitivePart definition={CarouselDefinition as never} part="previous" element="button" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
CarouselPrevious.displayName = 'CarouselPrevious';

export type CarouselNextProps = ReactPrimitivePartProps<CarouselController['parts']['next'], 'button', false>;
export const CarouselNext = React.forwardRef<React.ElementRef<'button'>, CarouselNextProps>((props, ref) => (
  <ReactPrimitivePart definition={CarouselDefinition as never} part="next" element="button" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
CarouselNext.displayName = 'CarouselNext';

export type CarouselIndicatorGroupProps = ReactPrimitivePartProps<CarouselController['parts']['indicatorGroup'], 'div', false>;
export const CarouselIndicatorGroup = React.forwardRef<React.ElementRef<'div'>, CarouselIndicatorGroupProps>((props, ref) => (
  <ReactPrimitivePart definition={CarouselDefinition as never} part="indicatorGroup" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
CarouselIndicatorGroup.displayName = 'CarouselIndicatorGroup';

export type CarouselIndicatorProps = ReactPrimitivePartProps<CarouselController['parts']['indicator'], 'button', true>;
export const CarouselIndicator = React.forwardRef<React.ElementRef<'button'>, CarouselIndicatorProps>((props, ref) => (
  <ReactPrimitivePart definition={CarouselDefinition as never} part="indicator" element="button" many={true} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
CarouselIndicator.displayName = 'CarouselIndicator';

export type CarouselLiveRegionProps = ReactPrimitivePartProps<CarouselController['parts']['liveRegion'], 'div', false>;
export const CarouselLiveRegion = React.forwardRef<React.ElementRef<'div'>, CarouselLiveRegionProps>((props, ref) => (
  <ReactPrimitivePart definition={CarouselDefinition as never} part="liveRegion" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
CarouselLiveRegion.displayName = 'CarouselLiveRegion';

export const CarouselProvider = CarouselRoot;
export function useCarousel(inputs: CarouselProps): ReactPrimitiveHookResult<CarouselController['state'], CarouselController['actions']> {
  return useReactPrimitive(CarouselDefinition, inputs) as ReactPrimitiveHookResult<CarouselController['state'], CarouselController['actions']>;
}
export const Carousel = Object.assign(CarouselRoot, { Provider: CarouselProvider, Root: CarouselRoot, Viewport: CarouselViewport, Item: CarouselItem, Previous: CarouselPrevious, Next: CarouselNext, IndicatorGroup: CarouselIndicatorGroup, Indicator: CarouselIndicator, LiveRegion: CarouselLiveRegion });

// uifn/solid/src/generated/carousel.tsx
import { createContext, type JSX } from 'solid-js';
import { createCarouselController, type CarouselProps, type CarouselController } from '@uifn/core/primitives/carousel';
import {
  createSolidPrimitiveInstanceId,
  SolidPrimitivePart,
  SolidPrimitiveRoot,
  type SolidPrimitiveContextValue,
  type SolidPrimitiveDefinition,
  type SolidPrimitivePartProps,
  type SolidPrimitiveRootProps,
} from '../internal/compound.jsx';

const CarouselContext = createContext<SolidPrimitiveContextValue<CarouselProps>>();
export const CarouselDefinition: SolidPrimitiveDefinition<CarouselProps> = {
  name: 'Carousel',
  family: 'range-gesture',
  kind: 'interactive-controller',
  rootPart: 'root',
  inputNames: ["index","defaultIndex","itemCount","loop","orientation","autoplayDelay","dir"],
  context: CarouselContext,
  createController: createCarouselController as never,
};

function CarouselRootElement(props: JSX.IntrinsicElements['section']): JSX.Element {
  return <section {...props} />;
}

export type CarouselRootProps = SolidPrimitiveRootProps<CarouselProps, 'section'>;
export function CarouselRoot(props: CarouselRootProps): JSX.Element {
  const hydrationId = createSolidPrimitiveInstanceId();
  return <SolidPrimitiveRoot definition={CarouselDefinition} element="section" renderElement={CarouselRootElement as never} hydrationId={hydrationId} props={props as never} />;
}

function CarouselViewportElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type CarouselViewportProps = SolidPrimitivePartProps<CarouselController['parts']['viewport'], 'div', false>;
export function CarouselViewport(props: CarouselViewportProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={CarouselDefinition as never}
      part="viewport"
      element="div"
      renderElement={CarouselViewportElement as never}
      many={false}
      props={props as never}
    />
  );
}

function CarouselItemElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type CarouselItemProps = SolidPrimitivePartProps<CarouselController['parts']['item'], 'div', true>;
export function CarouselItem(props: CarouselItemProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={CarouselDefinition as never}
      part="item"
      element="div"
      renderElement={CarouselItemElement as never}
      many={true}
      props={props as never}
    />
  );
}

function CarouselPreviousElement(props: JSX.IntrinsicElements['button']): JSX.Element {
  return <button {...props} />;
}

export type CarouselPreviousProps = SolidPrimitivePartProps<CarouselController['parts']['previous'], 'button', false>;
export function CarouselPrevious(props: CarouselPreviousProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={CarouselDefinition as never}
      part="previous"
      element="button"
      renderElement={CarouselPreviousElement as never}
      many={false}
      props={props as never}
    />
  );
}

function CarouselNextElement(props: JSX.IntrinsicElements['button']): JSX.Element {
  return <button {...props} />;
}

export type CarouselNextProps = SolidPrimitivePartProps<CarouselController['parts']['next'], 'button', false>;
export function CarouselNext(props: CarouselNextProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={CarouselDefinition as never}
      part="next"
      element="button"
      renderElement={CarouselNextElement as never}
      many={false}
      props={props as never}
    />
  );
}

function CarouselIndicatorGroupElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type CarouselIndicatorGroupProps = SolidPrimitivePartProps<CarouselController['parts']['indicatorGroup'], 'div', false>;
export function CarouselIndicatorGroup(props: CarouselIndicatorGroupProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={CarouselDefinition as never}
      part="indicatorGroup"
      element="div"
      renderElement={CarouselIndicatorGroupElement as never}
      many={false}
      props={props as never}
    />
  );
}

function CarouselIndicatorElement(props: JSX.IntrinsicElements['button']): JSX.Element {
  return <button {...props} />;
}

export type CarouselIndicatorProps = SolidPrimitivePartProps<CarouselController['parts']['indicator'], 'button', true>;
export function CarouselIndicator(props: CarouselIndicatorProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={CarouselDefinition as never}
      part="indicator"
      element="button"
      renderElement={CarouselIndicatorElement as never}
      many={true}
      props={props as never}
    />
  );
}

function CarouselLiveRegionElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type CarouselLiveRegionProps = SolidPrimitivePartProps<CarouselController['parts']['liveRegion'], 'div', false>;
export function CarouselLiveRegion(props: CarouselLiveRegionProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={CarouselDefinition as never}
      part="liveRegion"
      element="div"
      renderElement={CarouselLiveRegionElement as never}
      many={false}
      props={props as never}
    />
  );
}

export const CarouselProvider = CarouselRoot;
export const Carousel = /* @__PURE__ */ Object.assign(CarouselRoot, { Provider: CarouselProvider, Root: CarouselRoot, Viewport: CarouselViewport, Item: CarouselItem, Previous: CarouselPrevious, Next: CarouselNext, IndicatorGroup: CarouselIndicatorGroup, Indicator: CarouselIndicator, LiveRegion: CarouselLiveRegion });
