// uifn/react/src/generated/collapsible.tsx
'use client';

import * as React from 'react';
import { createCollapsibleController, type CollapsibleProps, type CollapsibleController } from '@uifn/core/primitives/collapsible';
import {
  ReactPrimitivePart,
  ReactPrimitiveRoot,
  useReactPrimitive,
  type ReactPrimitiveBridge,
  type ReactPrimitiveDefinition,
  type ReactPrimitiveHookResult,
  type ReactPrimitivePartProps,
  type ReactPrimitiveRootProps,
} from '../internal/compound';

const CollapsibleContext = React.createContext<ReactPrimitiveBridge<CollapsibleProps> | null>(null);
const CollapsibleDefinition: ReactPrimitiveDefinition<CollapsibleProps> = {
  name: 'Collapsible',
  family: 'disclosure',
  kind: 'interactive-controller',
  rootPart: 'root',
  inputNames: ["open","defaultOpen","disabled"],
  context: CollapsibleContext,
  createController: createCollapsibleController as never,
};

export type CollapsibleRootProps = ReactPrimitiveRootProps<CollapsibleProps, 'div'>;
export const CollapsibleRoot = React.forwardRef<React.ElementRef<'div'>, CollapsibleRootProps>((props, ref) => (
  <ReactPrimitiveRoot definition={CollapsibleDefinition} element="div" forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
CollapsibleRoot.displayName = 'CollapsibleRoot';

export type CollapsibleTriggerProps = ReactPrimitivePartProps<CollapsibleController['parts']['trigger'], 'button', false>;
export const CollapsibleTrigger = React.forwardRef<React.ElementRef<'button'>, CollapsibleTriggerProps>((props, ref) => (
  <ReactPrimitivePart definition={CollapsibleDefinition as never} part="trigger" element="button" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
CollapsibleTrigger.displayName = 'CollapsibleTrigger';

export type CollapsibleContentProps = ReactPrimitivePartProps<CollapsibleController['parts']['content'], 'div', false>;
export const CollapsibleContent = React.forwardRef<React.ElementRef<'div'>, CollapsibleContentProps>((props, ref) => (
  <ReactPrimitivePart definition={CollapsibleDefinition as never} part="content" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
CollapsibleContent.displayName = 'CollapsibleContent';

export const CollapsibleProvider = CollapsibleRoot;
export function useCollapsible(inputs: CollapsibleProps = {} as CollapsibleProps): ReactPrimitiveHookResult<CollapsibleController['state'], CollapsibleController['actions']> {
  return useReactPrimitive(CollapsibleDefinition, inputs) as ReactPrimitiveHookResult<CollapsibleController['state'], CollapsibleController['actions']>;
}
export const Collapsible = Object.assign(CollapsibleRoot, { Provider: CollapsibleProvider, Root: CollapsibleRoot, Trigger: CollapsibleTrigger, Content: CollapsibleContent });

// uifn/solid/src/generated/collapsible.tsx
import { createContext, type JSX } from 'solid-js';
import { createCollapsibleController, type CollapsibleProps, type CollapsibleController } from '@uifn/core/primitives/collapsible';
import {
  createSolidPrimitiveInstanceId,
  SolidPrimitivePart,
  SolidPrimitiveRoot,
  type SolidPrimitiveContextValue,
  type SolidPrimitiveDefinition,
  type SolidPrimitivePartProps,
  type SolidPrimitiveRootProps,
} from '../internal/compound.jsx';

const CollapsibleContext = createContext<SolidPrimitiveContextValue<CollapsibleProps>>();
export const CollapsibleDefinition: SolidPrimitiveDefinition<CollapsibleProps> = {
  name: 'Collapsible',
  family: 'disclosure',
  kind: 'interactive-controller',
  rootPart: 'root',
  inputNames: ["open","defaultOpen","disabled"],
  context: CollapsibleContext,
  createController: createCollapsibleController as never,
};

function CollapsibleRootElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type CollapsibleRootProps = SolidPrimitiveRootProps<CollapsibleProps, 'div'>;
export function CollapsibleRoot(props: CollapsibleRootProps): JSX.Element {
  const hydrationId = createSolidPrimitiveInstanceId();
  return <SolidPrimitiveRoot definition={CollapsibleDefinition} element="div" renderElement={CollapsibleRootElement as never} hydrationId={hydrationId} props={props as never} />;
}

function CollapsibleTriggerElement(props: JSX.IntrinsicElements['button']): JSX.Element {
  return <button {...props} />;
}

export type CollapsibleTriggerProps = SolidPrimitivePartProps<CollapsibleController['parts']['trigger'], 'button', false>;
export function CollapsibleTrigger(props: CollapsibleTriggerProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={CollapsibleDefinition as never}
      part="trigger"
      element="button"
      renderElement={CollapsibleTriggerElement as never}
      many={false}
      props={props as never}
    />
  );
}

function CollapsibleContentElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type CollapsibleContentProps = SolidPrimitivePartProps<CollapsibleController['parts']['content'], 'div', false>;
export function CollapsibleContent(props: CollapsibleContentProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={CollapsibleDefinition as never}
      part="content"
      element="div"
      renderElement={CollapsibleContentElement as never}
      many={false}
      props={props as never}
    />
  );
}

export const CollapsibleProvider = CollapsibleRoot;
export const Collapsible = /* @__PURE__ */ Object.assign(CollapsibleRoot, { Provider: CollapsibleProvider, Root: CollapsibleRoot, Trigger: CollapsibleTrigger, Content: CollapsibleContent });
