// uifn/react/src/generated/drawer.tsx
'use client';

import * as React from 'react';
import { createDrawerController, type DrawerProps, type DrawerController } from '@uifn/core/primitives/drawer';
import {
  ReactPrimitivePart,
  ReactPrimitiveRoot,
  useReactPrimitive,
  type ReactPrimitiveBridge,
  type ReactPrimitiveDefinition,
  type ReactPrimitiveHookResult,
  type ReactPrimitivePartProps,
  type ReactPrimitiveRootProps,
} from '../internal/compound';

const DrawerContext = React.createContext<ReactPrimitiveBridge<DrawerProps> | null>(null);
const DrawerDefinition: ReactPrimitiveDefinition<DrawerProps> = {
  name: 'Drawer',
  family: 'modal-overlay',
  kind: 'interactive-controller',
  rootPart: 'root',
  inputNames: ["open","defaultOpen","side","modal","dismissThreshold"],
  context: DrawerContext,
  createController: createDrawerController as never,
};

export type DrawerRootProps = ReactPrimitiveRootProps<DrawerProps, 'div'>;
export const DrawerRoot = React.forwardRef<React.ElementRef<'div'>, DrawerRootProps>((props, ref) => (
  <ReactPrimitiveRoot definition={DrawerDefinition} element="div" forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
DrawerRoot.displayName = 'DrawerRoot';

export type DrawerTriggerProps = ReactPrimitivePartProps<DrawerController['parts']['trigger'], 'button', false>;
export const DrawerTrigger = React.forwardRef<React.ElementRef<'button'>, DrawerTriggerProps>((props, ref) => (
  <ReactPrimitivePart definition={DrawerDefinition as never} part="trigger" element="button" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
DrawerTrigger.displayName = 'DrawerTrigger';

export type DrawerPortalProps = ReactPrimitivePartProps<DrawerController['parts']['portal'], 'div', false>;
export const DrawerPortal = React.forwardRef<React.ElementRef<'div'>, DrawerPortalProps>((props, ref) => (
  <ReactPrimitivePart definition={DrawerDefinition as never} part="portal" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
DrawerPortal.displayName = 'DrawerPortal';

export type DrawerBackdropProps = ReactPrimitivePartProps<DrawerController['parts']['backdrop'], 'div', false>;
export const DrawerBackdrop = React.forwardRef<React.ElementRef<'div'>, DrawerBackdropProps>((props, ref) => (
  <ReactPrimitivePart definition={DrawerDefinition as never} part="backdrop" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
DrawerBackdrop.displayName = 'DrawerBackdrop';

export type DrawerPositionerProps = ReactPrimitivePartProps<DrawerController['parts']['positioner'], 'div', false>;
export const DrawerPositioner = React.forwardRef<React.ElementRef<'div'>, DrawerPositionerProps>((props, ref) => (
  <ReactPrimitivePart definition={DrawerDefinition as never} part="positioner" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
DrawerPositioner.displayName = 'DrawerPositioner';

export type DrawerContentProps = ReactPrimitivePartProps<DrawerController['parts']['content'], 'div', false>;
export const DrawerContent = React.forwardRef<React.ElementRef<'div'>, DrawerContentProps>((props, ref) => (
  <ReactPrimitivePart definition={DrawerDefinition as never} part="content" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
DrawerContent.displayName = 'DrawerContent';

export type DrawerHandleProps = ReactPrimitivePartProps<DrawerController['parts']['handle'], 'div', false>;
export const DrawerHandle = React.forwardRef<React.ElementRef<'div'>, DrawerHandleProps>((props, ref) => (
  <ReactPrimitivePart definition={DrawerDefinition as never} part="handle" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
DrawerHandle.displayName = 'DrawerHandle';

export type DrawerTitleProps = ReactPrimitivePartProps<DrawerController['parts']['title'], 'h2', false>;
export const DrawerTitle = React.forwardRef<React.ElementRef<'h2'>, DrawerTitleProps>((props, ref) => (
  <ReactPrimitivePart definition={DrawerDefinition as never} part="title" element="h2" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
DrawerTitle.displayName = 'DrawerTitle';

export type DrawerDescriptionProps = ReactPrimitivePartProps<DrawerController['parts']['description'], 'p', false>;
export const DrawerDescription = React.forwardRef<React.ElementRef<'p'>, DrawerDescriptionProps>((props, ref) => (
  <ReactPrimitivePart definition={DrawerDefinition as never} part="description" element="p" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
DrawerDescription.displayName = 'DrawerDescription';

export type DrawerCloseProps = ReactPrimitivePartProps<DrawerController['parts']['close'], 'button', false>;
export const DrawerClose = React.forwardRef<React.ElementRef<'button'>, DrawerCloseProps>((props, ref) => (
  <ReactPrimitivePart definition={DrawerDefinition as never} part="close" element="button" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
DrawerClose.displayName = 'DrawerClose';

export const DrawerProvider = DrawerRoot;
export function useDrawer(inputs: DrawerProps = {} as DrawerProps): ReactPrimitiveHookResult<DrawerController['state'], DrawerController['actions']> {
  return useReactPrimitive(DrawerDefinition, inputs) as ReactPrimitiveHookResult<DrawerController['state'], DrawerController['actions']>;
}
export const Drawer = Object.assign(DrawerRoot, { Provider: DrawerProvider, Root: DrawerRoot, Trigger: DrawerTrigger, Portal: DrawerPortal, Backdrop: DrawerBackdrop, Positioner: DrawerPositioner, Content: DrawerContent, Handle: DrawerHandle, Title: DrawerTitle, Description: DrawerDescription, Close: DrawerClose });

// uifn/solid/src/generated/drawer.tsx
import { createContext, type JSX } from 'solid-js';
import { createDrawerController, type DrawerProps, type DrawerController } from '@uifn/core/primitives/drawer';
import {
  createSolidPrimitiveInstanceId,
  SolidPrimitivePart,
  SolidPrimitiveRoot,
  type SolidPrimitiveContextValue,
  type SolidPrimitiveDefinition,
  type SolidPrimitivePartProps,
  type SolidPrimitiveRootProps,
} from '../internal/compound.jsx';

const DrawerContext = createContext<SolidPrimitiveContextValue<DrawerProps>>();
export const DrawerDefinition: SolidPrimitiveDefinition<DrawerProps> = {
  name: 'Drawer',
  family: 'modal-overlay',
  kind: 'interactive-controller',
  rootPart: 'root',
  inputNames: ["open","defaultOpen","side","modal","dismissThreshold"],
  context: DrawerContext,
  createController: createDrawerController as never,
};

function DrawerRootElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type DrawerRootProps = SolidPrimitiveRootProps<DrawerProps, 'div'>;
export function DrawerRoot(props: DrawerRootProps): JSX.Element {
  const hydrationId = createSolidPrimitiveInstanceId();
  return <SolidPrimitiveRoot definition={DrawerDefinition} element="div" renderElement={DrawerRootElement as never} hydrationId={hydrationId} props={props as never} />;
}

function DrawerTriggerElement(props: JSX.IntrinsicElements['button']): JSX.Element {
  return <button {...props} />;
}

export type DrawerTriggerProps = SolidPrimitivePartProps<DrawerController['parts']['trigger'], 'button', false>;
export function DrawerTrigger(props: DrawerTriggerProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={DrawerDefinition as never}
      part="trigger"
      element="button"
      renderElement={DrawerTriggerElement as never}
      many={false}
      props={props as never}
    />
  );
}

function DrawerPortalElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type DrawerPortalProps = SolidPrimitivePartProps<DrawerController['parts']['portal'], 'div', false>;
export function DrawerPortal(props: DrawerPortalProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={DrawerDefinition as never}
      part="portal"
      element="div"
      renderElement={DrawerPortalElement as never}
      many={false}
      props={props as never}
    />
  );
}

function DrawerBackdropElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type DrawerBackdropProps = SolidPrimitivePartProps<DrawerController['parts']['backdrop'], 'div', false>;
export function DrawerBackdrop(props: DrawerBackdropProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={DrawerDefinition as never}
      part="backdrop"
      element="div"
      renderElement={DrawerBackdropElement as never}
      many={false}
      props={props as never}
    />
  );
}

function DrawerPositionerElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type DrawerPositionerProps = SolidPrimitivePartProps<DrawerController['parts']['positioner'], 'div', false>;
export function DrawerPositioner(props: DrawerPositionerProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={DrawerDefinition as never}
      part="positioner"
      element="div"
      renderElement={DrawerPositionerElement as never}
      many={false}
      props={props as never}
    />
  );
}

function DrawerContentElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type DrawerContentProps = SolidPrimitivePartProps<DrawerController['parts']['content'], 'div', false>;
export function DrawerContent(props: DrawerContentProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={DrawerDefinition as never}
      part="content"
      element="div"
      renderElement={DrawerContentElement as never}
      many={false}
      props={props as never}
    />
  );
}

function DrawerHandleElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type DrawerHandleProps = SolidPrimitivePartProps<DrawerController['parts']['handle'], 'div', false>;
export function DrawerHandle(props: DrawerHandleProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={DrawerDefinition as never}
      part="handle"
      element="div"
      renderElement={DrawerHandleElement as never}
      many={false}
      props={props as never}
    />
  );
}

function DrawerTitleElement(props: JSX.IntrinsicElements['h2']): JSX.Element {
  return <h2 {...props} />;
}

export type DrawerTitleProps = SolidPrimitivePartProps<DrawerController['parts']['title'], 'h2', false>;
export function DrawerTitle(props: DrawerTitleProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={DrawerDefinition as never}
      part="title"
      element="h2"
      renderElement={DrawerTitleElement as never}
      many={false}
      props={props as never}
    />
  );
}

function DrawerDescriptionElement(props: JSX.IntrinsicElements['p']): JSX.Element {
  return <p {...props} />;
}

export type DrawerDescriptionProps = SolidPrimitivePartProps<DrawerController['parts']['description'], 'p', false>;
export function DrawerDescription(props: DrawerDescriptionProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={DrawerDefinition as never}
      part="description"
      element="p"
      renderElement={DrawerDescriptionElement as never}
      many={false}
      props={props as never}
    />
  );
}

function DrawerCloseElement(props: JSX.IntrinsicElements['button']): JSX.Element {
  return <button {...props} />;
}

export type DrawerCloseProps = SolidPrimitivePartProps<DrawerController['parts']['close'], 'button', false>;
export function DrawerClose(props: DrawerCloseProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={DrawerDefinition as never}
      part="close"
      element="button"
      renderElement={DrawerCloseElement as never}
      many={false}
      props={props as never}
    />
  );
}

export const DrawerProvider = DrawerRoot;
export const Drawer = /* @__PURE__ */ Object.assign(DrawerRoot, { Provider: DrawerProvider, Root: DrawerRoot, Trigger: DrawerTrigger, Portal: DrawerPortal, Backdrop: DrawerBackdrop, Positioner: DrawerPositioner, Content: DrawerContent, Handle: DrawerHandle, Title: DrawerTitle, Description: DrawerDescription, Close: DrawerClose });
