// uifn/react/src/generated/input.tsx
'use client';

import * as React from 'react';
import { InputContract, type InputProps, type InputContractParts } from '@uifn/core/primitives/input';
import {
  ReactPrimitivePart,
  ReactPrimitiveRoot,
  useReactPrimitive,
  type ReactPrimitiveBridge,
  type ReactPrimitiveDefinition,
  type ReactPrimitiveHookResult,
  type ReactPrimitivePartProps,
  type ReactPrimitiveRootProps,
} from '../internal/compound';

const InputContext = React.createContext<ReactPrimitiveBridge<InputProps> | null>(null);
const InputDefinition: ReactPrimitiveDefinition<InputProps> = {
  name: 'Input',
  family: 'forms-input',
  kind: 'typed-static-contract',
  rootPart: 'root',
  inputNames: ["type","value","defaultValue","name","disabled","readOnly","required","invalid"],
  context: InputContext,
  contract: InputContract as never,
};

export type InputRootProps = ReactPrimitiveRootProps<InputProps, 'input'>;
export const InputRoot = React.forwardRef<React.ElementRef<'input'>, InputRootProps>((props, ref) => (
  <ReactPrimitiveRoot definition={InputDefinition} element="input" forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
InputRoot.displayName = 'InputRoot';



export const InputProvider = InputRoot;
export function useInput(inputs: InputProps = {} as InputProps): ReactPrimitiveHookResult<ReturnType<typeof InputContract.getState>, Record<string, never>> {
  return useReactPrimitive(InputDefinition, inputs) as ReactPrimitiveHookResult<ReturnType<typeof InputContract.getState>, Record<string, never>>;
}
export const Input = Object.assign(InputRoot, { Provider: InputProvider, Root: InputRoot });

// uifn/solid/src/generated/input.tsx
import { createContext, type JSX } from 'solid-js';
import { InputContract, type InputProps, type InputContractParts } from '@uifn/core/primitives/input';
import {
  createSolidPrimitiveInstanceId,
  SolidPrimitivePart,
  SolidPrimitiveRoot,
  type SolidPrimitiveContextValue,
  type SolidPrimitiveDefinition,
  type SolidPrimitivePartProps,
  type SolidPrimitiveRootProps,
} from '../internal/compound.jsx';

const InputContext = createContext<SolidPrimitiveContextValue<InputProps>>();
export const InputDefinition: SolidPrimitiveDefinition<InputProps> = {
  name: 'Input',
  family: 'forms-input',
  kind: 'typed-static-contract',
  rootPart: 'root',
  inputNames: ["type","value","defaultValue","name","disabled","readOnly","required","invalid"],
  context: InputContext,
  contract: InputContract as never,
};

function InputRootElement(props: JSX.IntrinsicElements['input']): JSX.Element {
  return <input {...props} />;
}

export type InputRootProps = SolidPrimitiveRootProps<InputProps, 'input'>;
export function InputRoot(props: InputRootProps): JSX.Element {
  const hydrationId = createSolidPrimitiveInstanceId();
  return <SolidPrimitiveRoot definition={InputDefinition} element="input" renderElement={InputRootElement as never} hydrationId={hydrationId} props={props as never} />;
}



export const InputProvider = InputRoot;
export const Input = /* @__PURE__ */ Object.assign(InputRoot, { Provider: InputProvider, Root: InputRoot });
