// uifn/react/src/generated/menu.tsx
'use client';

import * as React from 'react';
import { createMenuController, type MenuProps, type MenuController } from '@uifn/core/primitives/menu';
import {
  ReactPrimitivePart,
  ReactPrimitiveRoot,
  useReactPrimitive,
  type ReactPrimitiveBridge,
  type ReactPrimitiveDefinition,
  type ReactPrimitiveHookResult,
  type ReactPrimitivePartProps,
  type ReactPrimitiveRootProps,
} from '../internal/compound';

const MenuContext = React.createContext<ReactPrimitiveBridge<MenuProps> | null>(null);
const MenuDefinition: ReactPrimitiveDefinition<MenuProps> = {
  name: 'Menu',
  family: 'menu-navigation',
  kind: 'interactive-controller',
  rootPart: 'root',
  inputNames: ["open","defaultOpen","orientation","loop","dir"],
  context: MenuContext,
  createController: createMenuController as never,
};

export type MenuRootProps = ReactPrimitiveRootProps<MenuProps, 'div'>;
export const MenuRoot = React.forwardRef<React.ElementRef<'div'>, MenuRootProps>((props, ref) => (
  <ReactPrimitiveRoot definition={MenuDefinition} element="div" forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
MenuRoot.displayName = 'MenuRoot';

export type MenuTriggerProps = ReactPrimitivePartProps<MenuController['parts']['trigger'], 'button', false>;
export const MenuTrigger = React.forwardRef<React.ElementRef<'button'>, MenuTriggerProps>((props, ref) => (
  <ReactPrimitivePart definition={MenuDefinition as never} part="trigger" element="button" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
MenuTrigger.displayName = 'MenuTrigger';

export type MenuPositionerProps = ReactPrimitivePartProps<MenuController['parts']['positioner'], 'div', false>;
export const MenuPositioner = React.forwardRef<React.ElementRef<'div'>, MenuPositionerProps>((props, ref) => (
  <ReactPrimitivePart definition={MenuDefinition as never} part="positioner" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
MenuPositioner.displayName = 'MenuPositioner';

export type MenuContentProps = ReactPrimitivePartProps<MenuController['parts']['content'], 'div', false>;
export const MenuContent = React.forwardRef<React.ElementRef<'div'>, MenuContentProps>((props, ref) => (
  <ReactPrimitivePart definition={MenuDefinition as never} part="content" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
MenuContent.displayName = 'MenuContent';

export type MenuItemProps = ReactPrimitivePartProps<MenuController['parts']['item'], 'div', true>;
export const MenuItem = React.forwardRef<React.ElementRef<'div'>, MenuItemProps>((props, ref) => (
  <ReactPrimitivePart definition={MenuDefinition as never} part="item" element="div" many={true} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
MenuItem.displayName = 'MenuItem';

export type MenuItemIndicatorProps = ReactPrimitivePartProps<MenuController['parts']['itemIndicator'], 'span', true>;
export const MenuItemIndicator = React.forwardRef<React.ElementRef<'span'>, MenuItemIndicatorProps>((props, ref) => (
  <ReactPrimitivePart definition={MenuDefinition as never} part="itemIndicator" element="span" many={true} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
MenuItemIndicator.displayName = 'MenuItemIndicator';

export type MenuSeparatorProps = ReactPrimitivePartProps<MenuController['parts']['separator'], 'div', true>;
export const MenuSeparator = React.forwardRef<React.ElementRef<'div'>, MenuSeparatorProps>((props, ref) => (
  <ReactPrimitivePart definition={MenuDefinition as never} part="separator" element="div" many={true} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
MenuSeparator.displayName = 'MenuSeparator';

export type MenuGroupProps = ReactPrimitivePartProps<MenuController['parts']['group'], 'div', true>;
export const MenuGroup = React.forwardRef<React.ElementRef<'div'>, MenuGroupProps>((props, ref) => (
  <ReactPrimitivePart definition={MenuDefinition as never} part="group" element="div" many={true} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
MenuGroup.displayName = 'MenuGroup';

export type MenuGroupLabelProps = ReactPrimitivePartProps<MenuController['parts']['groupLabel'], 'div', true>;
export const MenuGroupLabel = React.forwardRef<React.ElementRef<'div'>, MenuGroupLabelProps>((props, ref) => (
  <ReactPrimitivePart definition={MenuDefinition as never} part="groupLabel" element="div" many={true} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
MenuGroupLabel.displayName = 'MenuGroupLabel';

export type MenuSubmenuTriggerProps = ReactPrimitivePartProps<MenuController['parts']['submenuTrigger'], 'div', true>;
export const MenuSubmenuTrigger = React.forwardRef<React.ElementRef<'div'>, MenuSubmenuTriggerProps>((props, ref) => (
  <ReactPrimitivePart definition={MenuDefinition as never} part="submenuTrigger" element="div" many={true} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
MenuSubmenuTrigger.displayName = 'MenuSubmenuTrigger';

export type MenuSubmenuContentProps = ReactPrimitivePartProps<MenuController['parts']['submenuContent'], 'div', true>;
export const MenuSubmenuContent = React.forwardRef<React.ElementRef<'div'>, MenuSubmenuContentProps>((props, ref) => (
  <ReactPrimitivePart definition={MenuDefinition as never} part="submenuContent" element="div" many={true} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
MenuSubmenuContent.displayName = 'MenuSubmenuContent';

export const MenuProvider = MenuRoot;
export function useMenu(inputs: MenuProps = {} as MenuProps): ReactPrimitiveHookResult<MenuController['state'], MenuController['actions']> {
  return useReactPrimitive(MenuDefinition, inputs) as ReactPrimitiveHookResult<MenuController['state'], MenuController['actions']>;
}
export const Menu = Object.assign(MenuRoot, { Provider: MenuProvider, Root: MenuRoot, Trigger: MenuTrigger, Positioner: MenuPositioner, Content: MenuContent, Item: MenuItem, ItemIndicator: MenuItemIndicator, Separator: MenuSeparator, Group: MenuGroup, GroupLabel: MenuGroupLabel, SubmenuTrigger: MenuSubmenuTrigger, SubmenuContent: MenuSubmenuContent });

// uifn/solid/src/generated/menu.tsx
import { createContext, type JSX } from 'solid-js';
import { createMenuController, type MenuProps, type MenuController } from '@uifn/core/primitives/menu';
import {
  createSolidPrimitiveInstanceId,
  SolidPrimitivePart,
  SolidPrimitiveRoot,
  type SolidPrimitiveContextValue,
  type SolidPrimitiveDefinition,
  type SolidPrimitivePartProps,
  type SolidPrimitiveRootProps,
} from '../internal/compound.jsx';

const MenuContext = createContext<SolidPrimitiveContextValue<MenuProps>>();
export const MenuDefinition: SolidPrimitiveDefinition<MenuProps> = {
  name: 'Menu',
  family: 'menu-navigation',
  kind: 'interactive-controller',
  rootPart: 'root',
  inputNames: ["open","defaultOpen","orientation","loop","dir"],
  context: MenuContext,
  createController: createMenuController as never,
};

function MenuRootElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type MenuRootProps = SolidPrimitiveRootProps<MenuProps, 'div'>;
export function MenuRoot(props: MenuRootProps): JSX.Element {
  const hydrationId = createSolidPrimitiveInstanceId();
  return <SolidPrimitiveRoot definition={MenuDefinition} element="div" renderElement={MenuRootElement as never} hydrationId={hydrationId} props={props as never} />;
}

function MenuTriggerElement(props: JSX.IntrinsicElements['button']): JSX.Element {
  return <button {...props} />;
}

export type MenuTriggerProps = SolidPrimitivePartProps<MenuController['parts']['trigger'], 'button', false>;
export function MenuTrigger(props: MenuTriggerProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={MenuDefinition as never}
      part="trigger"
      element="button"
      renderElement={MenuTriggerElement as never}
      many={false}
      props={props as never}
    />
  );
}

function MenuPositionerElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type MenuPositionerProps = SolidPrimitivePartProps<MenuController['parts']['positioner'], 'div', false>;
export function MenuPositioner(props: MenuPositionerProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={MenuDefinition as never}
      part="positioner"
      element="div"
      renderElement={MenuPositionerElement as never}
      many={false}
      props={props as never}
    />
  );
}

function MenuContentElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type MenuContentProps = SolidPrimitivePartProps<MenuController['parts']['content'], 'div', false>;
export function MenuContent(props: MenuContentProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={MenuDefinition as never}
      part="content"
      element="div"
      renderElement={MenuContentElement as never}
      many={false}
      props={props as never}
    />
  );
}

function MenuItemElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type MenuItemProps = SolidPrimitivePartProps<MenuController['parts']['item'], 'div', true>;
export function MenuItem(props: MenuItemProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={MenuDefinition as never}
      part="item"
      element="div"
      renderElement={MenuItemElement as never}
      many={true}
      props={props as never}
    />
  );
}

function MenuItemIndicatorElement(props: JSX.IntrinsicElements['span']): JSX.Element {
  return <span {...props} />;
}

export type MenuItemIndicatorProps = SolidPrimitivePartProps<MenuController['parts']['itemIndicator'], 'span', true>;
export function MenuItemIndicator(props: MenuItemIndicatorProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={MenuDefinition as never}
      part="itemIndicator"
      element="span"
      renderElement={MenuItemIndicatorElement as never}
      many={true}
      props={props as never}
    />
  );
}

function MenuSeparatorElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type MenuSeparatorProps = SolidPrimitivePartProps<MenuController['parts']['separator'], 'div', true>;
export function MenuSeparator(props: MenuSeparatorProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={MenuDefinition as never}
      part="separator"
      element="div"
      renderElement={MenuSeparatorElement as never}
      many={true}
      props={props as never}
    />
  );
}

function MenuGroupElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type MenuGroupProps = SolidPrimitivePartProps<MenuController['parts']['group'], 'div', true>;
export function MenuGroup(props: MenuGroupProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={MenuDefinition as never}
      part="group"
      element="div"
      renderElement={MenuGroupElement as never}
      many={true}
      props={props as never}
    />
  );
}

function MenuGroupLabelElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type MenuGroupLabelProps = SolidPrimitivePartProps<MenuController['parts']['groupLabel'], 'div', true>;
export function MenuGroupLabel(props: MenuGroupLabelProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={MenuDefinition as never}
      part="groupLabel"
      element="div"
      renderElement={MenuGroupLabelElement as never}
      many={true}
      props={props as never}
    />
  );
}

function MenuSubmenuTriggerElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type MenuSubmenuTriggerProps = SolidPrimitivePartProps<MenuController['parts']['submenuTrigger'], 'div', true>;
export function MenuSubmenuTrigger(props: MenuSubmenuTriggerProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={MenuDefinition as never}
      part="submenuTrigger"
      element="div"
      renderElement={MenuSubmenuTriggerElement as never}
      many={true}
      props={props as never}
    />
  );
}

function MenuSubmenuContentElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type MenuSubmenuContentProps = SolidPrimitivePartProps<MenuController['parts']['submenuContent'], 'div', true>;
export function MenuSubmenuContent(props: MenuSubmenuContentProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={MenuDefinition as never}
      part="submenuContent"
      element="div"
      renderElement={MenuSubmenuContentElement as never}
      many={true}
      props={props as never}
    />
  );
}

export const MenuProvider = MenuRoot;
export const Menu = /* @__PURE__ */ Object.assign(MenuRoot, { Provider: MenuProvider, Root: MenuRoot, Trigger: MenuTrigger, Positioner: MenuPositioner, Content: MenuContent, Item: MenuItem, ItemIndicator: MenuItemIndicator, Separator: MenuSeparator, Group: MenuGroup, GroupLabel: MenuGroupLabel, SubmenuTrigger: MenuSubmenuTrigger, SubmenuContent: MenuSubmenuContent });
