// uifn/react/src/generated/meter.tsx
'use client';

import * as React from 'react';
import { MeterContract, type MeterProps, type MeterContractParts } from '@uifn/core/primitives/meter';
import {
  ReactPrimitivePart,
  ReactPrimitiveRoot,
  useReactPrimitive,
  type ReactPrimitiveBridge,
  type ReactPrimitiveDefinition,
  type ReactPrimitiveHookResult,
  type ReactPrimitivePartProps,
  type ReactPrimitiveRootProps,
} from '../internal/compound';

const MeterContext = React.createContext<ReactPrimitiveBridge<MeterProps> | null>(null);
const MeterDefinition: ReactPrimitiveDefinition<MeterProps> = {
  name: 'Meter',
  family: 'status-feedback',
  kind: 'typed-static-contract',
  rootPart: 'root',
  inputNames: ["value","min","max","low","high","optimum","formatValue"],
  context: MeterContext,
  contract: MeterContract as never,
};

export type MeterRootProps = ReactPrimitiveRootProps<MeterProps, 'div'>;
export const MeterRoot = React.forwardRef<React.ElementRef<'div'>, MeterRootProps>((props, ref) => (
  <ReactPrimitiveRoot definition={MeterDefinition} element="div" forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
MeterRoot.displayName = 'MeterRoot';

export type MeterLabelProps = ReactPrimitivePartProps<MeterContractParts['label'], 'span', false>;
export const MeterLabel = React.forwardRef<React.ElementRef<'span'>, MeterLabelProps>((props, ref) => (
  <ReactPrimitivePart definition={MeterDefinition as never} part="label" element="span" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
MeterLabel.displayName = 'MeterLabel';

export type MeterTrackProps = ReactPrimitivePartProps<MeterContractParts['track'], 'div', false>;
export const MeterTrack = React.forwardRef<React.ElementRef<'div'>, MeterTrackProps>((props, ref) => (
  <ReactPrimitivePart definition={MeterDefinition as never} part="track" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
MeterTrack.displayName = 'MeterTrack';

export type MeterRangeProps = ReactPrimitivePartProps<MeterContractParts['range'], 'div', false>;
export const MeterRange = React.forwardRef<React.ElementRef<'div'>, MeterRangeProps>((props, ref) => (
  <ReactPrimitivePart definition={MeterDefinition as never} part="range" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
MeterRange.displayName = 'MeterRange';

export type MeterValueTextProps = ReactPrimitivePartProps<MeterContractParts['valueText'], 'span', false>;
export const MeterValueText = React.forwardRef<React.ElementRef<'span'>, MeterValueTextProps>((props, ref) => (
  <ReactPrimitivePart definition={MeterDefinition as never} part="valueText" element="span" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
MeterValueText.displayName = 'MeterValueText';

export const MeterProvider = MeterRoot;
export function useMeter(inputs: MeterProps): ReactPrimitiveHookResult<ReturnType<typeof MeterContract.getState>, Record<string, never>> {
  return useReactPrimitive(MeterDefinition, inputs) as ReactPrimitiveHookResult<ReturnType<typeof MeterContract.getState>, Record<string, never>>;
}
export const Meter = Object.assign(MeterRoot, { Provider: MeterProvider, Root: MeterRoot, Label: MeterLabel, Track: MeterTrack, Range: MeterRange, ValueText: MeterValueText });

// uifn/solid/src/generated/meter.tsx
import { createContext, type JSX } from 'solid-js';
import { MeterContract, type MeterProps, type MeterContractParts } from '@uifn/core/primitives/meter';
import {
  createSolidPrimitiveInstanceId,
  SolidPrimitivePart,
  SolidPrimitiveRoot,
  type SolidPrimitiveContextValue,
  type SolidPrimitiveDefinition,
  type SolidPrimitivePartProps,
  type SolidPrimitiveRootProps,
} from '../internal/compound.jsx';

const MeterContext = createContext<SolidPrimitiveContextValue<MeterProps>>();
export const MeterDefinition: SolidPrimitiveDefinition<MeterProps> = {
  name: 'Meter',
  family: 'status-feedback',
  kind: 'typed-static-contract',
  rootPart: 'root',
  inputNames: ["value","min","max","low","high","optimum","formatValue"],
  context: MeterContext,
  contract: MeterContract as never,
};

function MeterRootElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type MeterRootProps = SolidPrimitiveRootProps<MeterProps, 'div'>;
export function MeterRoot(props: MeterRootProps): JSX.Element {
  const hydrationId = createSolidPrimitiveInstanceId();
  return <SolidPrimitiveRoot definition={MeterDefinition} element="div" renderElement={MeterRootElement as never} hydrationId={hydrationId} props={props as never} />;
}

function MeterLabelElement(props: JSX.IntrinsicElements['span']): JSX.Element {
  return <span {...props} />;
}

export type MeterLabelProps = SolidPrimitivePartProps<MeterContractParts['label'], 'span', false>;
export function MeterLabel(props: MeterLabelProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={MeterDefinition as never}
      part="label"
      element="span"
      renderElement={MeterLabelElement as never}
      many={false}
      props={props as never}
    />
  );
}

function MeterTrackElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type MeterTrackProps = SolidPrimitivePartProps<MeterContractParts['track'], 'div', false>;
export function MeterTrack(props: MeterTrackProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={MeterDefinition as never}
      part="track"
      element="div"
      renderElement={MeterTrackElement as never}
      many={false}
      props={props as never}
    />
  );
}

function MeterRangeElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type MeterRangeProps = SolidPrimitivePartProps<MeterContractParts['range'], 'div', false>;
export function MeterRange(props: MeterRangeProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={MeterDefinition as never}
      part="range"
      element="div"
      renderElement={MeterRangeElement as never}
      many={false}
      props={props as never}
    />
  );
}

function MeterValueTextElement(props: JSX.IntrinsicElements['span']): JSX.Element {
  return <span {...props} />;
}

export type MeterValueTextProps = SolidPrimitivePartProps<MeterContractParts['valueText'], 'span', false>;
export function MeterValueText(props: MeterValueTextProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={MeterDefinition as never}
      part="valueText"
      element="span"
      renderElement={MeterValueTextElement as never}
      many={false}
      props={props as never}
    />
  );
}

export const MeterProvider = MeterRoot;
export const Meter = /* @__PURE__ */ Object.assign(MeterRoot, { Provider: MeterProvider, Root: MeterRoot, Label: MeterLabel, Track: MeterTrack, Range: MeterRange, ValueText: MeterValueText });
