// uifn/react/src/generated/navigation-menu.tsx
'use client';

import * as React from 'react';
import { createNavigationMenuController, type NavigationMenuProps, type NavigationMenuController } from '@uifn/core/primitives/navigation-menu';
import {
  ReactPrimitivePart,
  ReactPrimitiveRoot,
  useReactPrimitive,
  type ReactPrimitiveBridge,
  type ReactPrimitiveDefinition,
  type ReactPrimitiveHookResult,
  type ReactPrimitivePartProps,
  type ReactPrimitiveRootProps,
} from '../internal/compound';

const NavigationMenuContext = React.createContext<ReactPrimitiveBridge<NavigationMenuProps> | null>(null);
const NavigationMenuDefinition: ReactPrimitiveDefinition<NavigationMenuProps> = {
  name: 'NavigationMenu',
  family: 'menu-navigation',
  kind: 'interactive-controller',
  rootPart: 'root',
  inputNames: ["value","defaultValue","orientation","delayDuration","skipDelayDuration","dir"],
  context: NavigationMenuContext,
  createController: createNavigationMenuController as never,
};

export type NavigationMenuRootProps = ReactPrimitiveRootProps<NavigationMenuProps, 'nav'>;
export const NavigationMenuRoot = React.forwardRef<React.ElementRef<'nav'>, NavigationMenuRootProps>((props, ref) => (
  <ReactPrimitiveRoot definition={NavigationMenuDefinition} element="nav" forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
NavigationMenuRoot.displayName = 'NavigationMenuRoot';

export type NavigationMenuListProps = ReactPrimitivePartProps<NavigationMenuController['parts']['list'], 'ul', false>;
export const NavigationMenuList = React.forwardRef<React.ElementRef<'ul'>, NavigationMenuListProps>((props, ref) => (
  <ReactPrimitivePart definition={NavigationMenuDefinition as never} part="list" element="ul" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
NavigationMenuList.displayName = 'NavigationMenuList';

export type NavigationMenuItemProps = ReactPrimitivePartProps<NavigationMenuController['parts']['item'], 'li', true>;
export const NavigationMenuItem = React.forwardRef<React.ElementRef<'li'>, NavigationMenuItemProps>((props, ref) => (
  <ReactPrimitivePart definition={NavigationMenuDefinition as never} part="item" element="li" many={true} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
NavigationMenuItem.displayName = 'NavigationMenuItem';

export type NavigationMenuTriggerProps = ReactPrimitivePartProps<NavigationMenuController['parts']['trigger'], 'button', true>;
export const NavigationMenuTrigger = React.forwardRef<React.ElementRef<'button'>, NavigationMenuTriggerProps>((props, ref) => (
  <ReactPrimitivePart definition={NavigationMenuDefinition as never} part="trigger" element="button" many={true} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
NavigationMenuTrigger.displayName = 'NavigationMenuTrigger';

export type NavigationMenuContentProps = ReactPrimitivePartProps<NavigationMenuController['parts']['content'], 'div', true>;
export const NavigationMenuContent = React.forwardRef<React.ElementRef<'div'>, NavigationMenuContentProps>((props, ref) => (
  <ReactPrimitivePart definition={NavigationMenuDefinition as never} part="content" element="div" many={true} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
NavigationMenuContent.displayName = 'NavigationMenuContent';

export type NavigationMenuLinkProps = ReactPrimitivePartProps<NavigationMenuController['parts']['link'], 'a', true>;
export const NavigationMenuLink = React.forwardRef<React.ElementRef<'a'>, NavigationMenuLinkProps>((props, ref) => (
  <ReactPrimitivePart definition={NavigationMenuDefinition as never} part="link" element="a" many={true} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
NavigationMenuLink.displayName = 'NavigationMenuLink';

export type NavigationMenuViewportProps = ReactPrimitivePartProps<NavigationMenuController['parts']['viewport'], 'div', false>;
export const NavigationMenuViewport = React.forwardRef<React.ElementRef<'div'>, NavigationMenuViewportProps>((props, ref) => (
  <ReactPrimitivePart definition={NavigationMenuDefinition as never} part="viewport" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
NavigationMenuViewport.displayName = 'NavigationMenuViewport';

export type NavigationMenuIndicatorProps = ReactPrimitivePartProps<NavigationMenuController['parts']['indicator'], 'div', false>;
export const NavigationMenuIndicator = React.forwardRef<React.ElementRef<'div'>, NavigationMenuIndicatorProps>((props, ref) => (
  <ReactPrimitivePart definition={NavigationMenuDefinition as never} part="indicator" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
NavigationMenuIndicator.displayName = 'NavigationMenuIndicator';

export const NavigationMenuProvider = NavigationMenuRoot;
export function useNavigationMenu(inputs: NavigationMenuProps = {} as NavigationMenuProps): ReactPrimitiveHookResult<NavigationMenuController['state'], NavigationMenuController['actions']> {
  return useReactPrimitive(NavigationMenuDefinition, inputs) as ReactPrimitiveHookResult<NavigationMenuController['state'], NavigationMenuController['actions']>;
}
export const NavigationMenu = Object.assign(NavigationMenuRoot, { Provider: NavigationMenuProvider, Root: NavigationMenuRoot, List: NavigationMenuList, Item: NavigationMenuItem, Trigger: NavigationMenuTrigger, Content: NavigationMenuContent, Link: NavigationMenuLink, Viewport: NavigationMenuViewport, Indicator: NavigationMenuIndicator });

// uifn/solid/src/generated/navigation-menu.tsx
import { createContext, type JSX } from 'solid-js';
import { createNavigationMenuController, type NavigationMenuProps, type NavigationMenuController } from '@uifn/core/primitives/navigation-menu';
import {
  createSolidPrimitiveInstanceId,
  SolidPrimitivePart,
  SolidPrimitiveRoot,
  type SolidPrimitiveContextValue,
  type SolidPrimitiveDefinition,
  type SolidPrimitivePartProps,
  type SolidPrimitiveRootProps,
} from '../internal/compound.jsx';

const NavigationMenuContext = createContext<SolidPrimitiveContextValue<NavigationMenuProps>>();
export const NavigationMenuDefinition: SolidPrimitiveDefinition<NavigationMenuProps> = {
  name: 'NavigationMenu',
  family: 'menu-navigation',
  kind: 'interactive-controller',
  rootPart: 'root',
  inputNames: ["value","defaultValue","orientation","delayDuration","skipDelayDuration","dir"],
  context: NavigationMenuContext,
  createController: createNavigationMenuController as never,
};

function NavigationMenuRootElement(props: JSX.IntrinsicElements['nav']): JSX.Element {
  return <nav {...props} />;
}

export type NavigationMenuRootProps = SolidPrimitiveRootProps<NavigationMenuProps, 'nav'>;
export function NavigationMenuRoot(props: NavigationMenuRootProps): JSX.Element {
  const hydrationId = createSolidPrimitiveInstanceId();
  return <SolidPrimitiveRoot definition={NavigationMenuDefinition} element="nav" renderElement={NavigationMenuRootElement as never} hydrationId={hydrationId} props={props as never} />;
}

function NavigationMenuListElement(props: JSX.IntrinsicElements['ul']): JSX.Element {
  return <ul {...props} />;
}

export type NavigationMenuListProps = SolidPrimitivePartProps<NavigationMenuController['parts']['list'], 'ul', false>;
export function NavigationMenuList(props: NavigationMenuListProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={NavigationMenuDefinition as never}
      part="list"
      element="ul"
      renderElement={NavigationMenuListElement as never}
      many={false}
      props={props as never}
    />
  );
}

function NavigationMenuItemElement(props: JSX.IntrinsicElements['li']): JSX.Element {
  return <li {...props} />;
}

export type NavigationMenuItemProps = SolidPrimitivePartProps<NavigationMenuController['parts']['item'], 'li', true>;
export function NavigationMenuItem(props: NavigationMenuItemProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={NavigationMenuDefinition as never}
      part="item"
      element="li"
      renderElement={NavigationMenuItemElement as never}
      many={true}
      props={props as never}
    />
  );
}

function NavigationMenuTriggerElement(props: JSX.IntrinsicElements['button']): JSX.Element {
  return <button {...props} />;
}

export type NavigationMenuTriggerProps = SolidPrimitivePartProps<NavigationMenuController['parts']['trigger'], 'button', true>;
export function NavigationMenuTrigger(props: NavigationMenuTriggerProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={NavigationMenuDefinition as never}
      part="trigger"
      element="button"
      renderElement={NavigationMenuTriggerElement as never}
      many={true}
      props={props as never}
    />
  );
}

function NavigationMenuContentElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type NavigationMenuContentProps = SolidPrimitivePartProps<NavigationMenuController['parts']['content'], 'div', true>;
export function NavigationMenuContent(props: NavigationMenuContentProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={NavigationMenuDefinition as never}
      part="content"
      element="div"
      renderElement={NavigationMenuContentElement as never}
      many={true}
      props={props as never}
    />
  );
}

function NavigationMenuLinkElement(props: JSX.IntrinsicElements['a']): JSX.Element {
  return <a {...props} />;
}

export type NavigationMenuLinkProps = SolidPrimitivePartProps<NavigationMenuController['parts']['link'], 'a', true>;
export function NavigationMenuLink(props: NavigationMenuLinkProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={NavigationMenuDefinition as never}
      part="link"
      element="a"
      renderElement={NavigationMenuLinkElement as never}
      many={true}
      props={props as never}
    />
  );
}

function NavigationMenuViewportElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type NavigationMenuViewportProps = SolidPrimitivePartProps<NavigationMenuController['parts']['viewport'], 'div', false>;
export function NavigationMenuViewport(props: NavigationMenuViewportProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={NavigationMenuDefinition as never}
      part="viewport"
      element="div"
      renderElement={NavigationMenuViewportElement as never}
      many={false}
      props={props as never}
    />
  );
}

function NavigationMenuIndicatorElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type NavigationMenuIndicatorProps = SolidPrimitivePartProps<NavigationMenuController['parts']['indicator'], 'div', false>;
export function NavigationMenuIndicator(props: NavigationMenuIndicatorProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={NavigationMenuDefinition as never}
      part="indicator"
      element="div"
      renderElement={NavigationMenuIndicatorElement as never}
      many={false}
      props={props as never}
    />
  );
}

export const NavigationMenuProvider = NavigationMenuRoot;
export const NavigationMenu = /* @__PURE__ */ Object.assign(NavigationMenuRoot, { Provider: NavigationMenuProvider, Root: NavigationMenuRoot, List: NavigationMenuList, Item: NavigationMenuItem, Trigger: NavigationMenuTrigger, Content: NavigationMenuContent, Link: NavigationMenuLink, Viewport: NavigationMenuViewport, Indicator: NavigationMenuIndicator });
