// uifn/react/src/generated/number-input.tsx
'use client';

import * as React from 'react';
import { createNumberInputController, type NumberInputProps, type NumberInputController } from '@uifn/core/primitives/number-input';
import {
  ReactPrimitivePart,
  ReactPrimitiveRoot,
  useReactPrimitive,
  type ReactPrimitiveBridge,
  type ReactPrimitiveDefinition,
  type ReactPrimitiveHookResult,
  type ReactPrimitivePartProps,
  type ReactPrimitiveRootProps,
} from '../internal/compound';

const NumberInputContext = React.createContext<ReactPrimitiveBridge<NumberInputProps> | null>(null);
const NumberInputDefinition: ReactPrimitiveDefinition<NumberInputProps> = {
  name: 'NumberInput',
  family: 'forms-input',
  kind: 'interactive-controller',
  rootPart: 'root',
  inputNames: ["value","defaultValue","min","max","step","locale","name","disabled","readOnly","required"],
  context: NumberInputContext,
  createController: createNumberInputController as never,
};

export type NumberInputRootProps = ReactPrimitiveRootProps<NumberInputProps, 'div'>;
export const NumberInputRoot = React.forwardRef<React.ElementRef<'div'>, NumberInputRootProps>((props, ref) => (
  <ReactPrimitiveRoot definition={NumberInputDefinition} element="div" forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
NumberInputRoot.displayName = 'NumberInputRoot';

export type NumberInputLabelProps = ReactPrimitivePartProps<NumberInputController['parts']['label'], 'label', false>;
export const NumberInputLabel = React.forwardRef<React.ElementRef<'label'>, NumberInputLabelProps>((props, ref) => (
  <ReactPrimitivePart definition={NumberInputDefinition as never} part="label" element="label" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
NumberInputLabel.displayName = 'NumberInputLabel';

export type NumberInputControlProps = ReactPrimitivePartProps<NumberInputController['parts']['control'], 'div', false>;
export const NumberInputControl = React.forwardRef<React.ElementRef<'div'>, NumberInputControlProps>((props, ref) => (
  <ReactPrimitivePart definition={NumberInputDefinition as never} part="control" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
NumberInputControl.displayName = 'NumberInputControl';

export type NumberInputInputProps = ReactPrimitivePartProps<NumberInputController['parts']['input'], 'input', false>;
export const NumberInputInput = React.forwardRef<React.ElementRef<'input'>, NumberInputInputProps>((props, ref) => (
  <ReactPrimitivePart definition={NumberInputDefinition as never} part="input" element="input" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
NumberInputInput.displayName = 'NumberInputInput';

export type NumberInputIncrementProps = ReactPrimitivePartProps<NumberInputController['parts']['increment'], 'button', false>;
export const NumberInputIncrement = React.forwardRef<React.ElementRef<'button'>, NumberInputIncrementProps>((props, ref) => (
  <ReactPrimitivePart definition={NumberInputDefinition as never} part="increment" element="button" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
NumberInputIncrement.displayName = 'NumberInputIncrement';

export type NumberInputDecrementProps = ReactPrimitivePartProps<NumberInputController['parts']['decrement'], 'button', false>;
export const NumberInputDecrement = React.forwardRef<React.ElementRef<'button'>, NumberInputDecrementProps>((props, ref) => (
  <ReactPrimitivePart definition={NumberInputDefinition as never} part="decrement" element="button" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
NumberInputDecrement.displayName = 'NumberInputDecrement';

export type NumberInputScrubberProps = ReactPrimitivePartProps<NumberInputController['parts']['scrubber'], 'div', false>;
export const NumberInputScrubber = React.forwardRef<React.ElementRef<'div'>, NumberInputScrubberProps>((props, ref) => (
  <ReactPrimitivePart definition={NumberInputDefinition as never} part="scrubber" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
NumberInputScrubber.displayName = 'NumberInputScrubber';

export type NumberInputHiddenInputProps = ReactPrimitivePartProps<NumberInputController['parts']['hiddenInput'], 'input', false>;
export const NumberInputHiddenInput = React.forwardRef<React.ElementRef<'input'>, NumberInputHiddenInputProps>((props, ref) => (
  <ReactPrimitivePart definition={NumberInputDefinition as never} part="hiddenInput" element="input" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
NumberInputHiddenInput.displayName = 'NumberInputHiddenInput';

export type NumberInputErrorProps = ReactPrimitivePartProps<NumberInputController['parts']['error'], 'div', false>;
export const NumberInputError = React.forwardRef<React.ElementRef<'div'>, NumberInputErrorProps>((props, ref) => (
  <ReactPrimitivePart definition={NumberInputDefinition as never} part="error" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
NumberInputError.displayName = 'NumberInputError';

export const NumberInputProvider = NumberInputRoot;
export function useNumberInput(inputs: NumberInputProps = {} as NumberInputProps): ReactPrimitiveHookResult<NumberInputController['state'], NumberInputController['actions']> {
  return useReactPrimitive(NumberInputDefinition, inputs) as ReactPrimitiveHookResult<NumberInputController['state'], NumberInputController['actions']>;
}
export const NumberInput = Object.assign(NumberInputRoot, { Provider: NumberInputProvider, Root: NumberInputRoot, Label: NumberInputLabel, Control: NumberInputControl, Input: NumberInputInput, Increment: NumberInputIncrement, Decrement: NumberInputDecrement, Scrubber: NumberInputScrubber, HiddenInput: NumberInputHiddenInput, Error: NumberInputError });

// uifn/solid/src/generated/number-input.tsx
import { createContext, type JSX } from 'solid-js';
import { createNumberInputController, type NumberInputProps, type NumberInputController } from '@uifn/core/primitives/number-input';
import {
  createSolidPrimitiveInstanceId,
  SolidPrimitivePart,
  SolidPrimitiveRoot,
  type SolidPrimitiveContextValue,
  type SolidPrimitiveDefinition,
  type SolidPrimitivePartProps,
  type SolidPrimitiveRootProps,
} from '../internal/compound.jsx';

const NumberInputContext = createContext<SolidPrimitiveContextValue<NumberInputProps>>();
export const NumberInputDefinition: SolidPrimitiveDefinition<NumberInputProps> = {
  name: 'NumberInput',
  family: 'forms-input',
  kind: 'interactive-controller',
  rootPart: 'root',
  inputNames: ["value","defaultValue","min","max","step","locale","name","disabled","readOnly","required"],
  context: NumberInputContext,
  createController: createNumberInputController as never,
};

function NumberInputRootElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type NumberInputRootProps = SolidPrimitiveRootProps<NumberInputProps, 'div'>;
export function NumberInputRoot(props: NumberInputRootProps): JSX.Element {
  const hydrationId = createSolidPrimitiveInstanceId();
  return <SolidPrimitiveRoot definition={NumberInputDefinition} element="div" renderElement={NumberInputRootElement as never} hydrationId={hydrationId} props={props as never} />;
}

function NumberInputLabelElement(props: JSX.IntrinsicElements['label']): JSX.Element {
  return <label {...props} />;
}

export type NumberInputLabelProps = SolidPrimitivePartProps<NumberInputController['parts']['label'], 'label', false>;
export function NumberInputLabel(props: NumberInputLabelProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={NumberInputDefinition as never}
      part="label"
      element="label"
      renderElement={NumberInputLabelElement as never}
      many={false}
      props={props as never}
    />
  );
}

function NumberInputControlElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type NumberInputControlProps = SolidPrimitivePartProps<NumberInputController['parts']['control'], 'div', false>;
export function NumberInputControl(props: NumberInputControlProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={NumberInputDefinition as never}
      part="control"
      element="div"
      renderElement={NumberInputControlElement as never}
      many={false}
      props={props as never}
    />
  );
}

function NumberInputInputElement(props: JSX.IntrinsicElements['input']): JSX.Element {
  return <input {...props} />;
}

export type NumberInputInputProps = SolidPrimitivePartProps<NumberInputController['parts']['input'], 'input', false>;
export function NumberInputInput(props: NumberInputInputProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={NumberInputDefinition as never}
      part="input"
      element="input"
      renderElement={NumberInputInputElement as never}
      many={false}
      props={props as never}
    />
  );
}

function NumberInputIncrementElement(props: JSX.IntrinsicElements['button']): JSX.Element {
  return <button {...props} />;
}

export type NumberInputIncrementProps = SolidPrimitivePartProps<NumberInputController['parts']['increment'], 'button', false>;
export function NumberInputIncrement(props: NumberInputIncrementProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={NumberInputDefinition as never}
      part="increment"
      element="button"
      renderElement={NumberInputIncrementElement as never}
      many={false}
      props={props as never}
    />
  );
}

function NumberInputDecrementElement(props: JSX.IntrinsicElements['button']): JSX.Element {
  return <button {...props} />;
}

export type NumberInputDecrementProps = SolidPrimitivePartProps<NumberInputController['parts']['decrement'], 'button', false>;
export function NumberInputDecrement(props: NumberInputDecrementProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={NumberInputDefinition as never}
      part="decrement"
      element="button"
      renderElement={NumberInputDecrementElement as never}
      many={false}
      props={props as never}
    />
  );
}

function NumberInputScrubberElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type NumberInputScrubberProps = SolidPrimitivePartProps<NumberInputController['parts']['scrubber'], 'div', false>;
export function NumberInputScrubber(props: NumberInputScrubberProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={NumberInputDefinition as never}
      part="scrubber"
      element="div"
      renderElement={NumberInputScrubberElement as never}
      many={false}
      props={props as never}
    />
  );
}

function NumberInputHiddenInputElement(props: JSX.IntrinsicElements['input']): JSX.Element {
  return <input {...props} />;
}

export type NumberInputHiddenInputProps = SolidPrimitivePartProps<NumberInputController['parts']['hiddenInput'], 'input', false>;
export function NumberInputHiddenInput(props: NumberInputHiddenInputProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={NumberInputDefinition as never}
      part="hiddenInput"
      element="input"
      renderElement={NumberInputHiddenInputElement as never}
      many={false}
      props={props as never}
    />
  );
}

function NumberInputErrorElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type NumberInputErrorProps = SolidPrimitivePartProps<NumberInputController['parts']['error'], 'div', false>;
export function NumberInputError(props: NumberInputErrorProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={NumberInputDefinition as never}
      part="error"
      element="div"
      renderElement={NumberInputErrorElement as never}
      many={false}
      props={props as never}
    />
  );
}

export const NumberInputProvider = NumberInputRoot;
export const NumberInput = /* @__PURE__ */ Object.assign(NumberInputRoot, { Provider: NumberInputProvider, Root: NumberInputRoot, Label: NumberInputLabel, Control: NumberInputControl, Input: NumberInputInput, Increment: NumberInputIncrement, Decrement: NumberInputDecrement, Scrubber: NumberInputScrubber, HiddenInput: NumberInputHiddenInput, Error: NumberInputError });
