// uifn/react/src/generated/progress.tsx
'use client';

import * as React from 'react';
import { ProgressContract, type ProgressProps, type ProgressContractParts } from '@uifn/core/primitives/progress';
import {
  ReactPrimitivePart,
  ReactPrimitiveRoot,
  useReactPrimitive,
  type ReactPrimitiveBridge,
  type ReactPrimitiveDefinition,
  type ReactPrimitiveHookResult,
  type ReactPrimitivePartProps,
  type ReactPrimitiveRootProps,
} from '../internal/compound';

const ProgressContext = React.createContext<ReactPrimitiveBridge<ProgressProps> | null>(null);
const ProgressDefinition: ReactPrimitiveDefinition<ProgressProps> = {
  name: 'Progress',
  family: 'status-feedback',
  kind: 'typed-static-contract',
  rootPart: 'root',
  inputNames: ["value","min","max","indeterminate","formatValue"],
  context: ProgressContext,
  contract: ProgressContract as never,
};

export type ProgressRootProps = ReactPrimitiveRootProps<ProgressProps, 'div'>;
export const ProgressRoot = React.forwardRef<React.ElementRef<'div'>, ProgressRootProps>((props, ref) => (
  <ReactPrimitiveRoot definition={ProgressDefinition} element="div" forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
ProgressRoot.displayName = 'ProgressRoot';

export type ProgressLabelProps = ReactPrimitivePartProps<ProgressContractParts['label'], 'span', false>;
export const ProgressLabel = React.forwardRef<React.ElementRef<'span'>, ProgressLabelProps>((props, ref) => (
  <ReactPrimitivePart definition={ProgressDefinition as never} part="label" element="span" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
ProgressLabel.displayName = 'ProgressLabel';

export type ProgressTrackProps = ReactPrimitivePartProps<ProgressContractParts['track'], 'div', false>;
export const ProgressTrack = React.forwardRef<React.ElementRef<'div'>, ProgressTrackProps>((props, ref) => (
  <ReactPrimitivePart definition={ProgressDefinition as never} part="track" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
ProgressTrack.displayName = 'ProgressTrack';

export type ProgressRangeProps = ReactPrimitivePartProps<ProgressContractParts['range'], 'div', false>;
export const ProgressRange = React.forwardRef<React.ElementRef<'div'>, ProgressRangeProps>((props, ref) => (
  <ReactPrimitivePart definition={ProgressDefinition as never} part="range" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
ProgressRange.displayName = 'ProgressRange';

export type ProgressCircleProps = ReactPrimitivePartProps<ProgressContractParts['circle'], 'svg', false>;
export const ProgressCircle = React.forwardRef<React.ElementRef<'svg'>, ProgressCircleProps>((props, ref) => (
  <ReactPrimitivePart definition={ProgressDefinition as never} part="circle" element="svg" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
ProgressCircle.displayName = 'ProgressCircle';

export type ProgressValueTextProps = ReactPrimitivePartProps<ProgressContractParts['valueText'], 'span', false>;
export const ProgressValueText = React.forwardRef<React.ElementRef<'span'>, ProgressValueTextProps>((props, ref) => (
  <ReactPrimitivePart definition={ProgressDefinition as never} part="valueText" element="span" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
ProgressValueText.displayName = 'ProgressValueText';

export const ProgressProvider = ProgressRoot;
export function useProgress(inputs: ProgressProps = {} as ProgressProps): ReactPrimitiveHookResult<ReturnType<typeof ProgressContract.getState>, Record<string, never>> {
  return useReactPrimitive(ProgressDefinition, inputs) as ReactPrimitiveHookResult<ReturnType<typeof ProgressContract.getState>, Record<string, never>>;
}
export const Progress = Object.assign(ProgressRoot, { Provider: ProgressProvider, Root: ProgressRoot, Label: ProgressLabel, Track: ProgressTrack, Range: ProgressRange, Circle: ProgressCircle, ValueText: ProgressValueText });

// uifn/solid/src/generated/progress.tsx
import { createContext, type JSX } from 'solid-js';
import { ProgressContract, type ProgressProps, type ProgressContractParts } from '@uifn/core/primitives/progress';
import {
  createSolidPrimitiveInstanceId,
  SolidPrimitivePart,
  SolidPrimitiveRoot,
  type SolidPrimitiveContextValue,
  type SolidPrimitiveDefinition,
  type SolidPrimitivePartProps,
  type SolidPrimitiveRootProps,
} from '../internal/compound.jsx';

const ProgressContext = createContext<SolidPrimitiveContextValue<ProgressProps>>();
export const ProgressDefinition: SolidPrimitiveDefinition<ProgressProps> = {
  name: 'Progress',
  family: 'status-feedback',
  kind: 'typed-static-contract',
  rootPart: 'root',
  inputNames: ["value","min","max","indeterminate","formatValue"],
  context: ProgressContext,
  contract: ProgressContract as never,
};

function ProgressRootElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type ProgressRootProps = SolidPrimitiveRootProps<ProgressProps, 'div'>;
export function ProgressRoot(props: ProgressRootProps): JSX.Element {
  const hydrationId = createSolidPrimitiveInstanceId();
  return <SolidPrimitiveRoot definition={ProgressDefinition} element="div" renderElement={ProgressRootElement as never} hydrationId={hydrationId} props={props as never} />;
}

function ProgressLabelElement(props: JSX.IntrinsicElements['span']): JSX.Element {
  return <span {...props} />;
}

export type ProgressLabelProps = SolidPrimitivePartProps<ProgressContractParts['label'], 'span', false>;
export function ProgressLabel(props: ProgressLabelProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={ProgressDefinition as never}
      part="label"
      element="span"
      renderElement={ProgressLabelElement as never}
      many={false}
      props={props as never}
    />
  );
}

function ProgressTrackElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type ProgressTrackProps = SolidPrimitivePartProps<ProgressContractParts['track'], 'div', false>;
export function ProgressTrack(props: ProgressTrackProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={ProgressDefinition as never}
      part="track"
      element="div"
      renderElement={ProgressTrackElement as never}
      many={false}
      props={props as never}
    />
  );
}

function ProgressRangeElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type ProgressRangeProps = SolidPrimitivePartProps<ProgressContractParts['range'], 'div', false>;
export function ProgressRange(props: ProgressRangeProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={ProgressDefinition as never}
      part="range"
      element="div"
      renderElement={ProgressRangeElement as never}
      many={false}
      props={props as never}
    />
  );
}

function ProgressCircleElement(props: JSX.IntrinsicElements['svg']): JSX.Element {
  return <svg {...props} />;
}

export type ProgressCircleProps = SolidPrimitivePartProps<ProgressContractParts['circle'], 'svg', false>;
export function ProgressCircle(props: ProgressCircleProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={ProgressDefinition as never}
      part="circle"
      element="svg"
      renderElement={ProgressCircleElement as never}
      many={false}
      props={props as never}
    />
  );
}

function ProgressValueTextElement(props: JSX.IntrinsicElements['span']): JSX.Element {
  return <span {...props} />;
}

export type ProgressValueTextProps = SolidPrimitivePartProps<ProgressContractParts['valueText'], 'span', false>;
export function ProgressValueText(props: ProgressValueTextProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={ProgressDefinition as never}
      part="valueText"
      element="span"
      renderElement={ProgressValueTextElement as never}
      many={false}
      props={props as never}
    />
  );
}

export const ProgressProvider = ProgressRoot;
export const Progress = /* @__PURE__ */ Object.assign(ProgressRoot, { Provider: ProgressProvider, Root: ProgressRoot, Label: ProgressLabel, Track: ProgressTrack, Range: ProgressRange, Circle: ProgressCircle, ValueText: ProgressValueText });
