// uifn/react/src/generated/radio-group.tsx
'use client';

import * as React from 'react';
import { createRadioGroupController, type RadioGroupProps, type RadioGroupController } from '@uifn/core/primitives/radio-group';
import {
  ReactPrimitivePart,
  ReactPrimitiveRoot,
  useReactPrimitive,
  type ReactPrimitiveBridge,
  type ReactPrimitiveDefinition,
  type ReactPrimitiveHookResult,
  type ReactPrimitivePartProps,
  type ReactPrimitiveRootProps,
} from '../internal/compound';

const RadioGroupContext = React.createContext<ReactPrimitiveBridge<RadioGroupProps> | null>(null);
const RadioGroupDefinition: ReactPrimitiveDefinition<RadioGroupProps> = {
  name: 'RadioGroup',
  family: 'selection-collection',
  kind: 'interactive-controller',
  rootPart: 'root',
  inputNames: ["value","defaultValue","name","orientation","loop","disabled","readOnly","required"],
  context: RadioGroupContext,
  createController: createRadioGroupController as never,
};

export type RadioGroupRootProps = ReactPrimitiveRootProps<RadioGroupProps, 'fieldset'>;
export const RadioGroupRoot = React.forwardRef<React.ElementRef<'fieldset'>, RadioGroupRootProps>((props, ref) => (
  <ReactPrimitiveRoot definition={RadioGroupDefinition} element="fieldset" forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
RadioGroupRoot.displayName = 'RadioGroupRoot';

export type RadioGroupLabelProps = ReactPrimitivePartProps<RadioGroupController['parts']['label'], 'legend', false>;
export const RadioGroupLabel = React.forwardRef<React.ElementRef<'legend'>, RadioGroupLabelProps>((props, ref) => (
  <ReactPrimitivePart definition={RadioGroupDefinition as never} part="label" element="legend" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
RadioGroupLabel.displayName = 'RadioGroupLabel';

export type RadioGroupItemProps = ReactPrimitivePartProps<RadioGroupController['parts']['item'], 'label', true>;
export const RadioGroupItem = React.forwardRef<React.ElementRef<'label'>, RadioGroupItemProps>((props, ref) => (
  <ReactPrimitivePart definition={RadioGroupDefinition as never} part="item" element="label" many={true} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
RadioGroupItem.displayName = 'RadioGroupItem';

export type RadioGroupItemControlProps = ReactPrimitivePartProps<RadioGroupController['parts']['itemControl'], 'button', true>;
export const RadioGroupItemControl = React.forwardRef<React.ElementRef<'button'>, RadioGroupItemControlProps>((props, ref) => (
  <ReactPrimitivePart definition={RadioGroupDefinition as never} part="itemControl" element="button" many={true} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
RadioGroupItemControl.displayName = 'RadioGroupItemControl';

export type RadioGroupItemIndicatorProps = ReactPrimitivePartProps<RadioGroupController['parts']['itemIndicator'], 'span', true>;
export const RadioGroupItemIndicator = React.forwardRef<React.ElementRef<'span'>, RadioGroupItemIndicatorProps>((props, ref) => (
  <ReactPrimitivePart definition={RadioGroupDefinition as never} part="itemIndicator" element="span" many={true} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
RadioGroupItemIndicator.displayName = 'RadioGroupItemIndicator';

export type RadioGroupHiddenInputProps = ReactPrimitivePartProps<RadioGroupController['parts']['hiddenInput'], 'input', true>;
export const RadioGroupHiddenInput = React.forwardRef<React.ElementRef<'input'>, RadioGroupHiddenInputProps>((props, ref) => (
  <ReactPrimitivePart definition={RadioGroupDefinition as never} part="hiddenInput" element="input" many={true} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
RadioGroupHiddenInput.displayName = 'RadioGroupHiddenInput';

export type RadioGroupErrorProps = ReactPrimitivePartProps<RadioGroupController['parts']['error'], 'div', false>;
export const RadioGroupError = React.forwardRef<React.ElementRef<'div'>, RadioGroupErrorProps>((props, ref) => (
  <ReactPrimitivePart definition={RadioGroupDefinition as never} part="error" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
RadioGroupError.displayName = 'RadioGroupError';

export const RadioGroupProvider = RadioGroupRoot;
export function useRadioGroup(inputs: RadioGroupProps = {} as RadioGroupProps): ReactPrimitiveHookResult<RadioGroupController['state'], RadioGroupController['actions']> {
  return useReactPrimitive(RadioGroupDefinition, inputs) as ReactPrimitiveHookResult<RadioGroupController['state'], RadioGroupController['actions']>;
}
export const RadioGroup = Object.assign(RadioGroupRoot, { Provider: RadioGroupProvider, Root: RadioGroupRoot, Label: RadioGroupLabel, Item: RadioGroupItem, ItemControl: RadioGroupItemControl, ItemIndicator: RadioGroupItemIndicator, HiddenInput: RadioGroupHiddenInput, Error: RadioGroupError });

// uifn/solid/src/generated/radio-group.tsx
import { createContext, type JSX } from 'solid-js';
import { createRadioGroupController, type RadioGroupProps, type RadioGroupController } from '@uifn/core/primitives/radio-group';
import {
  createSolidPrimitiveInstanceId,
  SolidPrimitivePart,
  SolidPrimitiveRoot,
  type SolidPrimitiveContextValue,
  type SolidPrimitiveDefinition,
  type SolidPrimitivePartProps,
  type SolidPrimitiveRootProps,
} from '../internal/compound.jsx';

const RadioGroupContext = createContext<SolidPrimitiveContextValue<RadioGroupProps>>();
export const RadioGroupDefinition: SolidPrimitiveDefinition<RadioGroupProps> = {
  name: 'RadioGroup',
  family: 'selection-collection',
  kind: 'interactive-controller',
  rootPart: 'root',
  inputNames: ["value","defaultValue","name","orientation","loop","disabled","readOnly","required"],
  context: RadioGroupContext,
  createController: createRadioGroupController as never,
};

function RadioGroupRootElement(props: JSX.IntrinsicElements['fieldset']): JSX.Element {
  return <fieldset {...props} />;
}

export type RadioGroupRootProps = SolidPrimitiveRootProps<RadioGroupProps, 'fieldset'>;
export function RadioGroupRoot(props: RadioGroupRootProps): JSX.Element {
  const hydrationId = createSolidPrimitiveInstanceId();
  return <SolidPrimitiveRoot definition={RadioGroupDefinition} element="fieldset" renderElement={RadioGroupRootElement as never} hydrationId={hydrationId} props={props as never} />;
}

function RadioGroupLabelElement(props: JSX.IntrinsicElements['legend']): JSX.Element {
  return <legend {...props} />;
}

export type RadioGroupLabelProps = SolidPrimitivePartProps<RadioGroupController['parts']['label'], 'legend', false>;
export function RadioGroupLabel(props: RadioGroupLabelProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={RadioGroupDefinition as never}
      part="label"
      element="legend"
      renderElement={RadioGroupLabelElement as never}
      many={false}
      props={props as never}
    />
  );
}

function RadioGroupItemElement(props: JSX.IntrinsicElements['label']): JSX.Element {
  return <label {...props} />;
}

export type RadioGroupItemProps = SolidPrimitivePartProps<RadioGroupController['parts']['item'], 'label', true>;
export function RadioGroupItem(props: RadioGroupItemProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={RadioGroupDefinition as never}
      part="item"
      element="label"
      renderElement={RadioGroupItemElement as never}
      many={true}
      props={props as never}
    />
  );
}

function RadioGroupItemControlElement(props: JSX.IntrinsicElements['button']): JSX.Element {
  return <button {...props} />;
}

export type RadioGroupItemControlProps = SolidPrimitivePartProps<RadioGroupController['parts']['itemControl'], 'button', true>;
export function RadioGroupItemControl(props: RadioGroupItemControlProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={RadioGroupDefinition as never}
      part="itemControl"
      element="button"
      renderElement={RadioGroupItemControlElement as never}
      many={true}
      props={props as never}
    />
  );
}

function RadioGroupItemIndicatorElement(props: JSX.IntrinsicElements['span']): JSX.Element {
  return <span {...props} />;
}

export type RadioGroupItemIndicatorProps = SolidPrimitivePartProps<RadioGroupController['parts']['itemIndicator'], 'span', true>;
export function RadioGroupItemIndicator(props: RadioGroupItemIndicatorProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={RadioGroupDefinition as never}
      part="itemIndicator"
      element="span"
      renderElement={RadioGroupItemIndicatorElement as never}
      many={true}
      props={props as never}
    />
  );
}

function RadioGroupHiddenInputElement(props: JSX.IntrinsicElements['input']): JSX.Element {
  return <input {...props} />;
}

export type RadioGroupHiddenInputProps = SolidPrimitivePartProps<RadioGroupController['parts']['hiddenInput'], 'input', true>;
export function RadioGroupHiddenInput(props: RadioGroupHiddenInputProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={RadioGroupDefinition as never}
      part="hiddenInput"
      element="input"
      renderElement={RadioGroupHiddenInputElement as never}
      many={true}
      props={props as never}
    />
  );
}

function RadioGroupErrorElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type RadioGroupErrorProps = SolidPrimitivePartProps<RadioGroupController['parts']['error'], 'div', false>;
export function RadioGroupError(props: RadioGroupErrorProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={RadioGroupDefinition as never}
      part="error"
      element="div"
      renderElement={RadioGroupErrorElement as never}
      many={false}
      props={props as never}
    />
  );
}

export const RadioGroupProvider = RadioGroupRoot;
export const RadioGroup = /* @__PURE__ */ Object.assign(RadioGroupRoot, { Provider: RadioGroupProvider, Root: RadioGroupRoot, Label: RadioGroupLabel, Item: RadioGroupItem, ItemControl: RadioGroupItemControl, ItemIndicator: RadioGroupItemIndicator, HiddenInput: RadioGroupHiddenInput, Error: RadioGroupError });
