// uifn/react/src/generated/segment-group.tsx
'use client';

import * as React from 'react';
import { createSegmentGroupController, type SegmentGroupProps, type SegmentGroupController } from '@uifn/core/primitives/segment-group';
import {
  ReactPrimitivePart,
  ReactPrimitiveRoot,
  useReactPrimitive,
  type ReactPrimitiveBridge,
  type ReactPrimitiveDefinition,
  type ReactPrimitiveHookResult,
  type ReactPrimitivePartProps,
  type ReactPrimitiveRootProps,
} from '../internal/compound';

const SegmentGroupContext = React.createContext<ReactPrimitiveBridge<SegmentGroupProps> | null>(null);
const SegmentGroupDefinition: ReactPrimitiveDefinition<SegmentGroupProps> = {
  name: 'SegmentGroup',
  family: 'selection-collection',
  kind: 'interactive-controller',
  rootPart: 'root',
  inputNames: ["value","defaultValue","name","orientation","disabled","readOnly","required"],
  context: SegmentGroupContext,
  createController: createSegmentGroupController as never,
};

export type SegmentGroupRootProps = ReactPrimitiveRootProps<SegmentGroupProps, 'div'>;
export const SegmentGroupRoot = React.forwardRef<React.ElementRef<'div'>, SegmentGroupRootProps>((props, ref) => (
  <ReactPrimitiveRoot definition={SegmentGroupDefinition} element="div" forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
SegmentGroupRoot.displayName = 'SegmentGroupRoot';

export type SegmentGroupLabelProps = ReactPrimitivePartProps<SegmentGroupController['parts']['label'], 'span', false>;
export const SegmentGroupLabel = React.forwardRef<React.ElementRef<'span'>, SegmentGroupLabelProps>((props, ref) => (
  <ReactPrimitivePart definition={SegmentGroupDefinition as never} part="label" element="span" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
SegmentGroupLabel.displayName = 'SegmentGroupLabel';

export type SegmentGroupItemProps = ReactPrimitivePartProps<SegmentGroupController['parts']['item'], 'button', true>;
export const SegmentGroupItem = React.forwardRef<React.ElementRef<'button'>, SegmentGroupItemProps>((props, ref) => (
  <ReactPrimitivePart definition={SegmentGroupDefinition as never} part="item" element="button" many={true} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
SegmentGroupItem.displayName = 'SegmentGroupItem';

export type SegmentGroupItemTextProps = ReactPrimitivePartProps<SegmentGroupController['parts']['itemText'], 'span', true>;
export const SegmentGroupItemText = React.forwardRef<React.ElementRef<'span'>, SegmentGroupItemTextProps>((props, ref) => (
  <ReactPrimitivePart definition={SegmentGroupDefinition as never} part="itemText" element="span" many={true} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
SegmentGroupItemText.displayName = 'SegmentGroupItemText';

export type SegmentGroupIndicatorProps = ReactPrimitivePartProps<SegmentGroupController['parts']['indicator'], 'div', false>;
export const SegmentGroupIndicator = React.forwardRef<React.ElementRef<'div'>, SegmentGroupIndicatorProps>((props, ref) => (
  <ReactPrimitivePart definition={SegmentGroupDefinition as never} part="indicator" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
SegmentGroupIndicator.displayName = 'SegmentGroupIndicator';

export type SegmentGroupHiddenInputProps = ReactPrimitivePartProps<SegmentGroupController['parts']['hiddenInput'], 'input', false>;
export const SegmentGroupHiddenInput = React.forwardRef<React.ElementRef<'input'>, SegmentGroupHiddenInputProps>((props, ref) => (
  <ReactPrimitivePart definition={SegmentGroupDefinition as never} part="hiddenInput" element="input" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
SegmentGroupHiddenInput.displayName = 'SegmentGroupHiddenInput';

export const SegmentGroupProvider = SegmentGroupRoot;
export function useSegmentGroup(inputs: SegmentGroupProps = {} as SegmentGroupProps): ReactPrimitiveHookResult<SegmentGroupController['state'], SegmentGroupController['actions']> {
  return useReactPrimitive(SegmentGroupDefinition, inputs) as ReactPrimitiveHookResult<SegmentGroupController['state'], SegmentGroupController['actions']>;
}
export const SegmentGroup = Object.assign(SegmentGroupRoot, { Provider: SegmentGroupProvider, Root: SegmentGroupRoot, Label: SegmentGroupLabel, Item: SegmentGroupItem, ItemText: SegmentGroupItemText, Indicator: SegmentGroupIndicator, HiddenInput: SegmentGroupHiddenInput });

// uifn/solid/src/generated/segment-group.tsx
import { createContext, type JSX } from 'solid-js';
import { createSegmentGroupController, type SegmentGroupProps, type SegmentGroupController } from '@uifn/core/primitives/segment-group';
import {
  createSolidPrimitiveInstanceId,
  SolidPrimitivePart,
  SolidPrimitiveRoot,
  type SolidPrimitiveContextValue,
  type SolidPrimitiveDefinition,
  type SolidPrimitivePartProps,
  type SolidPrimitiveRootProps,
} from '../internal/compound.jsx';

const SegmentGroupContext = createContext<SolidPrimitiveContextValue<SegmentGroupProps>>();
export const SegmentGroupDefinition: SolidPrimitiveDefinition<SegmentGroupProps> = {
  name: 'SegmentGroup',
  family: 'selection-collection',
  kind: 'interactive-controller',
  rootPart: 'root',
  inputNames: ["value","defaultValue","name","orientation","disabled","readOnly","required"],
  context: SegmentGroupContext,
  createController: createSegmentGroupController as never,
};

function SegmentGroupRootElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type SegmentGroupRootProps = SolidPrimitiveRootProps<SegmentGroupProps, 'div'>;
export function SegmentGroupRoot(props: SegmentGroupRootProps): JSX.Element {
  const hydrationId = createSolidPrimitiveInstanceId();
  return <SolidPrimitiveRoot definition={SegmentGroupDefinition} element="div" renderElement={SegmentGroupRootElement as never} hydrationId={hydrationId} props={props as never} />;
}

function SegmentGroupLabelElement(props: JSX.IntrinsicElements['span']): JSX.Element {
  return <span {...props} />;
}

export type SegmentGroupLabelProps = SolidPrimitivePartProps<SegmentGroupController['parts']['label'], 'span', false>;
export function SegmentGroupLabel(props: SegmentGroupLabelProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={SegmentGroupDefinition as never}
      part="label"
      element="span"
      renderElement={SegmentGroupLabelElement as never}
      many={false}
      props={props as never}
    />
  );
}

function SegmentGroupItemElement(props: JSX.IntrinsicElements['button']): JSX.Element {
  return <button {...props} />;
}

export type SegmentGroupItemProps = SolidPrimitivePartProps<SegmentGroupController['parts']['item'], 'button', true>;
export function SegmentGroupItem(props: SegmentGroupItemProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={SegmentGroupDefinition as never}
      part="item"
      element="button"
      renderElement={SegmentGroupItemElement as never}
      many={true}
      props={props as never}
    />
  );
}

function SegmentGroupItemTextElement(props: JSX.IntrinsicElements['span']): JSX.Element {
  return <span {...props} />;
}

export type SegmentGroupItemTextProps = SolidPrimitivePartProps<SegmentGroupController['parts']['itemText'], 'span', true>;
export function SegmentGroupItemText(props: SegmentGroupItemTextProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={SegmentGroupDefinition as never}
      part="itemText"
      element="span"
      renderElement={SegmentGroupItemTextElement as never}
      many={true}
      props={props as never}
    />
  );
}

function SegmentGroupIndicatorElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type SegmentGroupIndicatorProps = SolidPrimitivePartProps<SegmentGroupController['parts']['indicator'], 'div', false>;
export function SegmentGroupIndicator(props: SegmentGroupIndicatorProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={SegmentGroupDefinition as never}
      part="indicator"
      element="div"
      renderElement={SegmentGroupIndicatorElement as never}
      many={false}
      props={props as never}
    />
  );
}

function SegmentGroupHiddenInputElement(props: JSX.IntrinsicElements['input']): JSX.Element {
  return <input {...props} />;
}

export type SegmentGroupHiddenInputProps = SolidPrimitivePartProps<SegmentGroupController['parts']['hiddenInput'], 'input', false>;
export function SegmentGroupHiddenInput(props: SegmentGroupHiddenInputProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={SegmentGroupDefinition as never}
      part="hiddenInput"
      element="input"
      renderElement={SegmentGroupHiddenInputElement as never}
      many={false}
      props={props as never}
    />
  );
}

export const SegmentGroupProvider = SegmentGroupRoot;
export const SegmentGroup = /* @__PURE__ */ Object.assign(SegmentGroupRoot, { Provider: SegmentGroupProvider, Root: SegmentGroupRoot, Label: SegmentGroupLabel, Item: SegmentGroupItem, ItemText: SegmentGroupItemText, Indicator: SegmentGroupIndicator, HiddenInput: SegmentGroupHiddenInput });
