// uifn/react/src/generated/signature-pad.tsx
'use client';

import * as React from 'react';
import { createSignaturePadController, type SignaturePadProps, type SignaturePadController } from '@uifn/core/primitives/signature-pad';
import {
  ReactPrimitivePart,
  ReactPrimitiveRoot,
  useReactPrimitive,
  type ReactPrimitiveBridge,
  type ReactPrimitiveDefinition,
  type ReactPrimitiveHookResult,
  type ReactPrimitivePartProps,
  type ReactPrimitiveRootProps,
} from '../internal/compound';

const SignaturePadContext = React.createContext<ReactPrimitiveBridge<SignaturePadProps> | null>(null);
const SignaturePadDefinition: ReactPrimitiveDefinition<SignaturePadProps> = {
  name: 'SignaturePad',
  family: 'range-gesture',
  kind: 'interactive-controller',
  rootPart: 'root',
  inputNames: ["value","defaultValue","name","disabled","readOnly","required"],
  context: SignaturePadContext,
  createController: createSignaturePadController as never,
};

export type SignaturePadRootProps = ReactPrimitiveRootProps<SignaturePadProps, 'div'>;
export const SignaturePadRoot = React.forwardRef<React.ElementRef<'div'>, SignaturePadRootProps>((props, ref) => (
  <ReactPrimitiveRoot definition={SignaturePadDefinition} element="div" forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
SignaturePadRoot.displayName = 'SignaturePadRoot';

export type SignaturePadLabelProps = ReactPrimitivePartProps<SignaturePadController['parts']['label'], 'label', false>;
export const SignaturePadLabel = React.forwardRef<React.ElementRef<'label'>, SignaturePadLabelProps>((props, ref) => (
  <ReactPrimitivePart definition={SignaturePadDefinition as never} part="label" element="label" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
SignaturePadLabel.displayName = 'SignaturePadLabel';

export type SignaturePadCanvasProps = ReactPrimitivePartProps<SignaturePadController['parts']['canvas'], 'canvas', false>;
export const SignaturePadCanvas = React.forwardRef<React.ElementRef<'canvas'>, SignaturePadCanvasProps>((props, ref) => (
  <ReactPrimitivePart definition={SignaturePadDefinition as never} part="canvas" element="canvas" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
SignaturePadCanvas.displayName = 'SignaturePadCanvas';

export type SignaturePadClearProps = ReactPrimitivePartProps<SignaturePadController['parts']['clear'], 'button', false>;
export const SignaturePadClear = React.forwardRef<React.ElementRef<'button'>, SignaturePadClearProps>((props, ref) => (
  <ReactPrimitivePart definition={SignaturePadDefinition as never} part="clear" element="button" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
SignaturePadClear.displayName = 'SignaturePadClear';

export type SignaturePadUndoProps = ReactPrimitivePartProps<SignaturePadController['parts']['undo'], 'button', false>;
export const SignaturePadUndo = React.forwardRef<React.ElementRef<'button'>, SignaturePadUndoProps>((props, ref) => (
  <ReactPrimitivePart definition={SignaturePadDefinition as never} part="undo" element="button" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
SignaturePadUndo.displayName = 'SignaturePadUndo';

export type SignaturePadStatusProps = ReactPrimitivePartProps<SignaturePadController['parts']['status'], 'div', false>;
export const SignaturePadStatus = React.forwardRef<React.ElementRef<'div'>, SignaturePadStatusProps>((props, ref) => (
  <ReactPrimitivePart definition={SignaturePadDefinition as never} part="status" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
SignaturePadStatus.displayName = 'SignaturePadStatus';

export type SignaturePadHiddenInputProps = ReactPrimitivePartProps<SignaturePadController['parts']['hiddenInput'], 'input', false>;
export const SignaturePadHiddenInput = React.forwardRef<React.ElementRef<'input'>, SignaturePadHiddenInputProps>((props, ref) => (
  <ReactPrimitivePart definition={SignaturePadDefinition as never} part="hiddenInput" element="input" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
SignaturePadHiddenInput.displayName = 'SignaturePadHiddenInput';

export const SignaturePadProvider = SignaturePadRoot;
export function useSignaturePad(inputs: SignaturePadProps = {} as SignaturePadProps): ReactPrimitiveHookResult<SignaturePadController['state'], SignaturePadController['actions']> {
  return useReactPrimitive(SignaturePadDefinition, inputs) as ReactPrimitiveHookResult<SignaturePadController['state'], SignaturePadController['actions']>;
}
export const SignaturePad = Object.assign(SignaturePadRoot, { Provider: SignaturePadProvider, Root: SignaturePadRoot, Label: SignaturePadLabel, Canvas: SignaturePadCanvas, Clear: SignaturePadClear, Undo: SignaturePadUndo, Status: SignaturePadStatus, HiddenInput: SignaturePadHiddenInput });

// uifn/solid/src/generated/signature-pad.tsx
import { createContext, type JSX } from 'solid-js';
import { createSignaturePadController, type SignaturePadProps, type SignaturePadController } from '@uifn/core/primitives/signature-pad';
import {
  createSolidPrimitiveInstanceId,
  SolidPrimitivePart,
  SolidPrimitiveRoot,
  type SolidPrimitiveContextValue,
  type SolidPrimitiveDefinition,
  type SolidPrimitivePartProps,
  type SolidPrimitiveRootProps,
} from '../internal/compound.jsx';

const SignaturePadContext = createContext<SolidPrimitiveContextValue<SignaturePadProps>>();
export const SignaturePadDefinition: SolidPrimitiveDefinition<SignaturePadProps> = {
  name: 'SignaturePad',
  family: 'range-gesture',
  kind: 'interactive-controller',
  rootPart: 'root',
  inputNames: ["value","defaultValue","name","disabled","readOnly","required"],
  context: SignaturePadContext,
  createController: createSignaturePadController as never,
};

function SignaturePadRootElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type SignaturePadRootProps = SolidPrimitiveRootProps<SignaturePadProps, 'div'>;
export function SignaturePadRoot(props: SignaturePadRootProps): JSX.Element {
  const hydrationId = createSolidPrimitiveInstanceId();
  return <SolidPrimitiveRoot definition={SignaturePadDefinition} element="div" renderElement={SignaturePadRootElement as never} hydrationId={hydrationId} props={props as never} />;
}

function SignaturePadLabelElement(props: JSX.IntrinsicElements['label']): JSX.Element {
  return <label {...props} />;
}

export type SignaturePadLabelProps = SolidPrimitivePartProps<SignaturePadController['parts']['label'], 'label', false>;
export function SignaturePadLabel(props: SignaturePadLabelProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={SignaturePadDefinition as never}
      part="label"
      element="label"
      renderElement={SignaturePadLabelElement as never}
      many={false}
      props={props as never}
    />
  );
}

function SignaturePadCanvasElement(props: JSX.IntrinsicElements['canvas']): JSX.Element {
  return <canvas {...props} />;
}

export type SignaturePadCanvasProps = SolidPrimitivePartProps<SignaturePadController['parts']['canvas'], 'canvas', false>;
export function SignaturePadCanvas(props: SignaturePadCanvasProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={SignaturePadDefinition as never}
      part="canvas"
      element="canvas"
      renderElement={SignaturePadCanvasElement as never}
      many={false}
      props={props as never}
    />
  );
}

function SignaturePadClearElement(props: JSX.IntrinsicElements['button']): JSX.Element {
  return <button {...props} />;
}

export type SignaturePadClearProps = SolidPrimitivePartProps<SignaturePadController['parts']['clear'], 'button', false>;
export function SignaturePadClear(props: SignaturePadClearProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={SignaturePadDefinition as never}
      part="clear"
      element="button"
      renderElement={SignaturePadClearElement as never}
      many={false}
      props={props as never}
    />
  );
}

function SignaturePadUndoElement(props: JSX.IntrinsicElements['button']): JSX.Element {
  return <button {...props} />;
}

export type SignaturePadUndoProps = SolidPrimitivePartProps<SignaturePadController['parts']['undo'], 'button', false>;
export function SignaturePadUndo(props: SignaturePadUndoProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={SignaturePadDefinition as never}
      part="undo"
      element="button"
      renderElement={SignaturePadUndoElement as never}
      many={false}
      props={props as never}
    />
  );
}

function SignaturePadStatusElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type SignaturePadStatusProps = SolidPrimitivePartProps<SignaturePadController['parts']['status'], 'div', false>;
export function SignaturePadStatus(props: SignaturePadStatusProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={SignaturePadDefinition as never}
      part="status"
      element="div"
      renderElement={SignaturePadStatusElement as never}
      many={false}
      props={props as never}
    />
  );
}

function SignaturePadHiddenInputElement(props: JSX.IntrinsicElements['input']): JSX.Element {
  return <input {...props} />;
}

export type SignaturePadHiddenInputProps = SolidPrimitivePartProps<SignaturePadController['parts']['hiddenInput'], 'input', false>;
export function SignaturePadHiddenInput(props: SignaturePadHiddenInputProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={SignaturePadDefinition as never}
      part="hiddenInput"
      element="input"
      renderElement={SignaturePadHiddenInputElement as never}
      many={false}
      props={props as never}
    />
  );
}

export const SignaturePadProvider = SignaturePadRoot;
export const SignaturePad = /* @__PURE__ */ Object.assign(SignaturePadRoot, { Provider: SignaturePadProvider, Root: SignaturePadRoot, Label: SignaturePadLabel, Canvas: SignaturePadCanvas, Clear: SignaturePadClear, Undo: SignaturePadUndo, Status: SignaturePadStatus, HiddenInput: SignaturePadHiddenInput });
