// uifn/react/src/generated/skeleton.tsx
'use client';

import * as React from 'react';
import { SkeletonContract, type SkeletonProps, type SkeletonContractParts } from '@uifn/core/primitives/skeleton';
import {
  ReactPrimitivePart,
  ReactPrimitiveRoot,
  useReactPrimitive,
  type ReactPrimitiveBridge,
  type ReactPrimitiveDefinition,
  type ReactPrimitiveHookResult,
  type ReactPrimitivePartProps,
  type ReactPrimitiveRootProps,
} from '../internal/compound';

const SkeletonContext = React.createContext<ReactPrimitiveBridge<SkeletonProps> | null>(null);
const SkeletonDefinition: ReactPrimitiveDefinition<SkeletonProps> = {
  name: 'Skeleton',
  family: 'status-feedback',
  kind: 'typed-static-contract',
  rootPart: 'root',
  inputNames: ["visible"],
  context: SkeletonContext,
  contract: SkeletonContract as never,
};

export type SkeletonRootProps = ReactPrimitiveRootProps<SkeletonProps, 'div'>;
export const SkeletonRoot = React.forwardRef<React.ElementRef<'div'>, SkeletonRootProps>((props, ref) => (
  <ReactPrimitiveRoot definition={SkeletonDefinition} element="div" forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
SkeletonRoot.displayName = 'SkeletonRoot';



export const SkeletonProvider = SkeletonRoot;
export function useSkeleton(inputs: SkeletonProps = {} as SkeletonProps): ReactPrimitiveHookResult<ReturnType<typeof SkeletonContract.getState>, Record<string, never>> {
  return useReactPrimitive(SkeletonDefinition, inputs) as ReactPrimitiveHookResult<ReturnType<typeof SkeletonContract.getState>, Record<string, never>>;
}
export const Skeleton = Object.assign(SkeletonRoot, { Provider: SkeletonProvider, Root: SkeletonRoot });

// uifn/solid/src/generated/skeleton.tsx
import { createContext, type JSX } from 'solid-js';
import { SkeletonContract, type SkeletonProps, type SkeletonContractParts } from '@uifn/core/primitives/skeleton';
import {
  createSolidPrimitiveInstanceId,
  SolidPrimitivePart,
  SolidPrimitiveRoot,
  type SolidPrimitiveContextValue,
  type SolidPrimitiveDefinition,
  type SolidPrimitivePartProps,
  type SolidPrimitiveRootProps,
} from '../internal/compound.jsx';

const SkeletonContext = createContext<SolidPrimitiveContextValue<SkeletonProps>>();
export const SkeletonDefinition: SolidPrimitiveDefinition<SkeletonProps> = {
  name: 'Skeleton',
  family: 'status-feedback',
  kind: 'typed-static-contract',
  rootPart: 'root',
  inputNames: ["visible"],
  context: SkeletonContext,
  contract: SkeletonContract as never,
};

function SkeletonRootElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type SkeletonRootProps = SolidPrimitiveRootProps<SkeletonProps, 'div'>;
export function SkeletonRoot(props: SkeletonRootProps): JSX.Element {
  const hydrationId = createSolidPrimitiveInstanceId();
  return <SolidPrimitiveRoot definition={SkeletonDefinition} element="div" renderElement={SkeletonRootElement as never} hydrationId={hydrationId} props={props as never} />;
}



export const SkeletonProvider = SkeletonRoot;
export const Skeleton = /* @__PURE__ */ Object.assign(SkeletonRoot, { Provider: SkeletonProvider, Root: SkeletonRoot });
