// uifn/react/src/generated/slider.tsx
'use client';

import * as React from 'react';
import { createSliderController, type SliderProps, type SliderController } from '@uifn/core/primitives/slider';
import {
  ReactPrimitivePart,
  ReactPrimitiveRoot,
  useReactPrimitive,
  type ReactPrimitiveBridge,
  type ReactPrimitiveDefinition,
  type ReactPrimitiveHookResult,
  type ReactPrimitivePartProps,
  type ReactPrimitiveRootProps,
} from '../internal/compound';

const SliderContext = React.createContext<ReactPrimitiveBridge<SliderProps> | null>(null);
const SliderDefinition: ReactPrimitiveDefinition<SliderProps> = {
  name: 'Slider',
  family: 'range-gesture',
  kind: 'interactive-controller',
  rootPart: 'root',
  inputNames: ["value","defaultValue","min","max","step","minStepsBetweenThumbs","orientation","dir","name","disabled","readOnly"],
  context: SliderContext,
  createController: createSliderController as never,
};

export type SliderRootProps = ReactPrimitiveRootProps<SliderProps, 'div'>;
export const SliderRoot = React.forwardRef<React.ElementRef<'div'>, SliderRootProps>((props, ref) => (
  <ReactPrimitiveRoot definition={SliderDefinition} element="div" forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
SliderRoot.displayName = 'SliderRoot';

export type SliderLabelProps = ReactPrimitivePartProps<SliderController['parts']['label'], 'label', false>;
export const SliderLabel = React.forwardRef<React.ElementRef<'label'>, SliderLabelProps>((props, ref) => (
  <ReactPrimitivePart definition={SliderDefinition as never} part="label" element="label" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
SliderLabel.displayName = 'SliderLabel';

export type SliderControlProps = ReactPrimitivePartProps<SliderController['parts']['control'], 'div', false>;
export const SliderControl = React.forwardRef<React.ElementRef<'div'>, SliderControlProps>((props, ref) => (
  <ReactPrimitivePart definition={SliderDefinition as never} part="control" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
SliderControl.displayName = 'SliderControl';

export type SliderTrackProps = ReactPrimitivePartProps<SliderController['parts']['track'], 'div', false>;
export const SliderTrack = React.forwardRef<React.ElementRef<'div'>, SliderTrackProps>((props, ref) => (
  <ReactPrimitivePart definition={SliderDefinition as never} part="track" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
SliderTrack.displayName = 'SliderTrack';

export type SliderRangeProps = ReactPrimitivePartProps<SliderController['parts']['range'], 'div', false>;
export const SliderRange = React.forwardRef<React.ElementRef<'div'>, SliderRangeProps>((props, ref) => (
  <ReactPrimitivePart definition={SliderDefinition as never} part="range" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
SliderRange.displayName = 'SliderRange';

export type SliderThumbProps = ReactPrimitivePartProps<SliderController['parts']['thumb'], 'div', true>;
export const SliderThumb = React.forwardRef<React.ElementRef<'div'>, SliderThumbProps>((props, ref) => (
  <ReactPrimitivePart definition={SliderDefinition as never} part="thumb" element="div" many={true} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
SliderThumb.displayName = 'SliderThumb';

export type SliderValueTextProps = ReactPrimitivePartProps<SliderController['parts']['valueText'], 'span', true>;
export const SliderValueText = React.forwardRef<React.ElementRef<'span'>, SliderValueTextProps>((props, ref) => (
  <ReactPrimitivePart definition={SliderDefinition as never} part="valueText" element="span" many={true} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
SliderValueText.displayName = 'SliderValueText';

export type SliderHiddenInputProps = ReactPrimitivePartProps<SliderController['parts']['hiddenInput'], 'input', true>;
export const SliderHiddenInput = React.forwardRef<React.ElementRef<'input'>, SliderHiddenInputProps>((props, ref) => (
  <ReactPrimitivePart definition={SliderDefinition as never} part="hiddenInput" element="input" many={true} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
SliderHiddenInput.displayName = 'SliderHiddenInput';

export const SliderProvider = SliderRoot;
export function useSlider(inputs: SliderProps = {} as SliderProps): ReactPrimitiveHookResult<SliderController['state'], SliderController['actions']> {
  return useReactPrimitive(SliderDefinition, inputs) as ReactPrimitiveHookResult<SliderController['state'], SliderController['actions']>;
}
export const Slider = Object.assign(SliderRoot, { Provider: SliderProvider, Root: SliderRoot, Label: SliderLabel, Control: SliderControl, Track: SliderTrack, Range: SliderRange, Thumb: SliderThumb, ValueText: SliderValueText, HiddenInput: SliderHiddenInput });

// uifn/solid/src/generated/slider.tsx
import { createContext, type JSX } from 'solid-js';
import { createSliderController, type SliderProps, type SliderController } from '@uifn/core/primitives/slider';
import {
  createSolidPrimitiveInstanceId,
  SolidPrimitivePart,
  SolidPrimitiveRoot,
  type SolidPrimitiveContextValue,
  type SolidPrimitiveDefinition,
  type SolidPrimitivePartProps,
  type SolidPrimitiveRootProps,
} from '../internal/compound.jsx';

const SliderContext = createContext<SolidPrimitiveContextValue<SliderProps>>();
export const SliderDefinition: SolidPrimitiveDefinition<SliderProps> = {
  name: 'Slider',
  family: 'range-gesture',
  kind: 'interactive-controller',
  rootPart: 'root',
  inputNames: ["value","defaultValue","min","max","step","minStepsBetweenThumbs","orientation","dir","name","disabled","readOnly"],
  context: SliderContext,
  createController: createSliderController as never,
};

function SliderRootElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type SliderRootProps = SolidPrimitiveRootProps<SliderProps, 'div'>;
export function SliderRoot(props: SliderRootProps): JSX.Element {
  const hydrationId = createSolidPrimitiveInstanceId();
  return <SolidPrimitiveRoot definition={SliderDefinition} element="div" renderElement={SliderRootElement as never} hydrationId={hydrationId} props={props as never} />;
}

function SliderLabelElement(props: JSX.IntrinsicElements['label']): JSX.Element {
  return <label {...props} />;
}

export type SliderLabelProps = SolidPrimitivePartProps<SliderController['parts']['label'], 'label', false>;
export function SliderLabel(props: SliderLabelProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={SliderDefinition as never}
      part="label"
      element="label"
      renderElement={SliderLabelElement as never}
      many={false}
      props={props as never}
    />
  );
}

function SliderControlElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type SliderControlProps = SolidPrimitivePartProps<SliderController['parts']['control'], 'div', false>;
export function SliderControl(props: SliderControlProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={SliderDefinition as never}
      part="control"
      element="div"
      renderElement={SliderControlElement as never}
      many={false}
      props={props as never}
    />
  );
}

function SliderTrackElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type SliderTrackProps = SolidPrimitivePartProps<SliderController['parts']['track'], 'div', false>;
export function SliderTrack(props: SliderTrackProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={SliderDefinition as never}
      part="track"
      element="div"
      renderElement={SliderTrackElement as never}
      many={false}
      props={props as never}
    />
  );
}

function SliderRangeElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type SliderRangeProps = SolidPrimitivePartProps<SliderController['parts']['range'], 'div', false>;
export function SliderRange(props: SliderRangeProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={SliderDefinition as never}
      part="range"
      element="div"
      renderElement={SliderRangeElement as never}
      many={false}
      props={props as never}
    />
  );
}

function SliderThumbElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type SliderThumbProps = SolidPrimitivePartProps<SliderController['parts']['thumb'], 'div', true>;
export function SliderThumb(props: SliderThumbProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={SliderDefinition as never}
      part="thumb"
      element="div"
      renderElement={SliderThumbElement as never}
      many={true}
      props={props as never}
    />
  );
}

function SliderValueTextElement(props: JSX.IntrinsicElements['span']): JSX.Element {
  return <span {...props} />;
}

export type SliderValueTextProps = SolidPrimitivePartProps<SliderController['parts']['valueText'], 'span', true>;
export function SliderValueText(props: SliderValueTextProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={SliderDefinition as never}
      part="valueText"
      element="span"
      renderElement={SliderValueTextElement as never}
      many={true}
      props={props as never}
    />
  );
}

function SliderHiddenInputElement(props: JSX.IntrinsicElements['input']): JSX.Element {
  return <input {...props} />;
}

export type SliderHiddenInputProps = SolidPrimitivePartProps<SliderController['parts']['hiddenInput'], 'input', true>;
export function SliderHiddenInput(props: SliderHiddenInputProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={SliderDefinition as never}
      part="hiddenInput"
      element="input"
      renderElement={SliderHiddenInputElement as never}
      many={true}
      props={props as never}
    />
  );
}

export const SliderProvider = SliderRoot;
export const Slider = /* @__PURE__ */ Object.assign(SliderRoot, { Provider: SliderProvider, Root: SliderRoot, Label: SliderLabel, Control: SliderControl, Track: SliderTrack, Range: SliderRange, Thumb: SliderThumb, ValueText: SliderValueText, HiddenInput: SliderHiddenInput });
