// uifn/react/src/generated/switch.tsx
'use client';

import * as React from 'react';
import { createSwitchController, type SwitchProps, type SwitchController } from '@uifn/core/primitives/switch';
import {
  ReactPrimitivePart,
  ReactPrimitiveRoot,
  useReactPrimitive,
  type ReactPrimitiveBridge,
  type ReactPrimitiveDefinition,
  type ReactPrimitiveHookResult,
  type ReactPrimitivePartProps,
  type ReactPrimitiveRootProps,
} from '../internal/compound';

const SwitchContext = React.createContext<ReactPrimitiveBridge<SwitchProps> | null>(null);
const SwitchDefinition: ReactPrimitiveDefinition<SwitchProps> = {
  name: 'Switch',
  family: 'forms-input',
  kind: 'interactive-controller',
  rootPart: 'root',
  inputNames: ["checked","defaultChecked","name","value","disabled","readOnly","required"],
  context: SwitchContext,
  createController: createSwitchController as never,
};

export type SwitchRootProps = ReactPrimitiveRootProps<SwitchProps, 'label'>;
export const SwitchRoot = React.forwardRef<React.ElementRef<'label'>, SwitchRootProps>((props, ref) => (
  <ReactPrimitiveRoot definition={SwitchDefinition} element="label" forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
SwitchRoot.displayName = 'SwitchRoot';

export type SwitchControlProps = ReactPrimitivePartProps<SwitchController['parts']['control'], 'button', false>;
export const SwitchControl = React.forwardRef<React.ElementRef<'button'>, SwitchControlProps>((props, ref) => (
  <ReactPrimitivePart definition={SwitchDefinition as never} part="control" element="button" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
SwitchControl.displayName = 'SwitchControl';

export type SwitchThumbProps = ReactPrimitivePartProps<SwitchController['parts']['thumb'], 'span', false>;
export const SwitchThumb = React.forwardRef<React.ElementRef<'span'>, SwitchThumbProps>((props, ref) => (
  <ReactPrimitivePart definition={SwitchDefinition as never} part="thumb" element="span" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
SwitchThumb.displayName = 'SwitchThumb';

export type SwitchLabelProps = ReactPrimitivePartProps<SwitchController['parts']['label'], 'span', false>;
export const SwitchLabel = React.forwardRef<React.ElementRef<'span'>, SwitchLabelProps>((props, ref) => (
  <ReactPrimitivePart definition={SwitchDefinition as never} part="label" element="span" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
SwitchLabel.displayName = 'SwitchLabel';

export type SwitchHiddenInputProps = ReactPrimitivePartProps<SwitchController['parts']['hiddenInput'], 'input', false>;
export const SwitchHiddenInput = React.forwardRef<React.ElementRef<'input'>, SwitchHiddenInputProps>((props, ref) => (
  <ReactPrimitivePart definition={SwitchDefinition as never} part="hiddenInput" element="input" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
SwitchHiddenInput.displayName = 'SwitchHiddenInput';

export const SwitchProvider = SwitchRoot;
export function useSwitch(inputs: SwitchProps = {} as SwitchProps): ReactPrimitiveHookResult<SwitchController['state'], SwitchController['actions']> {
  return useReactPrimitive(SwitchDefinition, inputs) as ReactPrimitiveHookResult<SwitchController['state'], SwitchController['actions']>;
}
export const Switch = Object.assign(SwitchRoot, { Provider: SwitchProvider, Root: SwitchRoot, Control: SwitchControl, Thumb: SwitchThumb, Label: SwitchLabel, HiddenInput: SwitchHiddenInput });

// uifn/solid/src/generated/switch.tsx
import { createContext, type JSX } from 'solid-js';
import { createSwitchController, type SwitchProps, type SwitchController } from '@uifn/core/primitives/switch';
import {
  createSolidPrimitiveInstanceId,
  SolidPrimitivePart,
  SolidPrimitiveRoot,
  type SolidPrimitiveContextValue,
  type SolidPrimitiveDefinition,
  type SolidPrimitivePartProps,
  type SolidPrimitiveRootProps,
} from '../internal/compound.jsx';

const SwitchContext = createContext<SolidPrimitiveContextValue<SwitchProps>>();
export const SwitchDefinition: SolidPrimitiveDefinition<SwitchProps> = {
  name: 'Switch',
  family: 'forms-input',
  kind: 'interactive-controller',
  rootPart: 'root',
  inputNames: ["checked","defaultChecked","name","value","disabled","readOnly","required"],
  context: SwitchContext,
  createController: createSwitchController as never,
};

function SwitchRootElement(props: JSX.IntrinsicElements['label']): JSX.Element {
  return <label {...props} />;
}

export type SwitchRootProps = SolidPrimitiveRootProps<SwitchProps, 'label'>;
export function SwitchRoot(props: SwitchRootProps): JSX.Element {
  const hydrationId = createSolidPrimitiveInstanceId();
  return <SolidPrimitiveRoot definition={SwitchDefinition} element="label" renderElement={SwitchRootElement as never} hydrationId={hydrationId} props={props as never} />;
}

function SwitchControlElement(props: JSX.IntrinsicElements['button']): JSX.Element {
  return <button {...props} />;
}

export type SwitchControlProps = SolidPrimitivePartProps<SwitchController['parts']['control'], 'button', false>;
export function SwitchControl(props: SwitchControlProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={SwitchDefinition as never}
      part="control"
      element="button"
      renderElement={SwitchControlElement as never}
      many={false}
      props={props as never}
    />
  );
}

function SwitchThumbElement(props: JSX.IntrinsicElements['span']): JSX.Element {
  return <span {...props} />;
}

export type SwitchThumbProps = SolidPrimitivePartProps<SwitchController['parts']['thumb'], 'span', false>;
export function SwitchThumb(props: SwitchThumbProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={SwitchDefinition as never}
      part="thumb"
      element="span"
      renderElement={SwitchThumbElement as never}
      many={false}
      props={props as never}
    />
  );
}

function SwitchLabelElement(props: JSX.IntrinsicElements['span']): JSX.Element {
  return <span {...props} />;
}

export type SwitchLabelProps = SolidPrimitivePartProps<SwitchController['parts']['label'], 'span', false>;
export function SwitchLabel(props: SwitchLabelProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={SwitchDefinition as never}
      part="label"
      element="span"
      renderElement={SwitchLabelElement as never}
      many={false}
      props={props as never}
    />
  );
}

function SwitchHiddenInputElement(props: JSX.IntrinsicElements['input']): JSX.Element {
  return <input {...props} />;
}

export type SwitchHiddenInputProps = SolidPrimitivePartProps<SwitchController['parts']['hiddenInput'], 'input', false>;
export function SwitchHiddenInput(props: SwitchHiddenInputProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={SwitchDefinition as never}
      part="hiddenInput"
      element="input"
      renderElement={SwitchHiddenInputElement as never}
      many={false}
      props={props as never}
    />
  );
}

export const SwitchProvider = SwitchRoot;
export const Switch = /* @__PURE__ */ Object.assign(SwitchRoot, { Provider: SwitchProvider, Root: SwitchRoot, Control: SwitchControl, Thumb: SwitchThumb, Label: SwitchLabel, HiddenInput: SwitchHiddenInput });
