// uifn/react/src/generated/toggle.tsx
'use client';

import * as React from 'react';
import { createToggleController, type ToggleProps, type ToggleController } from '@uifn/core/primitives/toggle';
import {
  ReactPrimitivePart,
  ReactPrimitiveRoot,
  useReactPrimitive,
  type ReactPrimitiveBridge,
  type ReactPrimitiveDefinition,
  type ReactPrimitiveHookResult,
  type ReactPrimitivePartProps,
  type ReactPrimitiveRootProps,
} from '../internal/compound';

const ToggleContext = React.createContext<ReactPrimitiveBridge<ToggleProps> | null>(null);
const ToggleDefinition: ReactPrimitiveDefinition<ToggleProps> = {
  name: 'Toggle',
  family: 'selection-collection',
  kind: 'interactive-controller',
  rootPart: 'root',
  inputNames: ["pressed","defaultPressed","disabled"],
  context: ToggleContext,
  createController: createToggleController as never,
};

export type ToggleRootProps = ReactPrimitiveRootProps<ToggleProps, 'button'>;
export const ToggleRoot = React.forwardRef<React.ElementRef<'button'>, ToggleRootProps>((props, ref) => (
  <ReactPrimitiveRoot definition={ToggleDefinition} element="button" forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
ToggleRoot.displayName = 'ToggleRoot';



export const ToggleProvider = ToggleRoot;
export function useToggle(inputs: ToggleProps = {} as ToggleProps): ReactPrimitiveHookResult<ToggleController['state'], ToggleController['actions']> {
  return useReactPrimitive(ToggleDefinition, inputs) as ReactPrimitiveHookResult<ToggleController['state'], ToggleController['actions']>;
}
export const Toggle = Object.assign(ToggleRoot, { Provider: ToggleProvider, Root: ToggleRoot });

// uifn/solid/src/generated/toggle.tsx
import { createContext, type JSX } from 'solid-js';
import { createToggleController, type ToggleProps, type ToggleController } from '@uifn/core/primitives/toggle';
import {
  createSolidPrimitiveInstanceId,
  SolidPrimitivePart,
  SolidPrimitiveRoot,
  type SolidPrimitiveContextValue,
  type SolidPrimitiveDefinition,
  type SolidPrimitivePartProps,
  type SolidPrimitiveRootProps,
} from '../internal/compound.jsx';

const ToggleContext = createContext<SolidPrimitiveContextValue<ToggleProps>>();
export const ToggleDefinition: SolidPrimitiveDefinition<ToggleProps> = {
  name: 'Toggle',
  family: 'selection-collection',
  kind: 'interactive-controller',
  rootPart: 'root',
  inputNames: ["pressed","defaultPressed","disabled"],
  context: ToggleContext,
  createController: createToggleController as never,
};

function ToggleRootElement(props: JSX.IntrinsicElements['button']): JSX.Element {
  return <button {...props} />;
}

export type ToggleRootProps = SolidPrimitiveRootProps<ToggleProps, 'button'>;
export function ToggleRoot(props: ToggleRootProps): JSX.Element {
  const hydrationId = createSolidPrimitiveInstanceId();
  return <SolidPrimitiveRoot definition={ToggleDefinition} element="button" renderElement={ToggleRootElement as never} hydrationId={hydrationId} props={props as never} />;
}



export const ToggleProvider = ToggleRoot;
export const Toggle = /* @__PURE__ */ Object.assign(ToggleRoot, { Provider: ToggleProvider, Root: ToggleRoot });
