// uifn/react/src/generated/tooltip.tsx
'use client';

import * as React from 'react';
import { createTooltipController, type TooltipProps, type TooltipController } from '@uifn/core/primitives/tooltip';
import {
  ReactPrimitivePart,
  ReactPrimitiveRoot,
  useReactPrimitive,
  type ReactPrimitiveBridge,
  type ReactPrimitiveDefinition,
  type ReactPrimitiveHookResult,
  type ReactPrimitivePartProps,
  type ReactPrimitiveRootProps,
} from '../internal/compound';

const TooltipContext = React.createContext<ReactPrimitiveBridge<TooltipProps> | null>(null);
const TooltipDefinition: ReactPrimitiveDefinition<TooltipProps> = {
  name: 'Tooltip',
  family: 'modal-overlay',
  kind: 'interactive-controller',
  rootPart: 'root',
  inputNames: ["open","defaultOpen","openDelay","closeDelay","placement","disabled"],
  context: TooltipContext,
  createController: createTooltipController as never,
};

export type TooltipRootProps = ReactPrimitiveRootProps<TooltipProps, 'span'>;
export const TooltipRoot = React.forwardRef<React.ElementRef<'span'>, TooltipRootProps>((props, ref) => (
  <ReactPrimitiveRoot definition={TooltipDefinition} element="span" forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
TooltipRoot.displayName = 'TooltipRoot';

export type TooltipTriggerProps = ReactPrimitivePartProps<TooltipController['parts']['trigger'], 'button', false>;
export const TooltipTrigger = React.forwardRef<React.ElementRef<'button'>, TooltipTriggerProps>((props, ref) => (
  <ReactPrimitivePart definition={TooltipDefinition as never} part="trigger" element="button" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
TooltipTrigger.displayName = 'TooltipTrigger';

export type TooltipPositionerProps = ReactPrimitivePartProps<TooltipController['parts']['positioner'], 'div', false>;
export const TooltipPositioner = React.forwardRef<React.ElementRef<'div'>, TooltipPositionerProps>((props, ref) => (
  <ReactPrimitivePart definition={TooltipDefinition as never} part="positioner" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
TooltipPositioner.displayName = 'TooltipPositioner';

export type TooltipContentProps = ReactPrimitivePartProps<TooltipController['parts']['content'], 'div', false>;
export const TooltipContent = React.forwardRef<React.ElementRef<'div'>, TooltipContentProps>((props, ref) => (
  <ReactPrimitivePart definition={TooltipDefinition as never} part="content" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
TooltipContent.displayName = 'TooltipContent';

export type TooltipArrowProps = ReactPrimitivePartProps<TooltipController['parts']['arrow'], 'div', false>;
export const TooltipArrow = React.forwardRef<React.ElementRef<'div'>, TooltipArrowProps>((props, ref) => (
  <ReactPrimitivePart definition={TooltipDefinition as never} part="arrow" element="div" many={false} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
TooltipArrow.displayName = 'TooltipArrow';

export const TooltipProvider = TooltipRoot;
export function useTooltip(inputs: TooltipProps = {} as TooltipProps): ReactPrimitiveHookResult<TooltipController['state'], TooltipController['actions']> {
  return useReactPrimitive(TooltipDefinition, inputs) as ReactPrimitiveHookResult<TooltipController['state'], TooltipController['actions']>;
}
export const Tooltip = Object.assign(TooltipRoot, { Provider: TooltipProvider, Root: TooltipRoot, Trigger: TooltipTrigger, Positioner: TooltipPositioner, Content: TooltipContent, Arrow: TooltipArrow });

// uifn/solid/src/generated/tooltip.tsx
import { createContext, type JSX } from 'solid-js';
import { createTooltipController, type TooltipProps, type TooltipController } from '@uifn/core/primitives/tooltip';
import {
  createSolidPrimitiveInstanceId,
  SolidPrimitivePart,
  SolidPrimitiveRoot,
  type SolidPrimitiveContextValue,
  type SolidPrimitiveDefinition,
  type SolidPrimitivePartProps,
  type SolidPrimitiveRootProps,
} from '../internal/compound.jsx';

const TooltipContext = createContext<SolidPrimitiveContextValue<TooltipProps>>();
export const TooltipDefinition: SolidPrimitiveDefinition<TooltipProps> = {
  name: 'Tooltip',
  family: 'modal-overlay',
  kind: 'interactive-controller',
  rootPart: 'root',
  inputNames: ["open","defaultOpen","openDelay","closeDelay","placement","disabled"],
  context: TooltipContext,
  createController: createTooltipController as never,
};

function TooltipRootElement(props: JSX.IntrinsicElements['span']): JSX.Element {
  return <span {...props} />;
}

export type TooltipRootProps = SolidPrimitiveRootProps<TooltipProps, 'span'>;
export function TooltipRoot(props: TooltipRootProps): JSX.Element {
  const hydrationId = createSolidPrimitiveInstanceId();
  return <SolidPrimitiveRoot definition={TooltipDefinition} element="span" renderElement={TooltipRootElement as never} hydrationId={hydrationId} props={props as never} />;
}

function TooltipTriggerElement(props: JSX.IntrinsicElements['button']): JSX.Element {
  return <button {...props} />;
}

export type TooltipTriggerProps = SolidPrimitivePartProps<TooltipController['parts']['trigger'], 'button', false>;
export function TooltipTrigger(props: TooltipTriggerProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={TooltipDefinition as never}
      part="trigger"
      element="button"
      renderElement={TooltipTriggerElement as never}
      many={false}
      props={props as never}
    />
  );
}

function TooltipPositionerElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type TooltipPositionerProps = SolidPrimitivePartProps<TooltipController['parts']['positioner'], 'div', false>;
export function TooltipPositioner(props: TooltipPositionerProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={TooltipDefinition as never}
      part="positioner"
      element="div"
      renderElement={TooltipPositionerElement as never}
      many={false}
      props={props as never}
    />
  );
}

function TooltipContentElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type TooltipContentProps = SolidPrimitivePartProps<TooltipController['parts']['content'], 'div', false>;
export function TooltipContent(props: TooltipContentProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={TooltipDefinition as never}
      part="content"
      element="div"
      renderElement={TooltipContentElement as never}
      many={false}
      props={props as never}
    />
  );
}

function TooltipArrowElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type TooltipArrowProps = SolidPrimitivePartProps<TooltipController['parts']['arrow'], 'div', false>;
export function TooltipArrow(props: TooltipArrowProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={TooltipDefinition as never}
      part="arrow"
      element="div"
      renderElement={TooltipArrowElement as never}
      many={false}
      props={props as never}
    />
  );
}

export const TooltipProvider = TooltipRoot;
export const Tooltip = /* @__PURE__ */ Object.assign(TooltipRoot, { Provider: TooltipProvider, Root: TooltipRoot, Trigger: TooltipTrigger, Positioner: TooltipPositioner, Content: TooltipContent, Arrow: TooltipArrow });
