// uifn/react/src/generated/toolbar.tsx
'use client';

import * as React from 'react';
import { createToolbarController, type ToolbarProps, type ToolbarController } from '@uifn/core/primitives/toolbar';
import {
  ReactPrimitivePart,
  ReactPrimitiveRoot,
  useReactPrimitive,
  type ReactPrimitiveBridge,
  type ReactPrimitiveDefinition,
  type ReactPrimitiveHookResult,
  type ReactPrimitivePartProps,
  type ReactPrimitiveRootProps,
} from '../internal/compound';

const ToolbarContext = React.createContext<ReactPrimitiveBridge<ToolbarProps> | null>(null);
const ToolbarDefinition: ReactPrimitiveDefinition<ToolbarProps> = {
  name: 'Toolbar',
  family: 'menu-navigation',
  kind: 'interactive-controller',
  rootPart: 'root',
  inputNames: ["orientation","loop","dir","disabled"],
  context: ToolbarContext,
  createController: createToolbarController as never,
};

export type ToolbarRootProps = ReactPrimitiveRootProps<ToolbarProps, 'div'>;
export const ToolbarRoot = React.forwardRef<React.ElementRef<'div'>, ToolbarRootProps>((props, ref) => (
  <ReactPrimitiveRoot definition={ToolbarDefinition} element="div" forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
ToolbarRoot.displayName = 'ToolbarRoot';

export type ToolbarButtonProps = ReactPrimitivePartProps<ToolbarController['parts']['button'], 'button', true>;
export const ToolbarButton = React.forwardRef<React.ElementRef<'button'>, ToolbarButtonProps>((props, ref) => (
  <ReactPrimitivePart definition={ToolbarDefinition as never} part="button" element="button" many={true} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
ToolbarButton.displayName = 'ToolbarButton';

export type ToolbarLinkProps = ReactPrimitivePartProps<ToolbarController['parts']['link'], 'a', true>;
export const ToolbarLink = React.forwardRef<React.ElementRef<'a'>, ToolbarLinkProps>((props, ref) => (
  <ReactPrimitivePart definition={ToolbarDefinition as never} part="link" element="a" many={true} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
ToolbarLink.displayName = 'ToolbarLink';

export type ToolbarToggleGroupProps = ReactPrimitivePartProps<ToolbarController['parts']['toggleGroup'], 'div', true>;
export const ToolbarToggleGroup = React.forwardRef<React.ElementRef<'div'>, ToolbarToggleGroupProps>((props, ref) => (
  <ReactPrimitivePart definition={ToolbarDefinition as never} part="toggleGroup" element="div" many={true} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
ToolbarToggleGroup.displayName = 'ToolbarToggleGroup';

export type ToolbarSeparatorProps = ReactPrimitivePartProps<ToolbarController['parts']['separator'], 'div', true>;
export const ToolbarSeparator = React.forwardRef<React.ElementRef<'div'>, ToolbarSeparatorProps>((props, ref) => (
  <ReactPrimitivePart definition={ToolbarDefinition as never} part="separator" element="div" many={true} forwardedRef={ref as React.ForwardedRef<HTMLElement>} props={props as never} />
));
ToolbarSeparator.displayName = 'ToolbarSeparator';

export const ToolbarProvider = ToolbarRoot;
export function useToolbar(inputs: ToolbarProps = {} as ToolbarProps): ReactPrimitiveHookResult<ToolbarController['state'], ToolbarController['actions']> {
  return useReactPrimitive(ToolbarDefinition, inputs) as ReactPrimitiveHookResult<ToolbarController['state'], ToolbarController['actions']>;
}
export const Toolbar = Object.assign(ToolbarRoot, { Provider: ToolbarProvider, Root: ToolbarRoot, Button: ToolbarButton, Link: ToolbarLink, ToggleGroup: ToolbarToggleGroup, Separator: ToolbarSeparator });

// uifn/solid/src/generated/toolbar.tsx
import { createContext, type JSX } from 'solid-js';
import { createToolbarController, type ToolbarProps, type ToolbarController } from '@uifn/core/primitives/toolbar';
import {
  createSolidPrimitiveInstanceId,
  SolidPrimitivePart,
  SolidPrimitiveRoot,
  type SolidPrimitiveContextValue,
  type SolidPrimitiveDefinition,
  type SolidPrimitivePartProps,
  type SolidPrimitiveRootProps,
} from '../internal/compound.jsx';

const ToolbarContext = createContext<SolidPrimitiveContextValue<ToolbarProps>>();
export const ToolbarDefinition: SolidPrimitiveDefinition<ToolbarProps> = {
  name: 'Toolbar',
  family: 'menu-navigation',
  kind: 'interactive-controller',
  rootPart: 'root',
  inputNames: ["orientation","loop","dir","disabled"],
  context: ToolbarContext,
  createController: createToolbarController as never,
};

function ToolbarRootElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type ToolbarRootProps = SolidPrimitiveRootProps<ToolbarProps, 'div'>;
export function ToolbarRoot(props: ToolbarRootProps): JSX.Element {
  const hydrationId = createSolidPrimitiveInstanceId();
  return <SolidPrimitiveRoot definition={ToolbarDefinition} element="div" renderElement={ToolbarRootElement as never} hydrationId={hydrationId} props={props as never} />;
}

function ToolbarButtonElement(props: JSX.IntrinsicElements['button']): JSX.Element {
  return <button {...props} />;
}

export type ToolbarButtonProps = SolidPrimitivePartProps<ToolbarController['parts']['button'], 'button', true>;
export function ToolbarButton(props: ToolbarButtonProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={ToolbarDefinition as never}
      part="button"
      element="button"
      renderElement={ToolbarButtonElement as never}
      many={true}
      props={props as never}
    />
  );
}

function ToolbarLinkElement(props: JSX.IntrinsicElements['a']): JSX.Element {
  return <a {...props} />;
}

export type ToolbarLinkProps = SolidPrimitivePartProps<ToolbarController['parts']['link'], 'a', true>;
export function ToolbarLink(props: ToolbarLinkProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={ToolbarDefinition as never}
      part="link"
      element="a"
      renderElement={ToolbarLinkElement as never}
      many={true}
      props={props as never}
    />
  );
}

function ToolbarToggleGroupElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type ToolbarToggleGroupProps = SolidPrimitivePartProps<ToolbarController['parts']['toggleGroup'], 'div', true>;
export function ToolbarToggleGroup(props: ToolbarToggleGroupProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={ToolbarDefinition as never}
      part="toggleGroup"
      element="div"
      renderElement={ToolbarToggleGroupElement as never}
      many={true}
      props={props as never}
    />
  );
}

function ToolbarSeparatorElement(props: JSX.IntrinsicElements['div']): JSX.Element {
  return <div {...props} />;
}

export type ToolbarSeparatorProps = SolidPrimitivePartProps<ToolbarController['parts']['separator'], 'div', true>;
export function ToolbarSeparator(props: ToolbarSeparatorProps): JSX.Element {
  return (
    <SolidPrimitivePart
      definition={ToolbarDefinition as never}
      part="separator"
      element="div"
      renderElement={ToolbarSeparatorElement as never}
      many={true}
      props={props as never}
    />
  );
}

export const ToolbarProvider = ToolbarRoot;
export const Toolbar = /* @__PURE__ */ Object.assign(ToolbarRoot, { Provider: ToolbarProvider, Root: ToolbarRoot, Button: ToolbarButton, Link: ToolbarLink, ToggleGroup: ToolbarToggleGroup, Separator: ToolbarSeparator });
