// apifn/svelte/src/RequestHistory.svelte
<!-- RequestHistory.svelte — list of past requests (UI-S-005) -->
<script lang="ts">
  import { createEventDispatcher } from "svelte";

  export interface HistoryEntry {
    id: string; timestamp: number; method: string; url: string;
    statusCode?: number; duration?: number;
    requestBody?: unknown; responseBody?: unknown;
    responseHeaders?: Record<string, string>; error?: string;
  }
  export let entries: HistoryEntry[] = [];
  export let maxEntries: number = 500;

  const dispatch = createEventDispatcher<{ select: HistoryEntry; clear: void }>();

  const METHOD_COLORS: Record<string, { bg: string; text: string }> = {
    get: { bg: "#065f46", text: "#6ee7b7" }, post: { bg: "#1e3a5f", text: "#93c5fd" },
    put: { bg: "#78350f", text: "#fcd34d" }, patch: { bg: "#5b21b6", text: "#c4b5fd" },
    delete: { bg: "#7f1d1d", text: "#fca5a5" },
  };

  $: visible = entries.slice(0, maxEntries).sort((a, b) => b.timestamp - a.timestamp);
  let selected: string | null = null;

  function statusColor(code?: number): string {
    if (!code) return "var(--apifn-text-muted)";
    if (code >= 200 && code < 300) return "var(--apifn-green)";
    if (code >= 400) return "var(--apifn-red)";
    return "var(--apifn-yellow)";
  }

  function mc(method: string) {
    return METHOD_COLORS[method.toLowerCase()] ?? { bg: "#2d3748", text: "#9ca3af" };
  }

  function toggleSelect(entry: HistoryEntry) {
    selected = selected === entry.id ? null : entry.id;
    dispatch("select", entry);
  }

  function clearHistory() { dispatch("clear"); }

  $: selectedEntry = visible.find((e) => e.id === selected) ?? null;
</script>

<div class="container">
  <div class="header">
    <span class="title">Request History ({visible.length})</span>
    <button class="clear-btn" on:click={clearHistory}>Clear</button>
  </div>

  {#if visible.length === 0}
    <div class="empty">No requests yet</div>
  {/if}

  {#each visible as entry}
    <div
      class="entry"
      class:active={entry.id === selected}
      role="button"
      tabindex="0"
      on:click={() => toggleSelect(entry)}
      on:keydown={(e) => e.key === "Enter" && toggleSelect(entry)}
    >
      <span class="method-tag" style="background:{mc(entry.method).bg};color:{mc(entry.method).text}">
        {entry.method.toUpperCase()}
      </span>
      <span class="url">{entry.url}</span>
      {#if entry.statusCode}
        <span class="status" style="color:{statusColor(entry.statusCode)}">{entry.statusCode}</span>
      {/if}
      {#if entry.duration !== undefined}
        <span class="duration">{entry.duration}ms</span>
      {/if}
      {#if entry.error}<span class="err-icon">✖</span>{/if}
    </div>

    {#if entry.id === selected && selectedEntry}
      <div class="detail">
        <div class="timestamp">{new Date(selectedEntry.timestamp).toLocaleString()}</div>
        {#if selectedEntry.error}
          <div class="error">{selectedEntry.error}</div>
        {/if}
        {#if selectedEntry.requestBody !== undefined}
          <div class="detail-section">
            <div class="detail-label">REQUEST BODY</div>
            <pre>{JSON.stringify(selectedEntry.requestBody, null, 2)}</pre>
          </div>
        {/if}
        {#if selectedEntry.responseBody !== undefined}
          <div class="detail-section">
            <div class="detail-label">RESPONSE BODY</div>
            <pre>{typeof selectedEntry.responseBody === "string" ? selectedEntry.responseBody : JSON.stringify(selectedEntry.responseBody, null, 2)}</pre>
          </div>
        {/if}
      </div>
    {/if}
  {/each}
</div>

<style>
  .container { font-family: var(--apifn-font-sans); color: var(--apifn-text); font-size: 13px; }
  .header { display: flex; align-items: center; justify-content: space-between; padding: 12px 16px; border-bottom: 1px solid var(--apifn-border); }
  .title { font-weight: 700; font-size: 13px; text-transform: uppercase; letter-spacing: .06em; color: var(--apifn-text-muted); }
  .clear-btn { background: none; border: 1px solid var(--apifn-border); border-radius: var(--apifn-radius); padding: 3px 10px; color: var(--apifn-text-muted); font-size: 12px; cursor: pointer; }
  .empty { padding: 32px; text-align: center; color: var(--apifn-text-muted); }
  .entry { display: flex; align-items: center; gap: 10px; padding: 10px 16px; border-bottom: 1px solid var(--apifn-border); cursor: pointer; transition: background .1s; }
  .entry:hover, .entry.active { background: var(--apifn-bg-surface-hover); }
  .method-tag { font-size: 11px; font-weight: 700; padding: 1px 6px; border-radius: 3px; font-family: var(--apifn-font-mono); min-width: 46px; text-align: center; }
  .url { flex: 1; font-family: var(--apifn-font-mono); font-size: 12px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
  .status { font-size: 12px; font-weight: 700; }
  .duration { font-size: 11px; color: var(--apifn-text-muted); min-width: 50px; text-align: right; }
  .err-icon { color: var(--apifn-red); font-size: 12px; }
  .detail { padding: 16px; background: var(--apifn-bg-surface); border-bottom: 1px solid var(--apifn-border); }
  .timestamp { font-size: 12px; color: var(--apifn-text-muted); margin-bottom: 8px; }
  .error { color: var(--apifn-red); margin-bottom: 8px; }
  .detail-section { margin-bottom: 8px; }
  .detail-label { font-size: 11px; font-weight: 700; color: var(--apifn-text-muted); margin-bottom: 4px; }
  pre { font-family: var(--apifn-font-mono); font-size: 12px; white-space: pre-wrap; word-break: break-all; color: var(--apifn-text); margin: 0; }
</style>

// apifn/react/src/RequestHistory.tsx
/**
 * RequestHistory — list of past requests (UI-R-005).
 * Chronological list, click to inspect, clear button, max 500 entries.
 */

import React, { useState } from "react";
import type { HistoryEntry } from "./types.js";
import { METHOD_COLORS } from "./styles/tokens.js";

export interface RequestHistoryProps {
    entries: HistoryEntry[];
    onClear?: () => void;
    onSelect?: (entry: HistoryEntry) => void;
    maxEntries?: number;
}

const s = {
    container: {
        fontFamily: "var(--apifn-font-sans)",
        color: "var(--apifn-text)",
        fontSize: "13px",
    } as React.CSSProperties,
    header: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        padding: "12px 16px",
        borderBottom: "1px solid var(--apifn-border)",
    } as React.CSSProperties,
    title: {
        fontWeight: 700,
        fontSize: "13px",
        textTransform: "uppercase" as const,
        letterSpacing: "0.06em",
        color: "var(--apifn-text-muted)",
    } as React.CSSProperties,
    clearBtn: {
        background: "none",
        border: "1px solid var(--apifn-border)",
        borderRadius: "var(--apifn-radius)",
        padding: "3px 10px",
        color: "var(--apifn-text-muted)",
        fontSize: "12px",
        cursor: "pointer",
    } as React.CSSProperties,
    empty: {
        padding: "32px",
        textAlign: "center" as const,
        color: "var(--apifn-text-muted)",
    } as React.CSSProperties,
    entry: (selected: boolean): React.CSSProperties => ({
        display: "flex",
        alignItems: "center",
        gap: "10px",
        padding: "10px 16px",
        borderBottom: "1px solid var(--apifn-border)",
        cursor: "pointer",
        background: selected ? "var(--apifn-bg-surface-hover)" : "transparent",
    }),
    method: (m: string): React.CSSProperties => {
        const c = METHOD_COLORS[m.toLowerCase()] ?? { bg: "#2d3748", text: "#9ca3af" };
        return { fontSize: "11px", fontWeight: 700, padding: "1px 6px", borderRadius: "3px", background: c.bg, color: c.text, fontFamily: "var(--apifn-font-mono)", minWidth: "46px", textAlign: "center" };
    },
    url: {
        flex: 1,
        fontFamily: "var(--apifn-font-mono)",
        fontSize: "12px",
        overflow: "hidden",
        textOverflow: "ellipsis",
        whiteSpace: "nowrap" as const,
    } as React.CSSProperties,
    status: (code?: number): React.CSSProperties => ({
        fontSize: "12px",
        fontWeight: 700,
        color: !code ? "var(--apifn-text-muted)" : code >= 200 && code < 300 ? "var(--apifn-green)" : code >= 400 ? "var(--apifn-red)" : "var(--apifn-yellow)",
    }),
    duration: {
        fontSize: "11px",
        color: "var(--apifn-text-muted)",
        minWidth: "50px",
        textAlign: "right" as const,
    } as React.CSSProperties,
    detail: {
        padding: "16px",
        background: "var(--apifn-bg-surface)",
        borderBottom: "1px solid var(--apifn-border)",
    } as React.CSSProperties,
    pre: {
        fontFamily: "var(--apifn-font-mono)",
        fontSize: "12px",
        whiteSpace: "pre-wrap" as const,
        wordBreak: "break-all" as const,
        color: "var(--apifn-text)",
        margin: 0,
    } as React.CSSProperties,
};

export function RequestHistory({ entries, onClear, onSelect, maxEntries = 500 }: RequestHistoryProps): React.ReactElement {
    const [selected, setSelected] = useState<string | null>(null);

    const visible = entries.slice(0, maxEntries).sort((a, b) => b.timestamp - a.timestamp);
    const selectedEntry = visible.find((e) => e.id === selected);

    function handleSelect(entry: HistoryEntry) {
        setSelected((s) => s === entry.id ? null : entry.id);
        onSelect?.(entry);
    }

    return (
        <div style={s.container}>
            <div style={s.header}>
                <span style={s.title}>Request History ({visible.length})</span>
                {onClear && (
                    <button style={s.clearBtn} onClick={onClear}>Clear</button>
                )}
            </div>

            {visible.length === 0 && <div style={s.empty}>No requests yet</div>}

            {visible.map((entry) => (
                <React.Fragment key={entry.id}>
                    <div style={s.entry(entry.id === selected)} onClick={() => handleSelect(entry)}>
                        <span style={s.method(entry.method)}>{entry.method.toUpperCase()}</span>
                        <span style={s.url}>{entry.url}</span>
                        {entry.statusCode && <span style={s.status(entry.statusCode)}>{entry.statusCode}</span>}
                        {entry.duration !== undefined && (
                            <span style={s.duration}>{entry.duration}ms</span>
                        )}
                        {entry.error && <span style={{ color: "var(--apifn-red)", fontSize: "12px" }}>✖</span>}
                    </div>

                    {entry.id === selected && selectedEntry && (
                        <div style={s.detail}>
                            <div style={{ marginBottom: "8px", fontSize: "12px", color: "var(--apifn-text-muted)" }}>
                                {new Date(selectedEntry.timestamp).toLocaleString()}
                            </div>
                            {selectedEntry.error && (
                                <div style={{ color: "var(--apifn-red)", marginBottom: "8px" }}>{selectedEntry.error}</div>
                            )}
                            {selectedEntry.requestBody !== undefined && (
                                <div style={{ marginBottom: "8px" }}>
                                    <div style={{ fontSize: "11px", fontWeight: 700, color: "var(--apifn-text-muted)", marginBottom: "4px" }}>REQUEST BODY</div>
                                    <pre style={s.pre}>{JSON.stringify(selectedEntry.requestBody, null, 2)}</pre>
                                </div>
                            )}
                            {selectedEntry.responseBody !== undefined && (
                                <div>
                                    <div style={{ fontSize: "11px", fontWeight: 700, color: "var(--apifn-text-muted)", marginBottom: "4px" }}>RESPONSE BODY</div>
                                    <pre style={s.pre}>{typeof selectedEntry.responseBody === "string" ? selectedEntry.responseBody : JSON.stringify(selectedEntry.responseBody, null, 2)}</pre>
                                </div>
                            )}
                        </div>
                    )}
                </React.Fragment>
            ))}
        </div>
    );
}
