// apifn/react/src/ResponseDiff.tsx
/**
 * ResponseDiff — side-by-side comparison of two API responses (UI-R-006).
 */

import React, { useMemo } from "react";
import type { TryItResponse } from "./types.js";

export interface ResponseDiffProps {
    left: TryItResponse;
    right: TryItResponse;
    leftLabel?: string;
    rightLabel?: string;
}

const s = {
    container: {
        fontFamily: "var(--apifn-font-sans)",
        color: "var(--apifn-text)",
    } as React.CSSProperties,
    header: {
        display: "flex",
        borderBottom: "1px solid var(--apifn-border)",
    } as React.CSSProperties,
    colHeader: {
        flex: 1,
        padding: "10px 16px",
        fontWeight: 700,
        fontSize: "13px",
        color: "var(--apifn-text-muted)",
    } as React.CSSProperties,
    summary: {
        display: "flex",
        gap: "24px",
        padding: "12px 16px",
        background: "var(--apifn-bg-surface)",
        borderBottom: "1px solid var(--apifn-border)",
        fontSize: "13px",
    } as React.CSSProperties,
    cols: {
        display: "flex",
        gap: "1px",
        background: "var(--apifn-border)",
    } as React.CSSProperties,
    col: {
        flex: 1,
        background: "var(--apifn-bg)",
        padding: "16px",
        overflow: "auto",
        maxHeight: "400px",
    } as React.CSSProperties,
    status: (code: number): React.CSSProperties => ({
        fontWeight: 700,
        color: code >= 200 && code < 300 ? "var(--apifn-green)" : code >= 400 ? "var(--apifn-red)" : "var(--apifn-yellow)",
    }),
    pre: {
        fontFamily: "var(--apifn-font-mono)",
        fontSize: "12px",
        whiteSpace: "pre-wrap" as const,
        wordBreak: "break-all" as const,
        color: "var(--apifn-text)",
        margin: 0,
    } as React.CSSProperties,
    diffLine: (kind: "added" | "removed" | "same"): React.CSSProperties => ({
        display: "block",
        background: kind === "added" ? "#065f4615" : kind === "removed" ? "#7f1d1d15" : "transparent",
        color: kind === "added" ? "var(--apifn-green)" : kind === "removed" ? "var(--apifn-red)" : "inherit",
        padding: "0 2px",
    }),
};

function diffLines(a: string, b: string): { kind: "same" | "added" | "removed"; text: string }[][] {
    const aLines = a.split("\n");
    const bLines = b.split("\n");
    const leftDiff: { kind: "same" | "added" | "removed"; text: string }[] = [];
    const rightDiff: { kind: "same" | "added" | "removed"; text: string }[] = [];

    const maxLen = Math.max(aLines.length, bLines.length);
    for (let i = 0; i < maxLen; i++) {
        const al = aLines[i] ?? "";
        const bl = bLines[i] ?? "";
        if (al === bl) {
            leftDiff.push({ kind: "same", text: al });
            rightDiff.push({ kind: "same", text: bl });
        } else {
            leftDiff.push({ kind: "removed", text: al });
            rightDiff.push({ kind: "added", text: bl });
        }
    }

    return [leftDiff, rightDiff];
}

function bodyToString(body: unknown): string {
    if (typeof body === "string") return body;
    return JSON.stringify(body, null, 2);
}

export function ResponseDiff({ left, right, leftLabel = "Before", rightLabel = "After" }: ResponseDiffProps): React.ReactElement {
    const [leftLines, rightLines] = useMemo(
        () => diffLines(bodyToString(left.body), bodyToString(right.body)),
        [left.body, right.body]
    );

    return (
        <div style={s.container}>
            <div style={s.header}>
                <div style={s.colHeader}>{leftLabel}</div>
                <div style={{ width: "1px", background: "var(--apifn-border)" }} />
                <div style={s.colHeader}>{rightLabel}</div>
            </div>

            {/* Summary comparison */}
            <div style={s.summary}>
                <span>
                    Status:{" "}
                    <span style={s.status(left.statusCode)}>{left.statusCode}</span>{" "}
                    →{" "}
                    <span style={s.status(right.statusCode)}>{right.statusCode}</span>
                </span>
                <span>
                    Duration:{" "}
                    <span style={{ fontFamily: "var(--apifn-font-mono)" }}>{left.durationMs}ms</span>{" "}
                    →{" "}
                    <span style={{ fontFamily: "var(--apifn-font-mono)", color: right.durationMs > left.durationMs ? "var(--apifn-red)" : "var(--apifn-green)" }}>
                        {right.durationMs}ms
                    </span>
                </span>
            </div>

            {/* Side-by-side body diff */}
            <div style={s.cols}>
                <div style={s.col}>
                    <pre style={s.pre}>
                        {leftLines.map((line, i) => (
                            <span key={i} style={s.diffLine(line.kind)}>{line.text}{"\n"}</span>
                        ))}
                    </pre>
                </div>
                <div style={s.col}>
                    <pre style={s.pre}>
                        {rightLines.map((line, i) => (
                            <span key={i} style={s.diffLine(line.kind)}>{line.text}{"\n"}</span>
                        ))}
                    </pre>
                </div>
            </div>
        </div>
    );
}

// apifn/svelte/src/ResponseDiff.svelte
<!-- ResponseDiff.svelte — side-by-side response comparison (UI-S-006) -->
<script lang="ts">
  export interface TryItResponse {
    statusCode: number; statusText: string;
    headers: Record<string, string>; body: unknown; durationMs: number;
  }
  export let left: TryItResponse;
  export let right: TryItResponse;
  export let leftLabel: string = "Before";
  export let rightLabel: string = "After";

  function bodyStr(b: unknown): string {
    return typeof b === "string" ? b : JSON.stringify(b, null, 2);
  }

  function diffLines(a: string, b: string): { left: { kind: string; text: string }[]; right: { kind: string; text: string }[] } {
    const al = a.split("\n");
    const bl = b.split("\n");
    const leftDiff: { kind: string; text: string }[] = [];
    const rightDiff: { kind: string; text: string }[] = [];
    const max = Math.max(al.length, bl.length);
    for (let i = 0; i < max; i++) {
      const a = al[i] ?? "";
      const b = bl[i] ?? "";
      if (a === b) { leftDiff.push({ kind: "same", text: a }); rightDiff.push({ kind: "same", text: b }); }
      else { leftDiff.push({ kind: "removed", text: a }); rightDiff.push({ kind: "added", text: b }); }
    }
    return { left: leftDiff, right: rightDiff };
  }

  $: diff = diffLines(bodyStr(left.body), bodyStr(right.body));

  function statusColor(code: number): string {
    if (code >= 200 && code < 300) return "var(--apifn-green)";
    if (code >= 400) return "var(--apifn-red)";
    return "var(--apifn-yellow)";
  }

  function lineStyle(kind: string): string {
    if (kind === "added") return "background:#065f4615;color:var(--apifn-green)";
    if (kind === "removed") return "background:#7f1d1d15;color:var(--apifn-red)";
    return "";
  }
</script>

<div class="container">
  <div class="header">
    <div class="col-header">{leftLabel}</div>
    <div class="divider"></div>
    <div class="col-header">{rightLabel}</div>
  </div>

  <!-- Summary -->
  <div class="summary">
    <span>
      Status:
      <span style="color:{statusColor(left.statusCode)};font-weight:700">{left.statusCode}</span>
      →
      <span style="color:{statusColor(right.statusCode)};font-weight:700">{right.statusCode}</span>
    </span>
    <span>
      Duration:
      <span class="mono">{left.durationMs}ms</span>
      →
      <span class="mono" style="color:{right.durationMs > left.durationMs ? 'var(--apifn-red)' : 'var(--apifn-green)'}">{right.durationMs}ms</span>
    </span>
  </div>

  <!-- Side-by-side diff -->
  <div class="cols">
    <div class="col">
      <pre>{#each diff.left as line}<span style={lineStyle(line.kind)}>{line.text + "\n"}</span>{/each}</pre>
    </div>
    <div class="separator"></div>
    <div class="col">
      <pre>{#each diff.right as line}<span style={lineStyle(line.kind)}>{line.text + "\n"}</span>{/each}</pre>
    </div>
  </div>
</div>

<style>
  .container { font-family: var(--apifn-font-sans); color: var(--apifn-text); }
  .header { display: flex; border-bottom: 1px solid var(--apifn-border); }
  .col-header { flex: 1; padding: 10px 16px; font-weight: 700; font-size: 13px; color: var(--apifn-text-muted); }
  .divider, .separator { width: 1px; background: var(--apifn-border); }
  .summary { display: flex; gap: 24px; padding: 12px 16px; background: var(--apifn-bg-surface); border-bottom: 1px solid var(--apifn-border); font-size: 13px; }
  .mono { font-family: var(--apifn-font-mono); }
  .cols { display: flex; gap: 0; background: var(--apifn-border); }
  .col { flex: 1; background: var(--apifn-bg); padding: 16px; overflow: auto; max-height: 400px; }
  pre { font-family: var(--apifn-font-mono); font-size: 12px; white-space: pre-wrap; word-break: break-all; color: var(--apifn-text); margin: 0; }
  span { display: block; padding: 0 2px; }
</style>
