// apifn/react/src/SchemaViewer.tsx
/**
 * SchemaViewer — renders a JSON Schema as a collapsible tree (UI-R-003).
 */

import React, { useState } from "react";
import type { SchemaObject } from "./types.js";

export interface SchemaViewerProps {
    schema: SchemaObject;
    name?: string;
    required?: boolean;
    expandDepth?: number;
    /** Current depth (internal) */
    depth?: number;
}

const s = {
    node: {
        fontFamily: "var(--apifn-font-mono, monospace)",
        fontSize: "13px",
        lineHeight: "1.6",
    } as React.CSSProperties,
    row: {
        display: "flex",
        alignItems: "baseline",
        gap: "6px",
        cursor: "pointer",
        padding: "2px 0",
    } as React.CSSProperties,
    toggle: {
        color: "var(--apifn-text-muted)",
        userSelect: "none" as const,
        width: "14px",
        flexShrink: 0,
    },
    name: {
        color: "var(--apifn-accent)",
        fontWeight: 600,
    } as React.CSSProperties,
    required: {
        color: "var(--apifn-red)",
        fontSize: "11px",
        fontWeight: 700,
    } as React.CSSProperties,
    typeBadge: (type: string): React.CSSProperties => ({
        fontSize: "11px",
        padding: "1px 6px",
        borderRadius: "4px",
        background:
            type === "string" ? "#065f4622" :
                type === "integer" || type === "number" ? "#1e3a5f22" :
                    type === "boolean" ? "#78350f22" :
                        type === "array" ? "#5b21b622" :
                            "#2d3748",
        color:
            type === "string" ? "var(--apifn-green)" :
                type === "integer" || type === "number" ? "var(--apifn-blue)" :
                    type === "boolean" ? "var(--apifn-yellow)" :
                        type === "array" ? "var(--apifn-purple)" :
                            "var(--apifn-text-muted)",
        border: "1px solid currentColor",
        opacity: 0.9,
    }),
    description: {
        color: "var(--apifn-text-muted)",
        fontSize: "12px",
    } as React.CSSProperties,
    children: {
        borderLeft: "1px solid var(--apifn-border)",
        marginLeft: "8px",
        paddingLeft: "12px",
    } as React.CSSProperties,
};

export function SchemaViewer({
    schema,
    name,
    required = false,
    expandDepth = 2,
    depth = 0,
}: SchemaViewerProps): React.ReactElement {
    const schemaType = schema.type as string | string[] | undefined;
    const primaryType = Array.isArray(schemaType) ? schemaType[0] : schemaType ?? "object";
    const hasChildren = primaryType === "object" && schema.properties;
    const isArray = primaryType === "array";
    const itemSchema = schema.items as SchemaObject | undefined;

    const [expanded, setExpanded] = useState(depth < expandDepth);

    return (
        <div style={s.node}>
            <div style={s.row} onClick={() => hasChildren && setExpanded((e) => !e)}>
                <span style={s.toggle}>
                    {hasChildren ? (expanded ? "▾" : "▸") : " "}
                </span>
                {name && <span style={s.name}>{name}</span>}
                {required && <span style={s.required}>required</span>}
                <span style={s.typeBadge(primaryType)}>{primaryType}</span>
                {isArray && itemSchema && (
                    <span style={{ ...s.typeBadge("array"), opacity: 0.6 }}>
                        {"of "}
                        {(itemSchema.type as string) ?? "object"}
                    </span>
                )}
                {typeof schema.description === "string" && (
                    <span style={s.description}>{schema.description}</span>
                )}
                {Array.isArray(schema.enum) && (
                    <span style={s.description}>
                        enum: {(schema.enum as unknown[]).map(String).join(" | ")}
                    </span>
                )}
            </div>

            {/* Object properties */}
            {(hasChildren && expanded && typeof schema.properties === "object" && schema.properties !== null) ? (
                <div style={s.children}>
                    {Object.entries(schema.properties as Record<string, unknown>).map(([propName, propSchema]) => {
                        const requiredFields = (schema.required ?? []) as string[];
                        return (
                            <SchemaViewer
                                key={propName}
                                schema={propSchema as SchemaObject}
                                name={propName}
                                required={requiredFields.includes(propName)}
                                expandDepth={expandDepth}
                                depth={depth + 1}
                            />
                        );
                    })}
                </div>
            ) : null}

            {/* Array items */}
            {(isArray && itemSchema && expanded && typeof itemSchema.properties === "object" && itemSchema.properties !== null) ? (
                <div style={s.children}>
                    <SchemaViewer
                        schema={itemSchema}
                        name="items"
                        expandDepth={expandDepth}
                        depth={depth + 1}
                    />
                </div>
            ) : null}
        </div>
    );
}

// apifn/svelte/src/SchemaViewer.svelte
<!-- SchemaViewer.svelte — renders a JSON Schema as a collapsible tree (UI-S-003) -->
<script lang="ts">
  import type { SchemaObject } from "@apifn/core";
  import SchemaViewer from "./SchemaViewer.svelte";

  export let schema: SchemaObject;
  export let name: string | undefined = undefined;
  export let required: boolean = false;
  export let expandDepth: number = 2;
  export let depth: number = 0;

  const schemaType = schema.type as string | string[] | undefined;
  const primaryType: string = Array.isArray(schemaType)
    ? (schemaType[0] ?? "object")
    : schemaType ?? "object";

  const hasChildren =
    primaryType === "object" &&
    typeof schema.properties === "object" &&
    schema.properties !== null;
  const isArray = primaryType === "array";
  const itemSchema = schema.items as SchemaObject | undefined;

  let expanded = depth < expandDepth;

  function typeColor(type: string): string {
    const map: Record<string, string> = {
      string: "var(--apifn-green)",
      integer: "var(--apifn-blue)",
      number: "var(--apifn-blue)",
      boolean: "var(--apifn-yellow)",
      array: "var(--apifn-purple)",
    };
    return map[type] ?? "var(--apifn-text-muted)";
  }

  function typeBg(type: string): string {
    const map: Record<string, string> = {
      string: "#065f4622",
      integer: "#1e3a5f22",
      number: "#1e3a5f22",
      boolean: "#78350f22",
      array: "#5b21b622",
    };
    return map[type] ?? "#2d3748";
  }

  $: requiredFields = (schema.required ?? []) as string[];
  $: properties = hasChildren
    ? Object.entries(schema.properties as Record<string, unknown>)
    : [];
</script>

<div class="schema-node">
  <!-- Row -->
  <div
    class="schema-row"
    role="button"
    tabindex="0"
    on:click={() => hasChildren && (expanded = !expanded)}
    on:keydown={(e) => e.key === "Enter" && hasChildren && (expanded = !expanded)}
  >
    <span class="toggle">{hasChildren ? (expanded ? "▾" : "▸") : " "}</span>
    {#if name}<span class="prop-name">{name}</span>{/if}
    {#if required}<span class="required">required</span>{/if}
    <span
      class="type-badge"
      style="color:{typeColor(primaryType)};background:{typeBg(primaryType)};border:1px solid {typeColor(primaryType)}44"
    >{primaryType}</span>
    {#if isArray && itemSchema}
      <span class="type-badge" style="opacity:0.6;color:var(--apifn-text-muted);background:#2d3748">
        of {itemSchema.type ?? "object"}
      </span>
    {/if}
    {#if typeof schema.description === "string"}
      <span class="description">{schema.description}</span>
    {/if}
    {#if Array.isArray(schema.enum)}
      <span class="description">enum: {schema.enum.map(String).join(" | ")}</span>
    {/if}
  </div>

  <!-- Object properties -->
  {#if hasChildren && expanded}
    <div class="children">
      {#each properties as [propName, propSchema]}
        <svelte:self
          schema={propSchema}
          name={propName}
          required={requiredFields.includes(propName)}
          {expandDepth}
          depth={depth + 1}
        />
      {/each}
    </div>
  {/if}

  <!-- Array items -->
  {#if isArray && itemSchema && expanded && typeof itemSchema.properties === "object" && itemSchema.properties !== null}
    <div class="children">
      <svelte:self schema={itemSchema} name="items" {expandDepth} depth={depth + 1} />
    </div>
  {/if}
</div>

<style>
  .schema-node {
    font-family: var(--apifn-font-mono, monospace);
    font-size: 13px;
    line-height: 1.6;
  }
  .schema-row {
    display: flex;
    align-items: baseline;
    gap: 6px;
    padding: 2px 0;
    cursor: pointer;
  }
  .toggle {
    color: var(--apifn-text-muted);
    user-select: none;
    width: 14px;
    flex-shrink: 0;
  }
  .prop-name { color: var(--apifn-accent); font-weight: 600; }
  .required { color: var(--apifn-red); font-size: 11px; font-weight: 700; }
  .type-badge {
    font-size: 11px;
    padding: 1px 6px;
    border-radius: 4px;
    opacity: 0.9;
  }
  .description { color: var(--apifn-text-muted); font-size: 12px; }
  .children {
    border-left: 1px solid var(--apifn-border);
    margin-left: 8px;
    padding-left: 12px;
  }
</style>
