// mdfn/components-solid/src/index.tsx
import { createMemo, createSignal, For, Index, onCleanup, Show, type Component } from "solid-js";
import { Button, Card, Input, ToolbarButton, ToolbarRoot } from "@uifn/components-solid";
import { captureMarkdownInsertion, createAuthoringModel, createToolbarModel, insertUploadedMarkdown, runToolbarAction, type AuthoringVersion, type MarkdownUploadResult, type SlashCommand, type ToolbarCommandTarget, type ToolbarGroup } from "@mdfn/components";
import { Transaction, canTransitionReview, createCommentThread, createSuggestion, decideSuggestion, replyToComment, setCommentResolved, transitionReview, type EditorController, type EditorialActor, type ReviewState } from "@mdfn/core";
import { MdfnEditor, createMdfnSignal, type MdfnEditorHandle, type MdfnEditorProps } from "@mdfn/solid";

type EditorMode = NonNullable<MdfnEditorProps["mode"]>;

export const MdfnToolbar: Component<{ controller: EditorController; groups?: readonly ToolbarGroup[]; ariaLabel?: string; class?: string; commandTarget?: ToolbarCommandTarget | null }> = (props) => {
  const snapshot = createMdfnSignal(() => props.controller);
  const model = () => { snapshot().version; return createToolbarModel(props.controller, props.groups, props.ariaLabel, props.commandTarget); };
  return <ToolbarRoot class={props.class} data-mdfn-component="toolbar" aria-label={model().ariaLabel}>
    <Index each={model().groups}>{(group) => <span role="group" aria-label={group().label} data-mdfn-toolbar-group={group().id}>
      <Index each={group().actions}>{(action) => <ToolbarButton value={action().id} type="button" disabled={action().disabled} aria-label={action().label} aria-pressed={action().pressed} title={action().shortcut ? `${action().label} (${action().shortcut})` : action().label} onClick={() => runToolbarAction(props.controller, action(), props.commandTarget)}>{action().label}</ToolbarButton>}</Index>
    </span>}</Index>
  </ToolbarRoot>;
};

export interface MdfnEditorShellProps extends MdfnEditorProps { readonly toolbarGroups?: readonly ToolbarGroup[]; readonly hideToolbar?: boolean; readonly hideAuthoringChrome?: boolean; readonly actor?: EditorialActor; readonly onSelectFiles?: (files: readonly File[]) => Promise<MarkdownUploadResult>; readonly onModeChange?: (mode: EditorMode) => void; readonly versions?: readonly AuthoringVersion[]; readonly onRestoreVersion?: (version: number) => void | Promise<void>; }
export const MdfnEditorShell: Component<MdfnEditorShellProps> = (props) => {
  const readOnly = (): boolean => props.readOnly === true || props.mode === "read-only";
  const insertionLifecycle = createMemo(() => {
    props.controller;
    const lifecycle = new AbortController();
    onCleanup(() => lifecycle.abort());
    return lifecycle;
  });
  const [commandTarget, setCommandTarget] = createSignal<ToolbarCommandTarget | null>(null);
  const [editor, setEditorHandle] = createSignal<MdfnEditorHandle | null>(null);
  const setEditor = (value: MdfnEditorHandle | null): void => {
    setEditorHandle(value);
    setCommandTarget(value ? {
      can: (command) => value.can(command as Parameters<MdfnEditorHandle["can"]>[0]),
      run: (command) => value.run(command as Parameters<MdfnEditorHandle["run"]>[0]),
    } : null);
    props.editorRef?.(value);
  };
  return <div class={props.class} data-mdfn-component="editor-shell">
    {!props.hideToolbar && !readOnly() && <MdfnToolbar controller={props.controller} groups={props.toolbarGroups} commandTarget={commandTarget()} />}
    {!props.hideAuthoringChrome && <MdfnAuthoringChrome controller={props.controller} editor={editor()} mode={props.mode} readOnly={readOnly()} actor={props.actor} onSelectFiles={props.onSelectFiles} onModeChange={props.onModeChange} versions={props.versions} onRestoreVersion={props.onRestoreVersion} />}
    <MdfnEditor
      controller={props.controller}
      mode={props.mode}
      readOnly={readOnly()}
      ariaLabel={props.ariaLabel}
      onLoadError={props.onLoadError}
      onFiles={async (files) => {
        const insertion = captureMarkdownInsertion(props.controller, insertionLifecycle().signal);
        try {
          await insertUploadedMarkdown(insertion, Promise.resolve(props.onSelectFiles?.(files)));
          await props.onFiles?.(files);
        } catch (error) {
          insertion.cancel();
          throw error;
        }
      }}
      editorRef={setEditor}
    />
  </div>;
};

export interface MdfnAuthoringChromeProps { readonly controller: EditorController; readonly editor?: MdfnEditorHandle | null; readonly mode?: EditorMode; readonly readOnly?: boolean; readonly compact?: boolean; readonly actor?: EditorialActor; readonly onSelectFiles?: (files: readonly File[]) => Promise<MarkdownUploadResult>; readonly onModeChange?: (mode: EditorMode) => void; readonly versions?: readonly AuthoringVersion[]; readonly onRestoreVersion?: (version: number) => void | Promise<void>; }
const editorModes: readonly EditorMode[] = ["visual", "source", "split", "preview", "read-only"];

export const MdfnAuthoringChrome: Component<MdfnAuthoringChromeProps> = (props) => {
  const readOnly = (): boolean => props.readOnly === true || props.mode === "read-only";
  const insertionLifecycle = createMemo(() => {
    props.controller;
    const lifecycle = new AbortController();
    onCleanup(() => lifecycle.abort());
    return lifecycle;
  });
  const snapshot = createMdfnSignal(() => props.controller);
  const [slashQuery, setSlashQuery] = createSignal("");
  const [link, setLink] = createSignal("");
  const [rows, setRows] = createSignal(2);
  const [columns, setColumns] = createSignal(2);
  const [comment, setComment] = createSignal("");
  const [suggestion, setSuggestion] = createSignal("");
  const [replies, setReplies] = createSignal<Record<string, string>>({});
  const [slashOpen, setSlashOpen] = createSignal(false);
  const actor = () => props.actor ?? { id: "local-author" };
  const model = createMemo(() => { snapshot().version; return createAuthoringModel(props.controller, { mode: props.mode, compact: props.compact, slashQuery: slashQuery(), slashOpen: slashOpen() }); });
  const commandTarget = (): ToolbarCommandTarget | null => props.editor ? { can: (command) => props.editor?.can(command as Parameters<MdfnEditorHandle["can"]>[0]) ?? false, run: (command) => props.editor?.run(command as Parameters<MdfnEditorHandle["run"]>[0]) ?? false } : null;
  const updateSidecar = (sidecar: NonNullable<ReturnType<EditorController["getState"]>["sidecar"]>, source: string): void => { props.controller.dispatch(new Transaction().setSidecar(sidecar).withSource(source)); };
  const addComment = (): void => {
    const state = props.controller.getState();
    const selection = state.selection?.kind === "text" ? state.selection : { anchor: 0, head: 0 };
    const result = createCommentThread({ sidecar: state.sidecar, anchor: { from: Math.min(selection.anchor, selection.head), to: Math.max(selection.anchor, selection.head) }, body: comment(), actor: actor(), markdownLength: state.markdown.length });
    updateSidecar(result.sidecar, "editorial:comment"); setComment("");
  };
  const setReview = (to: ReviewState): void => updateSidecar(transitionReview({ sidecar: props.controller.getState().sidecar, to, actor: actor() }), "editorial:review");
  const selectionRange = (): { from: number; to: number } => {
    const selection = props.controller.getState().selection;
    return selection?.kind === "text" ? { from: Math.min(selection.anchor, selection.head), to: Math.max(selection.anchor, selection.head) } : { from: 0, to: 0 };
  };
  const addSuggestion = (): void => {
    const state = props.controller.getState();
    const result = createSuggestion({ sidecar: state.sidecar, anchor: selectionRange(), replacement: suggestion(), actor: actor(), markdownLength: state.markdown.length });
    updateSidecar(result.sidecar, "editorial:suggestion");
    setSuggestion("");
  };
  const runSlash = (item: SlashCommand): void => {
    if (item.kind === "command" && item.command) props.editor?.run(item.command as Parameters<MdfnEditorHandle["run"]>[0]);
    if (item.kind === "table") props.editor?.insertTable(rows(), columns());
    if (item.kind === "link" && link()) props.editor?.setLink(link());
    setSlashOpen(false);
  };
  return <section data-mdfn-component="authoring-chrome" data-compact={model().compact ? "true" : "false"} aria-label="Markdown authoring controls">
    <nav aria-label="Editor mode" data-mdfn-surface="mode-switcher"><For each={editorModes}>{(mode) => <Button type="button" aria-pressed={props.mode === mode} disabled={!props.onModeChange} onClick={() => props.onModeChange?.(mode)}>{mode}</Button>}</For></nav>
    <Show when={!readOnly() && model().bubbleVisible}><div data-mdfn-surface="bubble-toolbar"><MdfnToolbar controller={props.controller} groups={model().bubble.groups} commandTarget={commandTarget()} ariaLabel="Selection formatting" /></div></Show>
    <Show when={!readOnly() && model().floatingVisible}><div data-mdfn-surface="floating-toolbar"><MdfnToolbar controller={props.controller} groups={model().floating.groups} commandTarget={commandTarget()} ariaLabel="Block formatting" /></div></Show>
    <Show when={!readOnly()}><Button type="button" aria-expanded={model().slashOpen} aria-controls="mdfn-insert-menu" onClick={() => setSlashOpen((value) => !value)}>Insert</Button></Show>
    <Show when={!readOnly() && model().slashOpen}><Card id="mdfn-insert-menu" data-mdfn-surface="slash-menu"><Card.Header><Card.Title>Insert</Card.Title></Card.Header><Card.Content><Input aria-label="Filter insert commands" value={slashQuery()} onInput={(event) => setSlashQuery(event.currentTarget.value)} /><div role="listbox" aria-label="Insert commands"><For each={model().slashCommands}>{(item) => <Button type="button" role="option" onClick={() => runSlash(item)}>{item.label}</Button>}</For></div></Card.Content></Card></Show>
    <Show when={!readOnly()}><Card data-mdfn-surface="link-editor"><Card.Header><Card.Title>Link</Card.Title></Card.Header><Card.Content><Input type="url" aria-label="Link URL" value={link()} onInput={(event) => setLink(event.currentTarget.value)} /><Button type="button" onClick={() => props.editor?.setLink(link())}>Apply link</Button><Button type="button" onClick={() => props.editor?.removeLink()}>Remove link</Button></Card.Content></Card></Show>
    <Show when={!readOnly()}><Card data-mdfn-surface="table-controls"><Card.Header><Card.Title>Table</Card.Title></Card.Header><Card.Content><Input type="number" min={1} max={100} aria-label="Table rows" value={rows()} onInput={(event) => setRows(Number(event.currentTarget.value))} /><Input type="number" min={1} max={100} aria-label="Table columns" value={columns()} onInput={(event) => setColumns(Number(event.currentTarget.value))} /><Button type="button" onClick={() => props.editor?.insertTable(rows(), columns())}>Insert table</Button></Card.Content></Card></Show>
    <Show when={!readOnly()}><Card data-mdfn-surface="file-controls"><Card.Header><Card.Title>Files</Card.Title></Card.Header><Card.Content><Input type="file" aria-label="Select files" multiple onChange={(event) => { const files = [...(event.currentTarget.files ?? [])]; const insertion = captureMarkdownInsertion(props.controller, insertionLifecycle().signal); const upload = props.onSelectFiles?.(files); if (!upload) { insertion.cancel(); return; } void insertUploadedMarkdown(insertion, upload).catch(() => insertion.cancel()); }} /></Card.Content></Card></Show>
    <nav data-mdfn-surface="outline" aria-label="Document outline"><ol><For each={model().outline}>{(item) => <li data-level={item.level}><Button type="button" onClick={() => item.from !== undefined && props.controller.dispatch(new Transaction().setSelection({ kind: "text", anchor: item.from, head: item.from }).withSource("outline"))}>{item.text}</Button></li>}</For></ol></nav>
    <aside data-mdfn-surface="diagnostics" aria-label="Markdown diagnostics" aria-live="polite"><ul><For each={model().diagnostics}>{(diagnostic) => <li data-severity={diagnostic.severity}>{diagnostic.message}</li>}</For></ul></aside>
    <Card data-mdfn-surface="editorial"><Card.Header><Card.Title>Review</Card.Title></Card.Header><Card.Content><p>State: {model().reviewState}</p><Show when={!readOnly()}><Input aria-label="Comment" value={comment()} onInput={(event) => setComment(event.currentTarget.value)} /><Button type="button" disabled={!comment().trim()} onClick={addComment}>Add comment</Button><Input aria-label="Suggestion replacement" value={suggestion()} onInput={(event) => setSuggestion(event.currentTarget.value)} /><Button type="button" onClick={addSuggestion}>Add suggestion</Button></Show><ul aria-label="Comments"><For each={model().comments ?? []}>{(thread) => <li><For each={thread.messages}>{(message) => <p>{message.body}</p>}</For>{thread.resolved ? "Resolved" : "Open"} <Show when={!readOnly()}><Input aria-label={`Reply to comment ${thread.id}`} value={replies()[thread.id] ?? ""} onInput={(event) => setReplies((current) => ({ ...current, [thread.id]: event.currentTarget.value }))} /><Button type="button" disabled={!(replies()[thread.id] ?? "").trim()} onClick={() => { updateSidecar(replyToComment({ sidecar: props.controller.getState().sidecar ?? {}, threadId: thread.id, body: replies()[thread.id] ?? "", actor: actor() }), "editorial:comment-reply"); setReplies((current) => ({ ...current, [thread.id]: "" })); }}>Reply</Button><Button type="button" onClick={() => updateSidecar(setCommentResolved({ sidecar: props.controller.getState().sidecar ?? {}, threadId: thread.id, resolved: !thread.resolved, actor: actor() }), "editorial:comment-resolution")}>{thread.resolved ? "Reopen" : "Resolve"}</Button></Show></li>}</For></ul><ul aria-label="Suggestions"><For each={model().suggestions ?? []}>{(entry) => <li>{entry.replacement} ({entry.status}) <Show when={entry.status === "pending" && !readOnly()}><Button type="button" onClick={() => decideSuggestion({ controller: props.controller, suggestionId: entry.id, decision: "accepted", actor: actor() })}>Accept</Button><Button type="button" onClick={() => decideSuggestion({ controller: props.controller, suggestionId: entry.id, decision: "rejected", actor: actor() })}>Reject</Button></Show></li>}</For></ul><Show when={!readOnly()}><div aria-label="Review transitions"><For each={["draft", "in-review", "changes-requested", "approved"] as const}>{(state) => <Button type="button" disabled={state === model().reviewState || !canTransitionReview(model().reviewState, state)} onClick={() => setReview(state)}>{state}</Button>}</For></div></Show></Card.Content></Card>
    <Card data-mdfn-surface="history"><Card.Header><Card.Title>Version history</Card.Title></Card.Header><Card.Content><ol aria-label="Document versions"><For each={props.versions ?? []}>{(entry) => <li>Version {entry.version}{entry.authorId ? ` by ${entry.authorId}` : ""} <Show when={props.onRestoreVersion && !readOnly()}><Button type="button" onClick={() => void props.onRestoreVersion?.(entry.version)}>Restore</Button></Show></li>}</For></ol><ol aria-label="Editorial activity"><For each={model().audit ?? []}>{(entry) => <li>{entry.action} by {entry.actorId}</li>}</For></ol></Card.Content></Card>
  </section>;
};

export { MdfnEditor } from "@mdfn/solid";
export const MDFN_COMPONENTS_SOLID_VERSION = "0.1.0" as const;

// mdfn/components-react/src/index.tsx
"use client";

import * as React from "react";
import { Button, Card, Input, ToolbarButton, ToolbarRoot } from "@uifn/components-react";
import { captureMarkdownInsertion, createAuthoringModel, createToolbarModel, insertUploadedMarkdown, runToolbarAction, type AuthoringVersion, type MarkdownUploadResult, type SlashCommand, type ToolbarCommandTarget, type ToolbarGroup } from "@mdfn/components";
import { Transaction, canTransitionReview, createCommentThread, createSuggestion, decideSuggestion, replyToComment, setCommentResolved, transitionReview, type EditorController, type EditorialActor, type ReviewState } from "@mdfn/core";
import { MdfnEditor, useMdfn, type MdfnEditorHandle, type MdfnEditorProps } from "@mdfn/react";

export interface MdfnToolbarProps extends Omit<React.ComponentProps<typeof ToolbarRoot>, "children"> {
  readonly controller: EditorController;
  readonly groups?: readonly ToolbarGroup[];
  readonly ariaLabel?: string;
  readonly commandTarget?: ToolbarCommandTarget | null;
}

export function MdfnToolbar({ controller, groups, ariaLabel, commandTarget, ...props }: MdfnToolbarProps): React.ReactElement {
  useMdfn(controller);
  const model = createToolbarModel(controller, groups, ariaLabel, commandTarget);
  return (
    <ToolbarRoot {...props} data-mdfn-component="toolbar" aria-label={model.ariaLabel}>
      {model.groups.map((group) => (
        <span key={group.id} role="group" aria-label={group.label} data-mdfn-toolbar-group={group.id}>
          {group.actions.map((action) => (
            <ToolbarButton key={action.id} value={action.id} type="button" disabled={action.disabled} aria-label={action.label} aria-pressed={action.pressed} title={action.shortcut ? `${action.label} (${action.shortcut})` : action.label} onClick={() => runToolbarAction(controller, action, commandTarget)}>
              {action.label}
            </ToolbarButton>
          ))}
        </span>
      ))}
    </ToolbarRoot>
  );
}

export interface MdfnEditorShellProps extends MdfnEditorProps {
  readonly toolbarGroups?: readonly ToolbarGroup[];
  readonly hideToolbar?: boolean;
  readonly hideAuthoringChrome?: boolean;
  readonly actor?: EditorialActor;
  readonly onSelectFiles?: (files: readonly File[]) => Promise<MarkdownUploadResult>;
  readonly onModeChange?: (mode: MdfnEditorProps["mode"]) => void;
  readonly versions?: readonly AuthoringVersion[];
  readonly onRestoreVersion?: (version: number) => void | Promise<void>;
}

export const MdfnEditorShell = React.forwardRef<React.ElementRef<typeof MdfnEditor>, MdfnEditorShellProps>(function MdfnEditorShell(
  { toolbarGroups, hideToolbar, hideAuthoringChrome, actor, onSelectFiles, onModeChange, versions, onRestoreVersion, className, onReady, ...props }, forwardedRef,
) {
  const readOnly = props.readOnly === true || props.mode === "read-only";
  const insertionLifecycle = React.useRef<AbortController | null>(null);
  React.useEffect(() => {
    const lifecycle = new AbortController();
    insertionLifecycle.current = lifecycle;
    return () => {
      lifecycle.abort();
      if (insertionLifecycle.current === lifecycle) insertionLifecycle.current = null;
    };
  }, [props.controller]);
  const [commandTarget, setCommandTarget] = React.useState<ToolbarCommandTarget | null>(null);
  const [editorHandle, setEditorHandle] = React.useState<MdfnEditorHandle | null>(null);
  const editorHandleRef = React.useRef<MdfnEditorHandle | null>(null);
  const setEditorRef = React.useCallback((handle: MdfnEditorHandle | null) => {
    editorHandleRef.current = handle;
    setEditorHandle(handle);
    setCommandTarget(handle ? {
      can: (command) => handle.can(command as Parameters<MdfnEditorHandle["can"]>[0]),
      run: (command) => handle.run(command as Parameters<MdfnEditorHandle["run"]>[0]),
    } : null);
    if (typeof forwardedRef === "function") forwardedRef(handle);
    else if (forwardedRef) forwardedRef.current = handle;
  }, [forwardedRef]);
  const editorReady = React.useCallback((handle: MdfnEditorHandle) => {
    setCommandTarget({
      can: (command) => handle.can(command as Parameters<MdfnEditorHandle["can"]>[0]),
      run: (command) => handle.run(command as Parameters<MdfnEditorHandle["run"]>[0]),
    });
    onReady?.(handle);
  }, [onReady]);
  const handleFiles = React.useCallback(async (files: readonly File[]) => {
    const insertion = captureMarkdownInsertion(props.controller, insertionLifecycle.current?.signal);
    try {
      await insertUploadedMarkdown(insertion, Promise.resolve(onSelectFiles?.(files)));
      await props.onFiles?.(files);
    } catch (error) {
      insertion.cancel();
      throw error;
    }
  }, [onSelectFiles, props.controller, props.onFiles]);
  return (
    <div className={className} data-mdfn-component="editor-shell">
      {!hideToolbar && !readOnly && <MdfnToolbar controller={props.controller} groups={toolbarGroups} commandTarget={commandTarget} />}
      {!hideAuthoringChrome && <MdfnAuthoringChrome controller={props.controller} editor={editorHandle} mode={props.mode} readOnly={readOnly} actor={actor} onSelectFiles={onSelectFiles} onModeChange={onModeChange} versions={versions} onRestoreVersion={onRestoreVersion} />}
      <MdfnEditor {...props} readOnly={readOnly} onFiles={handleFiles} ref={setEditorRef} onReady={editorReady} />
    </div>
  );
});

export interface MdfnAuthoringChromeProps {
  readonly controller: EditorController;
  readonly editor?: MdfnEditorHandle | null;
  readonly mode?: MdfnEditorProps["mode"];
  readonly readOnly?: boolean;
  readonly compact?: boolean;
  readonly actor?: EditorialActor;
  readonly onSelectFiles?: (files: readonly File[]) => Promise<MarkdownUploadResult>;
  readonly onModeChange?: (mode: MdfnEditorProps["mode"]) => void;
  readonly versions?: readonly AuthoringVersion[];
  readonly onRestoreVersion?: (version: number) => void | Promise<void>;
}

const modes = ["visual", "source", "split", "preview", "read-only"] as const;

export function MdfnAuthoringChrome({ controller, editor, mode = "visual", readOnly, compact, actor, onSelectFiles, onModeChange, versions = [], onRestoreVersion }: MdfnAuthoringChromeProps): React.ReactElement {
  const isReadOnly = readOnly === true || mode === "read-only";
  useMdfn(controller);
  const insertionLifecycle = React.useRef<AbortController | null>(null);
  React.useEffect(() => {
    const lifecycle = new AbortController();
    insertionLifecycle.current = lifecycle;
    return () => {
      lifecycle.abort();
      if (insertionLifecycle.current === lifecycle) insertionLifecycle.current = null;
    };
  }, [controller]);
  const [slashQuery, setSlashQuery] = React.useState("");
  const [link, setLink] = React.useState("");
  const [rows, setRows] = React.useState(2);
  const [columns, setColumns] = React.useState(2);
  const [comment, setComment] = React.useState("");
  const [suggestion, setSuggestion] = React.useState("");
  const [replies, setReplies] = React.useState<Record<string, string>>({});
  const [slashOpen, setSlashOpen] = React.useState(false);
  const model = createAuthoringModel(controller, { mode, compact, slashQuery, slashOpen });
  const runSlash = (item: SlashCommand): void => {
    if (item.kind === "command" && item.command) editor?.run(item.command as Parameters<MdfnEditorHandle["run"]>[0]);
    if (item.kind === "table") editor?.insertTable(rows, columns);
    if (item.kind === "link" && link) editor?.setLink(link);
    setSlashOpen(false);
  };
  const currentActor = actor ?? { id: "local-author" };
  const updateSidecar = (sidecar: NonNullable<ReturnType<EditorController["getState"]>["sidecar"]>, source: string): void => {
    controller.dispatch(new Transaction().setSidecar(sidecar).withSource(source));
  };
  const setReview = (next: ReviewState): void => updateSidecar(transitionReview({ sidecar: controller.getState().sidecar, to: next, actor: currentActor }), "editorial:review");
  const addComment = (): void => {
    const state = controller.getState();
    const selection = state.selection?.kind === "text" ? state.selection : { anchor: 0, head: 0 };
    const result = createCommentThread({ sidecar: state.sidecar, anchor: { from: Math.min(selection.anchor, selection.head), to: Math.max(selection.anchor, selection.head) }, body: comment, actor: currentActor, markdownLength: state.markdown.length });
    updateSidecar(result.sidecar, "editorial:comment");
    setComment("");
  };
  const selectionRange = (): { from: number; to: number } => {
    const selection = controller.getState().selection;
    return selection?.kind === "text"
      ? { from: Math.min(selection.anchor, selection.head), to: Math.max(selection.anchor, selection.head) }
      : { from: 0, to: 0 };
  };
  const addSuggestion = (): void => {
    const state = controller.getState();
    const result = createSuggestion({ sidecar: state.sidecar, anchor: selectionRange(), replacement: suggestion, actor: currentActor, markdownLength: state.markdown.length });
    updateSidecar(result.sidecar, "editorial:suggestion");
    setSuggestion("");
  };
  return (
    <section data-mdfn-component="authoring-chrome" data-compact={model.compact ? "true" : "false"} aria-label="Markdown authoring controls">
      <nav aria-label="Editor mode" data-mdfn-surface="mode-switcher">
        {modes.map((item) => <Button key={item} type="button" aria-pressed={mode === item} disabled={!onModeChange} onClick={() => onModeChange?.(item)}>{item}</Button>)}
      </nav>
      {!isReadOnly && model.bubbleVisible && <MdfnToolbar controller={controller} groups={model.bubble.groups} commandTarget={editor ? { can: (command) => editor.can(command as Parameters<MdfnEditorHandle["can"]>[0]), run: (command) => editor.run(command as Parameters<MdfnEditorHandle["run"]>[0]) } : null} ariaLabel="Selection formatting" data-mdfn-surface="bubble-toolbar" />}
      {!isReadOnly && model.floatingVisible && <div data-mdfn-surface="floating-toolbar"><MdfnToolbar controller={controller} groups={model.floating.groups} commandTarget={editor ? { can: (command) => editor.can(command as Parameters<MdfnEditorHandle["can"]>[0]), run: (command) => editor.run(command as Parameters<MdfnEditorHandle["run"]>[0]) } : null} ariaLabel="Block formatting" /></div>}
      {!isReadOnly && <Button type="button" aria-expanded={model.slashOpen} aria-controls="mdfn-insert-menu" onClick={() => setSlashOpen((value) => !value)}>Insert</Button>}
      {!isReadOnly && model.slashOpen && <Card id="mdfn-insert-menu" data-mdfn-surface="slash-menu">
        <Card.Header><Card.Title>Insert</Card.Title></Card.Header>
        <Card.Content>
          <Input aria-label="Filter insert commands" value={slashQuery} onChange={(event: React.ChangeEvent<HTMLInputElement>) => setSlashQuery(event.currentTarget.value)} />
          <div role="listbox" aria-label="Insert commands">{model.slashCommands.map((item) => <Button key={item.id} type="button" role="option" onClick={() => runSlash(item)}>{item.label}</Button>)}</div>
        </Card.Content>
      </Card>}
      {!isReadOnly && <Card data-mdfn-surface="link-editor">
        <Card.Header><Card.Title>Link</Card.Title></Card.Header>
        <Card.Content><Input type="url" aria-label="Link URL" value={link} onChange={(event: React.ChangeEvent<HTMLInputElement>) => setLink(event.currentTarget.value)} /><Button type="button" onClick={() => editor?.setLink(link)}>Apply link</Button><Button type="button" onClick={() => editor?.removeLink()}>Remove link</Button></Card.Content>
      </Card>}
      {!isReadOnly && <Card data-mdfn-surface="table-controls">
        <Card.Header><Card.Title>Table</Card.Title></Card.Header>
        <Card.Content><Input type="number" min={1} max={100} aria-label="Table rows" value={rows} onChange={(event: React.ChangeEvent<HTMLInputElement>) => setRows(Number(event.currentTarget.value))} /><Input type="number" min={1} max={100} aria-label="Table columns" value={columns} onChange={(event: React.ChangeEvent<HTMLInputElement>) => setColumns(Number(event.currentTarget.value))} /><Button type="button" onClick={() => editor?.insertTable(rows, columns)}>Insert table</Button></Card.Content>
      </Card>}
      {!isReadOnly && <Card data-mdfn-surface="file-controls">
        <Card.Header><Card.Title>Files</Card.Title></Card.Header>
        <Card.Content><Input type="file" aria-label="Select files" multiple onChange={(event: React.ChangeEvent<HTMLInputElement>) => {
          const files = [...(event.currentTarget.files ?? [])];
          const insertion = captureMarkdownInsertion(controller, insertionLifecycle.current?.signal);
          const upload = onSelectFiles?.(files);
          if (!upload) { insertion.cancel(); return; }
          void insertUploadedMarkdown(insertion, upload).catch(() => insertion.cancel());
        }} /></Card.Content>
      </Card>}
      <MdfnOutline controller={controller} />
      <MdfnDiagnostics controller={controller} />
      <Card data-mdfn-surface="editorial">
        <Card.Header><Card.Title>Review</Card.Title></Card.Header>
        <Card.Content>
          <p>State: {model.reviewState}</p>
          {!isReadOnly && <><Input aria-label="Comment" value={comment} onChange={(event: React.ChangeEvent<HTMLInputElement>) => setComment(event.currentTarget.value)} /><Button type="button" disabled={!comment.trim()} onClick={addComment}>Add comment</Button></>}
          {!isReadOnly && <><Input aria-label="Suggestion replacement" value={suggestion} onChange={(event: React.ChangeEvent<HTMLInputElement>) => setSuggestion(event.currentTarget.value)} /><Button type="button" onClick={addSuggestion}>Add suggestion</Button></>}
          <ul aria-label="Comments">{(model.comments ?? []).map((thread) => <li key={thread.id}>{thread.messages.map((message) => <p key={message.id}>{message.body}</p>)} {thread.resolved ? "Resolved" : "Open"} {!isReadOnly && <><Input aria-label={`Reply to comment ${thread.id}`} value={replies[thread.id] ?? ""} onChange={(event: React.ChangeEvent<HTMLInputElement>) => setReplies((current) => ({ ...current, [thread.id]: event.currentTarget.value }))} /><Button type="button" disabled={!(replies[thread.id] ?? "").trim()} onClick={() => { updateSidecar(replyToComment({ sidecar: controller.getState().sidecar ?? {}, threadId: thread.id, body: replies[thread.id] ?? "", actor: currentActor }), "editorial:comment-reply"); setReplies((current) => ({ ...current, [thread.id]: "" })); }}>Reply</Button><Button type="button" onClick={() => updateSidecar(setCommentResolved({ sidecar: controller.getState().sidecar ?? {}, threadId: thread.id, resolved: !thread.resolved, actor: currentActor }), "editorial:comment-resolution")}>{thread.resolved ? "Reopen" : "Resolve"}</Button></>}</li>)}</ul>
          <ul aria-label="Suggestions">{(model.suggestions ?? []).map((suggestion) => <li key={suggestion.id}>{suggestion.replacement} ({suggestion.status}) {suggestion.status === "pending" && !isReadOnly && <><Button type="button" onClick={() => decideSuggestion({ controller, suggestionId: suggestion.id, decision: "accepted", actor: currentActor })}>Accept</Button><Button type="button" onClick={() => decideSuggestion({ controller, suggestionId: suggestion.id, decision: "rejected", actor: currentActor })}>Reject</Button></>}</li>)}</ul>
          {!isReadOnly && <div aria-label="Review transitions">{(["draft", "in-review", "changes-requested", "approved"] as const).map((state) => <Button key={state} type="button" disabled={state === model.reviewState || !canTransitionReview(model.reviewState, state)} onClick={() => setReview(state)}>{state}</Button>)}</div>}
        </Card.Content>
      </Card>
      <Card data-mdfn-surface="history"><Card.Header><Card.Title>Version history</Card.Title></Card.Header><Card.Content><ol aria-label="Document versions">{versions.map((entry) => <li key={entry.version}>Version {entry.version}{entry.authorId ? ` by ${entry.authorId}` : ""} {onRestoreVersion && !isReadOnly && <Button type="button" onClick={() => void onRestoreVersion(entry.version)}>Restore</Button>}</li>)}</ol><ol aria-label="Editorial activity">{(model.audit ?? []).map((entry) => <li key={entry.id}>{entry.action} by {entry.actorId}</li>)}</ol></Card.Content></Card>
    </section>
  );
}

export function MdfnOutline({ controller }: { readonly controller: EditorController }): React.ReactElement {
  useMdfn(controller);
  const outline = createAuthoringModel(controller).outline;
  return <nav data-mdfn-surface="outline" aria-label="Document outline"><ol>{outline.map((item) => <li key={item.id} data-level={item.level}><Button type="button" onClick={() => item.from !== undefined && controller.dispatch(new Transaction().setSelection({ kind: "text", anchor: item.from, head: item.from }).withSource("outline"))}>{item.text}</Button></li>)}</ol></nav>;
}

export function MdfnDiagnostics({ controller }: { readonly controller: EditorController }): React.ReactElement {
  useMdfn(controller);
  const diagnostics = controller.getState().diagnostics;
  return <aside data-mdfn-surface="diagnostics" aria-label="Markdown diagnostics" aria-live="polite"><ul>{diagnostics.map((entry, index) => <li key={`${entry.code}-${index}`} data-severity={entry.severity}>{entry.message}</li>)}</ul></aside>;
}

export { MdfnEditor } from "@mdfn/react";
export const MDFN_COMPONENTS_REACT_VERSION = "0.1.0" as const;
